### ISSUE TITLE
Package not found @debank/rabby-api

### ISSUE THREAD

**Issue by lisabeyy** [RabbyHub/Rabby#1019]
Hey guys, where can we find the following package @debank/rabby-api. I would like to run the wallet locally :)

**Comment by vvvvvv1vvvvvv** [comment]
You can download from https://github.com/RabbyHub/Rabby/releases for run the wallet locally

**Comment by lisabeyy** [comment]
Yeah but I would like to contribute, I need to install all the dependencies, although this one is not found
error An unexpected error occurred: "https://registry.yarnpkg.com/@debank/rabby-api/-/rabby-api-0.5.4.tgz: Request failed \"404 Not Found\""

**Comment by a2468834** [comment]
Continuously got this error message too 🙌

**Comment by oritwoen** [comment]
Month after open this issue still not possible install package `@debank/rabby-api`. Please any of creator to change this package visibility to public.

I can't contribute without this...

**Comment by ajb** [comment]
this is truly insane. we're supposed to install some unknown software for the "open source" wallet?

**Comment by vvvvvv1vvvvvv** [comment]
Everyone can build Rabby locally now(develop branch), we have public all private packages
