### ISSUE TITLE
[Feature] Add filtering option on 'token', 'defi', 'nft' tab

### ISSUE THREAD

**Issue by hdadr** [RabbyHub/Rabby#1025]
![image](https://user-images.githubusercontent.com/22738075/194760312-ee8d130c-91ac-4e7d-94a8-a54381fe1ace.png)

Let me click on the chain icon and only show the tokens (/defi,nfts) belongs to the filtered chain.

**Comment by vvvvvv1vvvvvv** [comment]
Update to latest version then you can see it
