### ISSUE TITLE
[Chain Request] Add Support for WEMIX Mainnet or Custom RPC

### ISSUE THREAD

**Issue by residenthiago2011** [RabbyHub/Rabby#1066]
# WEMIX Mainnet
Network Name : WEMIX_Mainnet
New RPC URL : https://api.wemix.com/
ChainID : 1111
Symbol : WEMIX
Block Explorer URL : https://explorer.wemix.com/

**Comment by residenthiago2011** [comment]
Wen Wemix Mainnet?

**Comment by residenthiago2011** [comment]
Add Wemix Mainnet, ASAP Please!

**Comment by vvvvvv1vvvvvv** [comment]
https://twitter.com/Rabby_io/status/1655542080868077571
