### ISSUE TITLE
Flip function 

### ISSUE THREAD

**Issue by megabaks** [RabbyHub/Rabby#1137]
I tried 2 bridge by LayerZero: https://bridge.liquidswap.com/ and https://theaptosbridge.com/bridge
both has 2 problem with connection EVM wallets:
1. Can't connect Rabby
2. Metamask can be connected with previously removed cookies only. (Rabby extension enabled, flipped to mm)

About metamask connection.
1. I was connected previously
2. don't touch cookies, press "connect" ---> nothing happing
3. remove cookies, reload page, press "connect" ---> popup wallet...ok
4. second visit, act like 2. ---> can't connect. I have to act like 3. remove cookies again. 

BUT!!!
If Rabby extension disabled (chrome://extensions/bla-bla-bla...), I can connect with Metamask.
If I use Rabby's Flip - can't connect Metamask without previously removed cookies (Bridge_url --> Local Storage ---> Bridge_url)

Something wrong with the Flip function

**Comment by vvvvvv1vvvvvv** [comment]
it's a known issue: https://github.com/blocknative/web3-onboard/issues/1326 and we are try to touch LayerZero team for fix it

**Comment by megabaks** [comment]
Ok

**Comment by megabaks** [comment]
Ok
