### ISSUE TITLE
Enable more granular Max Priority Fee

### ISSUE THREAD

**Issue by gwenvador** [RabbyHub/Rabby#1138]
Please improve the max priority fee in the advanced settings. Currently Max priority fee is set to the gas price which is way overpaying for a transaction. In normal conditions it is around 1 - 2 gwei. This can be changed to a manual value that can be edited and disable the slider. 
Also replace max priority to tips as I would clarify things for the user perspective.

**Comment by vvvvvv1vvvvvv** [comment]
team is discussing
