### ISSUE TITLE
install fails with @debank/rabby-api: Not found

### ISSUE THREAD

**Issue by doums** [RabbyHub/Rabby#1163]
Hi,

Following the installation steps just fails with:

```
›  ~/D/n/rabby yarn
yarn install v1.22.19
warning package.json: License should be a valid SPDX license expression
warning rabby@0.58.0: License should be a valid SPDX license expression
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@debank/isomorphic/-/isomorphic-0.3.1.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/pierre/Documents/nym/rabby/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Trying by removing `yarn.lock` fails with `@debank/rabby-api: Not found`.

This another issue #1019 is opened since October 7th without any response!

`@debank/isomorphic` and `@debank/rabby-api` packages do not seem to be published (at least on public registry).

Can you clarify please how we are supposed to install locally if we plan to contribute?

**Comment by ajb** [comment]
+1

wtf?

**Comment by sullof** [comment]
+1

The package seems not to exist :-(

**Comment by novelnet** [comment]
+1
:(

**Comment by vvvvvv1vvvvvv** [comment]
@debank/rabby-api is not public currently since anti-bot requirement, should be public in future

**Comment by ajb** [comment]
that's disappointing that we can't build this wallet from source. how are we supposed to trust what it does?

**Comment by doums** [comment]
"Rabby is an open source browser plugin for the DeFi"

**Comment by novelnet** [comment]
Any workaround to get the extension build without debank/defi?

**Comment by novelnet** [comment]
Is it possible to get the rabby-api package locally and private please? I really have an urgent fix to do for personal use and cant build which initially was the reason why we choose rabby as open source. I'm willing to sign a NDA!

**Comment by novelnet** [comment]
> @debank/rabby-api is not public currently since anti-bot requirement, should be public in future

Any ETA? Can you contact me please? tobias@novelnet.de

**Comment by gmkung** [comment]
Too bad that @debank/rabby-api is not open source. Are there efforts to make a fork that uses an opensource alternative to @debank/rabby-api? We at Kleros have the [open data source available](https://kleros.notion.site/Blockchain-wallets-c9aad1cfc84f470daf7075cc8bbd3f10) for integration but would ideally like to join an existing effort to do this.

**Comment by vvvvvv1vvvvvv** [comment]
Everyone can build Rabby locally now(develop branch), we have public all private packages

**Comment by wsdt** [comment]
does that mean the API will also be open-sourced? :-)

**Comment by PhuocHofu** [comment]
> Awesome, thanks for the update on this!
@ajb i want to ask silly question, is this wallet really safe to use? thanks
