### ISSUE TITLE
Support optional mixing via HOPR's RPCh

### ISSUE THREAD

**Issue by phrohdoh** [RabbyHub/Rabby#1175]
https://hoprnet.org/rpch

https://youtu.be/-QwF878qJ8w

This will cost the Rabby team nothing (financially speaking) and provide a nice privacy benefit to users (in addition to the multiple issues requesting removal of tracking functionality).

**Comment by vvvvvv1vvvvvv** [comment]
Custom RPC is supported in v0.62.0
