### ISSUE TITLE
Can't see ETH on Arbitrum network

### ISSUE THREAD

**Issue by jadzeidan** [RabbyHub/Rabby#1198]
It seems I am unable to see Arbitrum ETH in my Rabby wallet. Even though I can confirm I see it on Arbiscan and on Dapps (for example Uniswap). But on Rabby it shows 0 balance. 

I think this is a bug in Rabby.

**Comment by vvvvvv1vvvvvv** [comment]
Sometimes there will be some delay in Rabby, is it works fine now? If not, join our Discord let me know more details https://discord.com/invite/seFBCWmUre

**Comment by Shareefgha** [comment]
> 

Thanks alot for your Help, you have noticed that I am not a Profi.
I have transfered ERC-20 Token ( Loopring LRC) from Crypto.com the App to my Hardwallet which is connected to Rabby.
I can see the Transaction comfirmed in the Transactions section but I can not see the Token in my coin list and therefore I am not able to controll it.

transaction hash: 0x2697a0932f20d3ebe98854e523dc752b64def93a1a72e1ded62eeba2352810ee
from: 0xc9219731adfa70645be14cd5d30507266f2092c5

can you help me please.
Thanks a lot and best regards
Ghareeb

**Comment by jadzeidan** [comment]
@Shareefgha which network did you make the transaction on? I can't see the transaction on either Ethereum or Arbitrum.

**Comment by vvvvvv1vvvvvv** [comment]
close since issue fixed
