### ISSUE TITLE
Can't see my tokens in the wallet.

### ISSUE THREAD

**Issue by Shareefgha** [RabbyHub/Rabby#1199]
I have transfered ERC-20 Token ( Loopring LRC) on Cronos network from Crypto.com the App to my Hardwallet which is connected to Rabby.
I can see the Transaction comfirmed in the Transactions section but I can not see the Token in my coin list and therefore I am not able to controll it.

transaction hash: 0x2697a0932f20d3ebe98854e523dc752b64def93a1a72e1ded62eeba2352810ee
from: 0xc9219731adfa70645be14cd5d30507266f2092c5

**Comment by vvvvvv1vvvvvv** [comment]
You can see it now
