### ISSUE TITLE
Goerli support?

### ISSUE THREAD

**Issue by DenisGorbachev** [RabbyHub/Rabby#1212]
I'm trying to use Rabby for testing my dApp. However, I can't connect it to Goerli testnet. Steps to reproduce:

* Go to https://chainlist.org/chain/5
* Click "Connect wallet"
* Click "Add to MetaMask"
* Notice the error: "The requested chain is not supported by Rabby yet"

I really like your UI, and I'd like to continue using Rabby for development, too. 

Is it possible to add support for Goerli?

**Comment by belg1o** [comment]
@vvvvvv1vvvvvv Rabby really needs to allow users to add their own chains based on their own RPCs.

**Comment by gigamesh** [comment]
Got really excited to try this but no test network support makes it unusable for devs :(

**Comment by nneverlander** [comment]
can you please add testnet support?

**Comment by ethan1141** [comment]
i would like to see it too

**Comment by steflsd** [comment]
Same issue my side. Want to test some dApps on Goerli

**Comment by ajberni** [comment]
would be especially helpful now, since ledger isn't connecting to metamask, and there is no other way to transact on goerli really (ledger live doesn't support goerli either)...

**Comment by ethan1141** [comment]
can you implement testnet on rabby

**Comment by sanbir** [comment]
Would love to see this feature too

**Comment by vvvvvv1vvvvvv** [comment]
supported now

**Comment by trendespresso** [comment]
Rabby doesn't support testnets!?!?
