### ISSUE TITLE
Update Connect to v9

### ISSUE THREAD

**Issue by Hannsek** [RabbyHub/Rabby#1221]
Trezor's Connect v9 is released.

Please update to the latest version. More info here: https://www.npmjs.com/package/@trezor/connect.

Please reach us if you find any issues.

**Comment by vvvvvv1vvvvvv** [comment]
Will schedule it soon

**Comment by vvvvvv1vvvvvv** [comment]
https://github.com/RabbyHub/eth-trezor-keyring/pull/4
Hi @Hannsek , the upgrade is ready, would you like to review the code?

**Comment by Hannsek** [comment]
As I am not a developer, A cannot help with that. 😅

**Comment by vvvvvv1vvvvvv** [comment]
resolved in #1252
