### ISSUE TITLE
Error when using the internal RPC endpoint and `eth_call` with `pending` block tag.

### ISSUE THREAD

**Issue by alexdupre** [RabbyHub/Rabby#1232]
I discovered a weird issue when sending `eth_call` with `pending` block tag, using the default RPC endpoint (in my case it was on Songbird blockchain, but I guess it's not chain dependent): all requests fail with ```{"message":"The height of the queried block exceeds the limit","code":-33001}```

The funny thing is that if I set a custom RPC endpoint, even the same as the internal one, it works as expected.

**Comment by vvvvvv1vvvvvv** [comment]
should be fixed now
