### ISSUE TITLE
Cronos gas fee after 1.0 upgrade

### ISSUE THREAD

**Issue by jorisc90** [RabbyHub/Rabby#1239]
Hi Rabby team,

Seems like Cronos gas calculations are broken after the 1.0 upgrade. The fee always sits at 62.5-65 CRO, whereas other wallets calculate a 1-2 CRO fee for a normal transaction.

Steps to reproduce

- go to any dAPP, I used cronosmm.finance
- try to do any swap operation
- see a high gas fee

**Comment by vvvvvv1vvvvvv** [comment]
fixed now

**Comment by jorisc90** [comment]
Just found that this issue has resurfaced. Made a whoopsie and payed ETH level gas fees.
