### ISSUE TITLE
UI - "Speed up" transaction windows title confusing

### ISSUE THREAD

**Issue by jadzeidan** [RabbyHub/Rabby#1240]
When clicking the "Speed up" feature in Rabby, the following window says "Send Token" (even when just sending ETH). I think it would be more clear if the title of the window is "Speed up transaction" 

![image](https://user-images.githubusercontent.com/42831937/213872673-c3c61e73-2729-4911-8820-0be41a416a7f.png)

**Comment by vvvvvv1vvvvvv** [comment]
Speed up is using a higher gasPrice to submit your transaction again, so the title is same as your origin transacion
