### ISSUE TITLE
[Chain Request] Add Support for zkSync Era Mainnet

### ISSUE THREAD

**Issue by residenthiago2011** [RabbyHub/Rabby#1294]
Network Name : zkSync Era Mainnet
New RPC URL : https://mainnet.era.zksync.io
ChainID : 324
Symbol : ETH
Block Explorer URL : https://explorer.zksync.io/

**Comment by rummzink** [comment]
We need ability to add custom networks

**Comment by vvvvvv1vvvvvv** [comment]
resolved in #1304
