### ISSUE TITLE
Search the importing adresses

### ISSUE THREAD

**Issue by Mouchoir** [RabbyHub/Rabby#1295]
Hello !

I'm trying to switch from Jaxx, where I had 3 active wallets (ETH, BTC, LTC) to Rabby (browser extension) but when I enter my seed phrase, I have literally hundreds of pages to pick addresses from.

is there a way to search / sort them so I can find my three addresses easily?

Thanks a lot for your help

**Comment by CryptoKira** [comment]
Pull request made: https://github.com/RabbyHub/Rabby/pull/1485

**Comment by vvvvvv1vvvvvv** [comment]
v0.92.3 supported
