### ISSUE TITLE
Feature request: Searchable wallets

### ISSUE THREAD

**Issue by arkaydeus** [RabbyHub/Rabby#1311]
**Feature request**
The ability to search for wallets by name

**AS A**
User of many wallets
**I WANT TO**
Search for a specific wallet by name
**SO THAT I CAN**
Find a wallet in a very long list of wallets

Power users commonly have a lot of wallets. Rabby, by default sorts wallets by balance, but the balances aren't always up to date. This can make finding wallets really hard. It's also compounded by the lack of full screen mode.

This feature request is for a wallet search box and the ability to start typing the name of the wallet and to then have the wallet list filtered by these names.

Lack of this feature for users of many wallets is often cited as a reason not to switch to Rabby which is a shame.

**Comment by CryptoKira** [comment]
Pull request made: https://github.com/RabbyHub/Rabby/pull/1485

**Comment by vvvvvv1vvvvvv** [comment]
v0.92.3 supported
