### ISSUE TITLE
support for window.ethereum.providers or window.evmproviders

### ISSUE THREAD

**Issue by quagliero** [RabbyHub/Rabby#1313]
Hi,

Sharing what I saw over on the rainbowkit github with a PR that was opened to add Rabby:

https://github.com/rainbow-me/rainbowkit/pull/1037#issuecomment-1502672475

> We'll move forward with the connector support, but would definitely like to see support for window.ethereum.providers or window.evmproviders in Rabby so that we can maintain the RainbowKit switching UX. Please do reach back out to amend in the future.

**Comment by vvvvvv1vvvvvv** [comment]
EIP-6963 supported
