### ISSUE TITLE
Cannot use more than one QR wallet

### ISSUE THREAD

**Issue by ojura** [RabbyHub/Rabby#1314]
If I try adding a second Airgap wallet (with a different secret), after scanning the QR code, I get a screen to add more derived addresses from the QR wallet that was added first.

In other words, it seems that Rabby supports only a single QR wallet.

**Comment by johan-lorentzon** [comment]
Same problem for me, and I also find no way to remove the imported wallet

**Comment by latifrons** [comment]
I happen to imported another airgap wallet. However Rabby always use the latest scanned QR code as the secret and account to sign, no matter which wallet I select in the UI.
After I rescan the first wallet's QR the signing process is fine. However I can never use second airgap wallet anymore.

**Comment by vvvvvv1vvvvvv** [comment]
<img width="989" alt="image" src="https://github.com/RabbyHub/Rabby/assets/86296331/cca843ed-cf44-4a78-9a98-89e880a9f07a">
You can click "Switch to another Keystone" for forget current device after v0.92.3, simply click import Keystone address to find it
