### ISSUE TITLE
`@debank/rabby-api` is not available on npm

### ISSUE THREAD

**Issue by oxSaturn** [RabbyHub/Rabby#1317]
Hi, Rabby has this `@debank/rabby-api` [dependency](https://github.com/RabbyHub/Rabby/blob/develop/package.json#L20) which is not published on npm.

<img width="947" alt="" src="https://user-images.githubusercontent.com/126733611/231695933-f1b22dcd-b80e-47a7-a582-1b3c372dc80d.png">

**Comment by benma** [comment]
@vvvvvv1vvvvvv please take a look, this prevents us from building the extension.

**Comment by xsfunc** [comment]
same

**Comment by oxSaturn** [comment]
Seems someone reported it a long time ago here https://github.com/RabbyHub/Rabby/issues/1163

**Comment by benma** [comment]
@vvvvvv1vvvvvv what is the solution? Some BitBox02 users are reporting connection problems and we have no way for us to build the app to debug.

**Comment by vvvvvv1vvvvvv** [comment]
@benma Can you ask Jad to invite you to the telegram group? I will help you for debug

**Comment by omertalib42** [comment]
Just pinging this issue to see if there will be any changes, @vvvvvv1vvvvvv. I had some ideas to push for, but sadly it's impossible to build to project.

**Comment by vvvvvv1vvvvvv** [comment]
Everyone can build Rabby locally now(develop branch), we have public all private packages
