### ISSUE TITLE
Option to turn off automatic balance scanning of all the wallets

### ISSUE THREAD

**Issue by mkumas** [RabbyHub/Rabby#1322]
When using multiple wallets(i.e. 10+ wallets) rabby becomes unresponsive and not usable while it tries to fetch all the information for all of the wallets. A simple option to turn off automatic scanning of wallets may fix it.

**Comment by vvvvvv1vvvvvv** [comment]
Rabby will not automatic scan balance of all your wallets, only if scan the specify wallet balance when you switch to it, can you make a screen recording to show us the unresponsive and usable?

**Comment by Jones098** [comment]
All rights reserved that to mine own memory thanks 👍
