### ISSUE TITLE
ShimmerEVM testnet support

### ISSUE THREAD

**Issue by discochuck** [RabbyHub/Rabby#1360]
Would love to see support for ShimmerEVM testnet!

launch announcement:
https://blog.shimmer.network/shimmerevm-testnet-launch/

--snip
Network name: ShimmerEVM Testnet
JSON-RPC Endpoint: https://json-rpc.evm.testnet.shimmer.network/
Websocket JSON-RPC Endpoint: wss://ws.json-rpc.evm.testnet.shimmer.network/
Explorer URL: https://explorer.evm.testnet.shimmer.network/
Chain ID: 1071
Token name: SMR
--snip

This is the last thing I'm keeping metamask installed for (I manually disable rabby and enable metamask specifically to engage with their testnet) and of course reverse that process when I'm done. 

I want to uninstall metamask.. you guys are my only hope. 

thx

**Comment by vvvvvv1vvvvvv** [comment]
You can add custom testnet in Rabby now, so the issue will be closed
