### ISSUE TITLE
Search input field for current address change

### ISSUE THREAD

**Issue by gasperbr** [RabbyHub/Rabby#1393]
Having an option to search for an address by the label or its bytes would be very helpful for those who have a lot of stored addresses.

**Comment by 36EbtvQ8** [comment]
this please! the only thing missing for me to jump over from Metamask, its a must for users with many addresses

**Comment by DmitriyKurto** [comment]
I'm also waiting for this feature

**Comment by ethan1141** [comment]
I'll be very helpful to have it

**Comment by vvvvvv1vvvvvv** [comment]
v0.92.3 supported
