### ISSUE TITLE
Balance not updated

### ISSUE THREAD

**Issue by sixgodfan** [RabbyHub/Rabby#1398]
I have imported more than a thousand addresses and in version 0.86 when I click on update balance, but the balance is not updated, the balance is only updated when I click on that address for that address

![VyHV8E.png](https://i.328888.xyz/2023/05/20/VyHV8E.png)

**Comment by vvvvvv1vvvvvv** [comment]
You can't update all address balance since api rate limit, you can switch them one by one for update for instead
