### ISSUE TITLE
issue signing transactions with qr based hardware wallet - Keystone

### ISSUE THREAD

**Issue by 5863358894** [RabbyHub/Rabby#1401]
When logging on to Rabby it works flawlessly every time to sign transactions (on BSC and ETH chain) with Keystone, QR based, hardware wallet. However, when the computer goes to sleep or  I don't  use Rabby for a while, there seem to be an issue with getting the camera on Macbook Pro M1 / Chrome (Version 113.0.5672.126 (Official Build) (arm64)). I scan the QR code from the Keystone wallet displayed within the Rabby wallet, but then when Rabby will read the response QR code from the Keystone wallet it does not activate the camera. It shows a blank screen where the camera view should appear. It doesn't help clearing cache. Only solution is to log out from Rabby, clear cache, force refresh the website, log back on to Rabby and then start over with the signing process. A restart of the computer also solves the issue.

**Comment by vvvvvv1vvvvvv** [comment]
Does the issue still can reproduce?
