### ISSUE TITLE
[testnet request] Sepolia testnet

### ISSUE THREAD

**Issue by radeksvarz** [RabbyHub/Rabby#1416]
related to #1274 and #1369 
However if chain enlisting is considered on one by one bases, Sepolia is the now long term L1 testnet.

**Comment by bolandco** [comment]
Following 👀

**Comment by justkevindefi** [comment]
+1 need this ASAP.

**Comment by radeksvarz** [comment]
c'mon, current situation:

![image](https://github.com/RabbyHub/Rabby/assets/6020891/63cd0725-a688-4cf3-88d7-6f45a5925a9f)

vs ethereum.org suggestion:

> Sepolia is the recommended default testnet for application development.

https://ethereum.org/en/developers/docs/networks/#sepolia

**Comment by vvvvvv1vvvvvv** [comment]
supported

**Comment by radeksvarz** [comment]
yes, also Arbitrum Sepolia is supported. Neat.  thanks devs!
