### ISSUE TITLE
[chainlist request] Localhost RPC for dev, testing and demonstrations

### ISSUE THREAD

**Issue by radeksvarz** [RabbyHub/Rabby#1417]
Rabby Wallet lacks a localhost:8545 RPC option in its chainlist, hindering local development using tools like Anvil, Truffle, and Hardhat. This omission prevents devs from seamlessly connecting to their locally hosted blockchain networks for testing and debugging purposes.

This is related to #1274 , but can be designed differently UI/UX wise (think Android developer mode)

**Comment by radeksvarz** [comment]
Custom RPC is possible to be set.

However only for mainnets (not testnets) and thus requiring corresponding chain ID of the mainnet:

![image](https://github.com/RabbyHub/Rabby/assets/6020891/118d0961-c428-41f6-9a53-8372808b45f7)


This seam to work at first when starting anvil with `anvil --chain-id 1`

![image](https://github.com/RabbyHub/Rabby/assets/6020891/8ae6a12b-f621-429d-b8be-20d959c763ce)


However the balance on the accounts is not reflected.

![image](https://github.com/RabbyHub/Rabby/assets/6020891/a3660308-f3af-44c4-8553-99d9704dfcb1)

vs

![image](https://github.com/RabbyHub/Rabby/assets/6020891/fb27c4f8-257d-4bac-a61e-c01b48b36de1)

**Comment by stevyhacker** [comment]
I second this, it would be much easier to test contract development locally with Foundry/Anvil and Rabby rather than switching to Metamask only because of this feature. Please add custom rpc and chain.

**Comment by quangkeu95** [comment]
bumping this, really need Rabby to supports custom RPC to connect to the local Anvil node

**Comment by hdadr** [comment]
The team is deaf to hearing us to add custom rpc / chains.

**Comment by vvvvvv1vvvvvv** [comment]
You can add custom testnet in Rabby now, so the issue will be closed

**Comment by radeksvarz** [comment]
@vvvvvv1vvvvvv Thanks!

I can confirm it works.

![image](https://github.com/RabbyHub/Rabby/assets/6020891/4be31dcd-5160-4799-bcec-46feaeb7f7a1)
