### ISSUE TITLE
Rabby timing out too quickly when trying to communicate with Bitbox02

### ISSUE THREAD

**Issue by neoKushan** [RabbyHub/Rabby#1422]
I'm raising a new issue as it's been deemed unrelated to  #1403

Essentially, any time Rabby tries to communicate with the Bitbox02, it times out very quickly. 

The pairing code appears very briefly - it's like maybe half a second but I managed to get it to connect by tapping the wallet quickly enough. Now it's connected and works to an extent, but I see the same behaviour when trying to sign a transaction - It prompts for like half a second, then disappears while Rabby displays an error similar to the above:

![image](https://github.com/RabbyHub/Rabby/assets/1029699/447746db-b99a-40ab-9b10-6dfaae8bb792)

This applies to connecting an address, signing a transaction or even just unlocking the Bitbox02, the pass screen appears for a split second, then Rabby displays an error. I have added a video to show the behaviour:

https://github.com/RabbyHub/Rabby/assets/1029699/026394ad-7a5b-4c63-8383-af3ff01a7566

This happens across all Dapps, regardless of whether or not the Bitbox app itself is open or not. Other bitbox02 compatible apps like MyEtherWallet work correctly. 

 I pulled this log from chrome but it doesn't seem to show anything useful:
[acmacodkjbdgmoleebolmdjonilkdbch-1685010638690.log](https://github.com/RabbyHub/Rabby/files/11582681/acmacodkjbdgmoleebolmdjonilkdbch-1685010638690.log)

I am happy to give whatever other information could be helpful.

**Comment by belg1o** [comment]
Also having these issues

Will add my logs below

`DevTools failed to load source map: Could not load content for chrome-extension://acmacodkjbdgmoleebolmdjonilkdbch/webextension-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://acmacodkjbdgmoleebolmdjonilkdbch/background.js.map: System error: net::ERR_FILE_NOT_FOUND
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
background.js:2 Fetch finished loading: POST "https://o460488.ingest.sentry.io/api/5831390/envelope/?sentry_key=e871ee64a51b4e8c91ea5fa50b67be6b&sentry_version=7".
(anonymous) @ background.js:2
e @ background.js:2
a._sendRequest @ background.js:2
a.sendSession @ background.js:2
e.sendSession @ background.js:2
e._sendSession @ background.js:2
e.captureSession @ background.js:2
e._sendSessionUpdate @ background.js:2
e.captureSession @ background.js:2
(anonymous) @ background.js:2
A @ background.js:2
(anonymous) @ background.js:2
await in (anonymous) (async)
__webpack_require__.a @ background.js:2
51065 @ background.js:2
__webpack_require__ @ background.js:2
(anonymous) @ background.js:2
__webpack_require__.O @ background.js:2
(anonymous) @ background.js:2
(anonymous) @ background.js:2
background.js:2 XHR failed loading: GET "https://festats.debank.com/rabby/byteInUse?value=175499".
(anonymous) @ background.js:2
(anonymous) @ background.js:2
request @ background.js:2
report @ background.js:2
(anonymous) @ background.js:2
Promise.then (async)
(anonymous) @ background.js:2
await in (anonymous) (async)
__webpack_require__.a @ background.js:2
51065 @ background.js:2
__webpack_require__ @ background.js:2
(anonymous) @ background.js:2
__webpack_require__.O @ background.js:2
(anonymous) @ background.js:2
(anonymous) @ background.js:2
background.js:2     GET https://festats.debank.com/rabby/byteInUse?value=175499 404
(anonymous) @ background.js:2
(anonymous) @ background.js:2
request @ background.js:2
report @ background.js:2
(anonymous) @ background.js:2
Promise.then (async)
(anonymous) @ background.js:2
await in (anonymous) (async)
__webpack_require__.a @ background.js:2
51065 @ background.js:2
__webpack_require__ @ background.js:2
(anonymous) @ background.js:2
__webpack_require__.O @ background.js:2
(anonymous) @ background.js:2
(anonymous) @ background.js:2
background.js:2 XHR finished loading: POST "https://rpc.mevblocker.io/".
(anonymous) @ background.js:2
(anonymous) @ background.js:2
(anonymous) @ background.js:2
e.exports @ background.js:2
e.exports @ background.js:2
s.request @ background.js:2
(anonymous) @ background.js:2
(anonymous) @ background.js:2
request @ background.js:2
ping @ background.js:2
(anonymous) @ background.js:2
onRequest @ background.js:2
(anonymous) @ background.js:2
XHR finished loading: GET "<URL>".
XHR finished loading: GET "<URL>".
XHR finished loading: GET "<URL>".
XHR finished loading: GET "<URL>".
XHR finished loading: GET "<URL>".
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
DevTools failed to load source map: Could not load content for chrome-extension://acmacodkjbdgmoleebolmdjonilkdbch/webextension-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://acmacodkjbdgmoleebolmdjonilkdbch/content-script.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://rabbyhub.github.io/eth-ledger-bridge-keyring/pageProvider.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
bundle.js:316 Rabby < = > Ledger Bridge initialized from https://rabbyhub.github.io/eth-ledger-bridge-keyring/!
background.js:2 2023/05/31 22:54:15 fire event: statusChanged
background.js:2 2023/05/31 22:54:15 Device status: connected
background.js:2 2023/05/31 22:54:15 Device status: connected
background.js:2 2023/05/31 22:54:15 Device status: connected
background.js:2 2023/05/31 22:54:15 Device status: connected
background.js:2 2023/05/31 22:54:15 Device status: connected
background.js:2 2023/05/31 22:54:15 OP_INFO: version=9.14.0, product=bitbox02-multi
background.js:2 2023/05/31 22:54:16 attestation check result: true
background.js:2 2023/05/31 22:54:16 fire event: attestationCheckDone
background.js:2 true
background.js:2 {ErrorType: 'generic', Code: 0, Message: 'unexpected NACK response'}
(anonymous) @ background.js:2
withDevice @ background.js:2
await in withDevice (async)
__getPage @ background.js:2
getFirstPage @ background.js:2
H.requestKeyring @ background.js:2
(anonymous) @ background.js:2
onRequest @ background.js:2
(anonymous) @ background.js:2
webextension-polyfill.js:1 Uncaught (in promise) {message: 'Could not establish connection. Receiving end does not exist.'}message: "Could not establish connection. Receiving end does not exist."[[Prototype]]: Objectconstructor: ƒ ()arguments: nullcaller: nulllength: 0name: ""prototype: {constructor: ƒ}constructor: ƒ ()[[Prototype]]: Object[[Prototype]]: ƒ ()apply: ƒ apply()arguments: (...)bind: ƒ bind()call: ƒ call()caller: (...)constructor: ƒ Function()length: 0name: ""toString: ƒ ()Symbol(Symbol.hasInstance): ƒ [Symbol.hasInstance]()get arguments: ƒ ()set arguments: ƒ ()get caller: ƒ ()set caller: ƒ ()[[FunctionLocation]]: [[Prototype]]: Object[[Scopes]]: Scopes[0]No properties[[Scopes]]: Scopes[0][[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()length: 2name: "__defineGetter__"arguments: (...)caller: (...)[[Prototype]]: ƒ ()apply: ƒ apply()arguments: (...)bind: ƒ bind()call: ƒ call()caller: (...)constructor: ƒ Function()length: 0name: ""toString: ƒ ()Symbol(Symbol.hasInstance): ƒ [Symbol.hasInstance]()get arguments: ƒ ()set arguments: ƒ ()get caller: ƒ ()set caller: ƒ ()[[FunctionLocation]]: [[Prototype]]: Object[[Scopes]]: Scopes[0][[Scopes]]: Scopes[0]No properties__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()length: 1name: "__lookupGetter__"arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]__lookupSetter__: ƒ __lookupSetter__()length: 1name: "__lookupSetter__"arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]__proto__: (...)get __proto__: ƒ __proto__()length: 0name: "get __proto__"arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]set __proto__: ƒ __proto__()length: 1name: "set __proto__"arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]
u @ webextension-polyfill.js:1
background.js:2 Fetch finished loading: POST "https://o460488.ingest.sentry.io/api/5831390/envelope/?sentry_key=e871ee64a51b4e8c91ea5fa50b67be6b&sentry_version=7".
(anonymous) @ background.js:2
e @ background.js:2
a._sendRequest @ background.js:2
a.sendSession @ background.js:2
e.sendSession @ background.js:2
e._sendSession @ background.js:2
e.captureSession @ background.js:2
e._updateSessionFromEvent @ background.js:2
(anonymous) @ background.js:2
onfulfilled @ background.js:2
(anonymous) @ background.js:2
_executeHandlers @ background.js:2
_attachHandler @ background.js:2
(anonymous) @ background.js:2
e @ background.js:2
e.then @ background.js:2
e._processEvent @ background.js:2
e._captureEvent @ background.js:2
e.captureEvent @ background.js:2
e._invokeClient @ background.js:2
e.captureEvent @ background.js:2
callback @ background.js:2
p @ background.js:2
s.onunhandledrejection @ background.js:2
background.js:2 Fetch finished loading: POST "https://o460488.ingest.sentry.io/api/5831390/store/?sentry_key=e871ee64a51b4e8c91ea5fa50b67be6b&sentry_version=7".
(anonymous) @ background.js:2
e @ background.js:2
a._sendRequest @ background.js:2
a.sendEvent @ background.js:2
e.sendEvent @ background.js:2
e._sendEvent @ background.js:2
a._sendEvent @ background.js:2
(anonymous) @ background.js:2
onfulfilled @ background.js:2
(anonymous) @ background.js:2
_executeHandlers @ background.js:2
_attachHandler @ background.js:2
(anonymous) @ background.js:2
e @ background.js:2
e.then @ background.js:2
e._processEvent @ background.js:2
e._captureEvent @ background.js:2
e.captureEvent @ background.js:2
e._invokeClient @ background.js:2
e.captureEvent @ background.js:2
callback @ background.js:2
p @ background.js:2
s.onunhandledrejection @ background.js:2
`

**Comment by belg1o** [comment]
Pinging @vvvvvv1vvvvvv

**Comment by benma** [comment]
In the BitBox TG chat we discovered:

- It works on other machines, and even in a Win10 VM running inside the Win11 where it does not work
- Chrome&Mew works, which does not need a BitBoxBridge
- FireFox&Mew does not work, which needs a BitBoxBridge

Unexpected NACK with the symptoms described indicates that the communication from Rabby to the Bridge, or from the Bridge to the BitBox02, is somehow slowed down. It seems to be a rare issue. My assumption is that there is something on your Windows installations that slows down either TCP/HTTP (Rabby <-> Bridge communication) or USB (Bridge <-> BitBox02 communication), but it is hard to figure out what that might be.

Another avenue to try is to re-architect the BitBox02 integration in Rabby to be able to use WebUSB, but that does not seem trivial - seems it needs some sort of inter process communication as the WebUSB part is not allowed where the BitBox02 integration code runs, so that would be a bigger effort. That would also only work on Chrome, not Firefox.

**Comment by neoKushan** [comment]
It's a good theory about the slowed communication. Is there some way we can prove that out, maybe a debug build of the Bridge that logs timestamps of communications?

**Comment by benma** [comment]
https://github.com/digitalbitbox/bitbox-bridge/releases/tag/v1.5.1 fixed the problem for @neoKushan and @belg1o. Thanks @neoKushan for figuring out that the latest commit in the bridge repo actually worked while the official release (a few commits behind) did not.

**Comment by neoKushan** [comment]
Yup , this is officially resolved with the 1.5.1 release of the Bitbox bridge.

**Comment by sortoel** [comment]
Fix seems to be for Windows/macOS but same issue appears on Linux + Brave

**Comment by benma** [comment]
@sortoel macOS was not affected by this bug. I uploaded the same 1.5.1 version that helped for Windows also for Linux, please try it out and let me know if that helps:

https://github.com/digitalbitbox/bitbox-bridge/releases/tag/v1.5.1

**Comment by benma** [comment]
@sortoel did it work?

**Comment by sortoel** [comment]
@benma The only thing that works for me now is if I unlock the Bitbox02 using MEW. What used to work (opening Bitbox app, unlocking and then closing it) doesn't seem to work anymore as Rabby doesn't even recognize Bitbox this way.
