### ISSUE TITLE
EIP-55 - address checksum standard (2016) 

### ISSUE THREAD

**Issue by merisation** [RabbyHub/Rabby#1428]
All hexadecimal characters [A-F] in Ethereum addresses should not be lowercase, EIP-55 (2016) added a checksum to all addresses so they normally have upper and lowercase characters. Please fix.

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md

**Comment by aspiers** [comment]
This is super important for guarding against errors in addresses.  Currently it's too easy for a single digit error in an address to result in lost funds.  So it would be great if you could prioritize this.  Thanks!
