### ISSUE TITLE
When importing hardware wallet addresses, back button goes forward

### ISSUE THREAD

**Issue by timjrobinson** [RabbyHub/Rabby#1475]
While I was importing addresses from my Gridplus I accidentally clicked the go forward button to go to the 2nd page, I then clicked the back button to go back to the first page of addresses. Instead of going to the 1st page it listed addresses 11 -> 15, the ones from the third page. But the little number in between the `<` `>` buttons said `1`

**Comment by vvvvvv1vvvvvv** [comment]
fixed in the latest version
