### ISSUE TITLE
[BUG] stETH (lido) doesnt show up when trying to send it in wallet.

### ISSUE THREAD

**Issue by hdadr** [RabbyHub/Rabby#1491]
![image](https://github.com/RabbyHub/Rabby/assets/22738075/55b27879-eb73-4777-8cc6-0c1a0b2eadf4)

- send
- select token
- stETH
Does not show up, has to paste the contract address to be able to find the token. 
This is a serious problem as people might accidentally paste the contract address to the receiving address and send the tokens there losing it.

**Comment by vvvvvv1vvvvvv** [comment]
do you have steth balance in your wallet?

**Comment by hdadr** [comment]
> do you have steth balance in your wallet?

Yes

**Comment by vvvvvv1vvvvvv** [comment]
Reproduced, you can search 0xae7ab96520de3a18e5e111b5eaab095312d7fe84 as workaround currently
will let you know for any update of fix

**Comment by hdadr** [comment]
> 

It seems that i still have the problem v0.92.12

**Comment by vvvvvv1vvvvvv** [comment]
<img width="397" alt="image" src="https://github.com/RabbyHub/Rabby/assets/86296331/130d5a45-92fb-453d-a3ea-6947590cfb33">

We currently consider steth as a type of ETH staked portfolio, so you can find it in DeFi but not tokens, it's expected.
The workaround is add steth to customized token manually like below 

<img width="414" alt="image" src="https://github.com/RabbyHub/Rabby/assets/86296331/a97b878e-0ce3-4931-b19e-266b911ff3ca">

**Comment by hdadr** [comment]
still have the same issue, i have to paste the stETH address everytime i wanna send it. Newest version of rabby

**Comment by vvvvvv1vvvvvv** [comment]
No, you can simple search "steth" now instead of paste address
<img width="414" alt="image" src="https://github.com/RabbyHub/Rabby/assets/86296331/86cb9471-02cd-4e7e-96b4-ce2b8d523a52">

**Comment by hdadr** [comment]
Idk what happens on my end, because it did not show up

**Comment by vvvvvv1vvvvvv** [comment]
any screenshot?

**Comment by hdadr** [comment]
> any screenshot?

i just came back to make some screenshot and now it works and finds it.
