### ISSUE TITLE
Walletconnect needs to be upgraded to v2

### ISSUE THREAD

**Issue by Zarigis** [RabbyHub/Rabby#1493]
Walletconnect v1 has been shut down as of June 28th (see: https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/overview) but all of the walletconnect options in rabby are still using v1 and are therefore non-functional.

**Comment by vvvvvv1vvvvvv** [comment]
https://twitter.com/Rabby_io/status/1667151344564576257
TLDR: Rabby use self-host WalletConnect v1 relay to make sure v1 still works

**Comment by Zarigis** [comment]
Some apps are incompatible with v1 though. For example the Ledger app for android throws an error when attempting to connect to rabby via walletconnect, saying the app is out of date.
