### ISSUE TITLE
Cannot create wallet if seed has duplicate words

### ISSUE THREAD

**Issue by t4t5** [RabbyHub/Rabby#150]
My seed generated by Rabby contained the word "physical" twice, one after the other.

When trying to verify the seed phrase, it doesn't work, since it will only append the word **once** to the top container and then **not let you choose the same one from the list again**:

https://user-images.githubusercontent.com/2598660/127284515-c48294b1-c224-486b-b0ce-61a364d06d9c.mov

**Comment by vvvvvv1vvvvvv** [comment]
fixed in https://github.com/RabbyHub/Rabby/commit/e8d6c2b4429d54bbc3c3f0eafc03bdb66282bf78，you can try v0.7.1 in Release Tab of Github
