### ISSUE TITLE
Option to hide your balance

### ISSUE THREAD

**Issue by Th0rgal** [RabbyHub/Rabby#1523]
Hello,

It is just a suggestion. It would be nice to be able to hide your balances when you click on the amount like on ledger live, especially when you need to do a quick tx in a public place.

Thanks,
Thomas

**Comment by vvvvvv1vvvvvv** [comment]
Supported on the latest version

**Comment by benface** [comment]
Could we have that feature on Rabby Desktop too? 🙏
