### ISSUE TITLE
[BUG] Rabby cannot process deposit/withdrawal transactions into this complex Balancer Pool on Polygon zkEVM

### ISSUE THREAD

**Issue by timjrobinson** [RabbyHub/Rabby#1526]
There is a Balancer pool on Polygon zkEVM - https://app.balancer.fi/#/zkevm/pool/0x6f34a44fce1506352a171232163e7716dd073ade000200000000000000000015 - that for some reason Rabby wallet can't deposit into or withdraw from. It works correctly in Metamask, and the transaction data is the same for both. 

Here is an example withdraw transaction done via Metamask that didn't work when attempting to do it via Rabby: https://zkevm.polygonscan.com/tx/0xcb690da074c767343f32606b8237cce31ec3a1ee0dd1ff52da632a22fa43d59d

I'm a developer at Balancer if you'd like further help debugging this.

**Comment by vvvvvv1vvvvvv** [comment]
Looks like we recommend a low gasPrice cause transaction can't submit

**Comment by timjrobinson** [comment]
It's not gas price, happens at multiple times from multiple users with Rabby wallets. There's something in this transaction that Rabby wallet is unable to parse correctly, as it reports the transaction cannot be completed. You should try yourself depositing / withdrawing into that pool with Rabby and you'll see it.

**Comment by vvvvvv1vvvvvv** [comment]
should be fixed now, can you check again?
