### ISSUE TITLE
Add custom token

### ISSUE THREAD

**Issue by vuquangbinh** [RabbyHub/Rabby#1538]
Please add the function of adding new tokens according to the contract address.

Thanks!

**Comment by vvvvvv1vvvvvv** [comment]
<img width="404" alt="image" src="https://github.com/RabbyHub/Rabby/assets/86296331/3b2dcc3c-54e8-4f80-8d37-c2f059bf0800">

<img width="404" alt="image" src="https://github.com/RabbyHub/Rabby/assets/86296331/d0dba1ae-5f11-46cd-a2cc-c7f9811de605">

You can simply add custom token by search contract address
