### ISSUE TITLE
MDEX cannot connect to Rabby

### ISSUE THREAD

**Issue by mahuanhuan** [RabbyHub/Rabby#157]
MDEX cannot connect to Rabby

![image](https://user-images.githubusercontent.com/15261282/127470611-5deb21de-61de-4406-9fe7-9252d0256478.png)

**Comment by vvvvvv1vvvvvv** [comment]
Can you try to restart your browser(kill the Chrome, then reopen it), mostly fixed in https://github.com/RabbyHub/Rabby/pull/152
