### ISSUE TITLE
`wallet.openapi.getToken` returns inaccurate balance

### ISSUE THREAD

**Issue by oxSaturn** [RabbyHub/Rabby#1575]
I kept running into an approval issue when using rabby wallet (didn't try MetaMask yet), and I believe it's due to the rabby api returning inaccurate balance.

Below is my wftm balance on fantom queried from ftmscan:

![CleanShot-Ql1p9bQ4@2x](https://github.com/RabbyHub/Rabby/assets/126733611/0832af2a-a433-46f2-a1a4-e6fb16d91a43)

And below is the data queried from rabby api:

![CleanShot-p5SLvgu2@2x](https://github.com/RabbyHub/Rabby/assets/126733611/c051bc1e-fd84-420f-8bc7-7fa820a86d5b)

<img width="377" alt="CleanShot-UVUARNal@2x" src="https://github.com/RabbyHub/Rabby/assets/126733611/980be8eb-a7c3-4828-bace-fea366bce589">

And here's the balance when visiting debank:

<img width="388" alt="CleanShot-7KPTCWe4@2x" src="https://github.com/RabbyHub/Rabby/assets/126733611/cddee0c0-f2bf-44b4-8abb-44534a987fca">

As you can see, the balance from rabby api is smaller than my actual balance.

Say I want to add liquidity to a dex, and I'd like to deposit all my wftm, i.e., `240014887325196554938`, but rabby would only allow me approve `240014887325196550000` if I click my balance:

![CleanShot-tBqzKrtu@2x](https://github.com/RabbyHub/Rabby/assets/126733611/e98adb4b-6ff7-49f4-a914-793d092d95c4)

Thus the dex wouldn't allow me to deposit `240014887325196554938` as I have approved an allowance that's less than my balance.

**Comment by vvvvvv1vvvvvv** [comment]
closed by #1562
