### ISSUE TITLE
(Chain Request) for Rabby Wallet to integrate HorizenEON (EVM)

### ISSUE THREAD

**Issue by DeFiMoney-Printer** [RabbyHub/Rabby#1579]
Network name
Horizen EON
Network URL
https://eon-rpc.horizenlabs.io/ethv1
Chain ID
7332
Currency symbol
ZEN
Block explorer URL
https://eon-explorer.horizenlabs.io

EON Landing Page
https://eon.horizen.io/

Horizen Landing Page:
https://www.horizen.io/

Horizen Foundation Github: 
https://github.com/HorizenOfficial

HorizenEON (EVM), the premier sidechain solution on Horizen's Zendoo has been soft-launched to mainnet and gradually bringing on partners and builders after a successful 3 phase testnet development phase which ended with Gobi Testnet surpassing 1million transactions.

Please integrate HorizenEON to Rabby Wallet as a chain that can be selected by default.

**Comment by vvvvvv1vvvvvv** [comment]
supported in the latest version
