### ISSUE TITLE
Rabby always injects isRabby = true into window.ethereum object

### ISSUE THREAD

**Issue by sherrbss** [RabbyHub/Rabby#1582]
Noticing that Rabby will always inject a value of `true` for the `isRabby` property on the window.ethereum object, regardless of whether the `MetaMask is in use and Rabby is banned` state is active. If this state is active, should the isRabby property be set to false/undefined? If not, is it possible that another property is added to identify that MetaMask should be preferred over Rabby?

Related commentary: https://github.com/wagmi-dev/wagmi/issues/2708

**Comment by vvvvvv1vvvvvv** [comment]
<img width="1671" alt="image" src="https://github.com/RabbyHub/Rabby/assets/86296331/a9d4c9bd-734e-414f-b766-818510d50e41">
it works fine in my side, Rabby will not inject isRabby if MetaMask is in use and Rabby is banned, check if you have any other extension wallet will cause the conflict
