### ISSUE TITLE
Ability to toggle advanced gas control to edit gas directly.

### ISSUE THREAD

**Issue by belg1o** [RabbyHub/Rabby#160]
The ability to put change gas directly off the interface instead of having to go into the gas menu settings would be a QoL implementation going forward. 

An example of this would be 
![image](https://user-images.githubusercontent.com/11260048/127653082-4b26bacf-b1e3-49fe-b5a5-1465fea310a3.png)
Where 15 would be the custom number entered for that transaction.

Below is how Metamask implement it. 
![chrome_iype0znCgB](https://user-images.githubusercontent.com/11260048/127653466-caa88c25-a445-48af-a646-412cbcd1d9ce.png)

**Comment by vvvvvv1vvvvvv** [comment]
Try click the icon right side, you can customize it in "Custom" 
![image](https://user-images.githubusercontent.com/86296331/127731624-034bb9f6-cb9a-43f9-8149-80f1f39b7f09.png)

**Comment by belg1o** [comment]
> Try click the icon right side, you can customize it in "Custom"
> ![image](https://user-images.githubusercontent.com/86296331/127731624-034bb9f6-cb9a-43f9-8149-80f1f39b7f09.png)

I know this is available, it would be nice if you could skip this step of having to go in the menus and have the ability to customize right off the interface instead.

**Comment by vvvvvv1vvvvvv** [comment]
will discuss with UI Team

**Comment by vvvvvv1vvvvvv** [comment]
![image](https://user-images.githubusercontent.com/86296331/145958949-134b48eb-7563-40c4-9dd0-92a4915edc5f.png)

Here you go, check our new gas panel UI
