### ISSUE TITLE
Unknown address after hardward wallet switching

### ISSUE THREAD

**Issue by oxSaturn** [RabbyHub/Rabby#1710]
I just keeps running into this error after switching hardware wallet, believe there's no such problem in the old version.

<img width="359" alt="CleanShot-3X06KOwd@2x" src="https://github.com/RabbyHub/Rabby/assets/126733611/d1d0cf73-416b-452c-add2-6d11967735a1">

**Comment by oxSaturn** [comment]
Here's how I had to work around the problem:

1. Select `Connect hardware wallets`
2. select `trezor`
3. refresh the page

**Comment by vvvvvv1vvvvvv** [comment]
This 2 address in different Trezor devices right?

**Comment by oxSaturn** [comment]
> This 2 address in different Trezor devices right?

Right.

**Comment by vvvvvv1vvvvvv** [comment]
Do you have a stable way to reproduce this issue?
I can't reproduce it in my side

**Comment by oxSaturn** [comment]
> Do you have a stable way to reproduce this issue? I can't reproduce it in my side

Hi, just tried, can't reproduce any more.

But I think it's still reproducible yesterday, and another thing I noticed yesterday was, if I switch the hardware and wait a while before interacting, there won't be any problem.

So maybe let's close it, i can reopen just in case it happens again.
