### ISSUE TITLE
Extend accounts beyond 50

### ISSUE THREAD

**Issue by gardnertechhq** [RabbyHub/Rabby#1716]
Hello, I am trying to extend number of accounts in wallet beyond 50 but it seems like it's impossible. 
Can I somehow to this? Is it limited because of some performance consideration?

**Comment by vvvvvv1vvvvvv** [comment]
<img width="1705" alt="image" src="https://github.com/RabbyHub/Rabby/assets/86296331/2e0d90ca-2c50-497a-a3bc-052a793d79af">

Click "Advanced Settings", input the start number you want(like you want see index 50-99, then input 50)
