### ISSUE TITLE
Error: User rejected the request when open devtool in popup

### ISSUE THREAD

**Issue by codetool03** [RabbyHub/Rabby#1720]
I connect to a web3 certain website, it shows a popup to enter a password or connect, I right-click and select inspect, then the devtool popup pops up but both are closed.

**Comment by vvvvvv1vvvvvv** [comment]
it's expected, popup will auto close when focusChange triggered
https://github.com/RabbyHub/Rabby/blob/develop/src/background/service/notification.ts#L97
