### ISSUE TITLE
Fiat On and Off Ramp Integration

### ISSUE THREAD

**Issue by DFXAdmin** [RabbyHub/Rabby#1725]
Hello together

I don't know if I'm right here with this theme, if not I want to apologize, I didn't find any other way to ask this question.

We have integrated Rabby Wallet in our services and recommend Rabby Wallet to our customers to interact with EVM Blockchains. We are big fans of Rabby Wallet especially because it is developed under an MIT license. We have developed and released all our services under MIT license as well because we love OpenSource.

To my question, is there an option to integrate our European Fiat On and Off Ramp into Rabby Wallet? We have built an excellent service for this and have many happy customers. 

We are regulated in Switzerland and offer our On and Off Ramp to all people in Europe.

**Comment by vvvvvv1vvvvvv** [comment]
No plan currently
