### ISSUE TITLE
Support Crossbell Chain

### ISSUE THREAD

**Issue by Songkeys** [RabbyHub/Rabby#1730]
Please support this chain.

- Website: https://crossbell.io/
- Scan: https://scan.crossbell.io/
- Info: https://chainlist.org/?search=crossbell
- In `viem/chains`: https://github.com/wagmi-dev/viem/blob/main/src/chains/definitions/crossbell.ts

P.S. I was trying to make a PR but found the `@debank/common` pkg is not open sourced.

**Comment by vvvvvv1vvvvvv** [comment]
Rabby supports custom networks now, it means you can use Rabby with any EVM network, this issue will be closed
