### ISSUE TITLE
Ape.tax not accessible

### ISSUE THREAD

**Issue by belg1o** [RabbyHub/Rabby#176]
When you try to access the https://ape.tax/ site, the experimental pools for funding won't load. 
![image](https://user-images.githubusercontent.com/11260048/128486563-fe3b7247-a9bb-4478-94f6-c110e75749e2.png)

This is what it's supposed to look like (using Metamask to load and connect) 

![chrome_RCuoAAdRvZ](https://user-images.githubusercontent.com/11260048/128483968-e56602fe-3674-4952-a232-0ebe60747bc8.png)

**Comment by vvvvvv1vvvvvv** [comment]
Looks like since `eth_subscribe` is not supported for now

**Comment by vvvvvv1vvvvvv** [comment]
Just checkout the code of this dapp, looks like https://github.com/fameal/ape-tax/blob/master/src/App.vue#L73 has a infinite call, will check this..

**Comment by vvvvvv1vvvvvv** [comment]
looks like works fine with ape.tax now, will close this issue
