### ISSUE TITLE
Unable to send mint Tx on Wasabix on BSC

### ISSUE THREAD

**Issue by kur0** [RabbyHub/Rabby#178]
URL https://bsc.wasabix.finance/#/app/minters/busd/wabusd/alpaca
When trying mint waBUSD, the tx will get failed on website's js after Signing the TX on rabby

**Comment by vvvvvv1vvvvvv** [comment]
Can you share more information like error message or anything else?

**Comment by kur0** [comment]
re-tried later and I am able to send through this time. 
Closing issue. Thanks for the attention
