### ISSUE TITLE
Enable EIP-1559 and gas price optimisations for Optimism and Base chains

### ISSUE THREAD

**Issue by acryptosx** [RabbyHub/Rabby#1785]
Enable EIP-1559 as it is supported for both these chains now.
Also, allow manual setting of lower priority gas price for these chains (and all others).
For Base chain, lowest priority gas price is currently 100 wei (0.0000001 gwei). For Ethereum mainnet it is lower than 0.001 as well. There is no way to set these via the UI at the moment.

**Comment by kewlfft** [comment]
In general, we need a clearer and more flexible support of EIP-1559. For example, in case of manual setting and repeat transaction, Rabby switches back into legacy gas mode.

**Comment by vvvvvv1vvvvvv** [comment]
enabled
