### ISSUE TITLE
Gaslimit in wagmi is not working for rabby

### ISSUE THREAD

**Issue by script-money** [RabbyHub/Rabby#1790]
I use wagmi. My use case requires a higher gas limit setting, which was not a problem before. Recently, it seems that there have been issues with the update.

## in rabby, gas limit is estimated

<img width="420" alt="Screenshot 2023-10-01 at 21 19 40" src="https://github.com/RabbyHub/Rabby/assets/74860630/c1adb028-73a0-485e-bb08-918d34c44760">

## in metamask, gas limit is correct

<img width="412" alt="Screenshot 2023-10-01 at 21 18 56" src="https://github.com/RabbyHub/Rabby/assets/74860630/c5b168df-bfba-41ae-8b45-32f7ccab300e">

## code

```tsx
  const {
    data: loot10WithCaptainData,
    write: loot10WithCaptainWrite,
    error: loot10WithCaptainError,
    isLoading: isLoot10WithCaptainWaitSending,
    reset: loot10WithCaptainReset,
  } = useContractWrite({
    address: poolAddr,
    abi: [
      {
        inputs: [
          {
            internalType: "uint16",
            name: "captainId_",
            type: "uint16",
          },
          {
            internalType: "uint256",
            name: "nftId_",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "usdc_",
            type: "bool",
          },
        ],
        name: "loot10",
        outputs: [],
        stateMutability: "payable",
        type: "function",
      },
    ] as const,
    functionName: "loot10",
    args: [roleId, BigInt(nftId ?? 0), isPayUSDC],
    value: BigInt(loot10PriceSendValue),
    gas: 2325000n,
    chainId: env.NEXT_PUBLIC_CHAIN_ID,
    onError: (error) => {
      console.warn(`loot10WithCaptain ${error.message}`);
    },
    onSettled: () => {
      console.log(`loot10WithCaptain address ${poolAddr}`);
      console.log(`loot10WithCaptain use ${isPayUSDC ? "USDC" : "MATIC"}`);
    },
  });
  ```

**Comment by vvvvvv1vvvvvv** [comment]
Rabby will re-estimate gas cost and set a gasLimit, why you need to set a higher gasLimit?

**Comment by script-money** [comment]
> Rabby will re-estimate gas cost and set a gasLimit, why you need to set a higher gasLimit?

As this is a lottery game, the gas consumption varies depending on the number of different items drawn.

**Comment by vvvvvv1vvvvvv** [comment]
Currently, Rabby will use `max(gasLimit from Dapp, estimated gasLimit)` for final gasLimit, so your issue should be resolved
