### ISSUE TITLE
Adding Custom RPC

### ISSUE THREAD

**Issue by JozefJarosciak** [RabbyHub/Rabby#1795]
Rabby is not allowing me to add a custom RPC for a new blockchain that is being developed: XENBLOCKS.
XenBlocks has roughly 15 thousand users, and the majority of them are forced to switch from Rabby to Metamask now, because the following can be easily added to Metamask, but not into Rabby:

Network name: XENBLOCKS
New RPC URL: https://xenblocks.io:5556
Chain ID: 100101
Currency symbol: XNM

Metamask image:
![image](https://github.com/RabbyHub/Rabby/assets/3492464/9dbe8bc0-ac5b-4cbf-9ab9-489720768e6f)

Folks, the ability to add truly custom RPC is absolutely essential for developers.

**Comment by Commoneffort** [comment]
Please, integrate custom RPC

**Comment by dirrrtyjesus** [comment]
lets go rabby blyat.. open sauce support open sauce!!

**Comment by vvvvvv1vvvvvv** [comment]
You can add custom testnet in Rabby now, so the issue will be closed
