### ISSUE TITLE
Request for Adding Support for EIP-6963 - Multi Injected Provider Discovery

### ISSUE THREAD

**Issue by KarthikS373** [RabbyHub/Rabby#1809]
## Issue
Rabby Wallet currently lacks support for EIP-6963, which introduces the Multi Injected Provider Discovery mechanism. This Ethereum Improvement Proposal (EIP) enhances the interoperability and user experience for users who have multiple browser extensions or wallets

## Proposed Solution
The proposed solution involves integrating EIP-6963 support into Rabby Wallet. This integration should follow the EIP-6963 specification, ensuring that Rabby Wallet can discover and interact with multiple Wallet Providers in a web page using JavaScript's window events

Related: 
[EIP-6963](https://eips.ethereum.org/EIPS/eip-6963)

**Comment by vvvvvv1vvvvvv** [comment]
supported in the latest version
