### ISSUE TITLE
Clicking on more opens a scam link

### ISSUE THREAD

**Issue by Th0rgal** [RabbyHub/Rabby#1826]
Hello,

I noticed a very weird behavior on my wallet today, I don't know if I have a malware on my end or if it is an issue within Rabby. When I click on the "More" button it opens a phishing link.

Here is a recording:
https://youtu.be/Pr7Kzkf8i2Q

**Comment by vvvvvv1vvvvvv** [comment]
Because you connected to a phishing site which flagged by Google.
<img width="651" alt="image" src="https://github.com/RabbyHub/Rabby/assets/86296331/adb2add4-0b63-417a-b0eb-be36f4aa19be">
Click "visit this unsafe site" to access and disconnect the website to fix it
