### ISSUE TITLE
Inconsistent Transaction Preview on Arc

### ISSUE THREAD

**Issue by mergd** [RabbyHub/Rabby#1836]
Love the extension but Rabby tx previews on the Arc browser are really inconsistent.

Sometimes the show tx modal will show and about half of the time it won't show up – below is a screen recording of what this looks like when it doesn't work – nothing shows up.

![CleanShot 2023-10-27 at 21 59 16](https://github.com/RabbyHub/Rabby/assets/24722014/e1dc4c3f-77fe-4aa1-b9c8-ee4965c771c5)

Running latest version of Arc (1.14.0, which is chrome v118) and on latest version of MacOS

**Comment by vvvvvv1vvvvvv** [comment]
We cannot guarantee the stability on Arc browser, please try to use chrome
but anyway, will take a look when free

**Comment by vvvvvv1vvvvvv** [comment]
Can you still reproduce this issue?
It looks fine in my side with Arc 1.17.2

**Comment by vvvvvv1vvvvvv** [comment]
will close since no response and can't reproduce the issue
