### ISSUE TITLE
Invalid RPC Response 

### ISSUE THREAD

**Issue by belg1o** [RabbyHub/Rabby#185]
Using the build from v0.9.0 from the build. On https://opensea.io/ I'm getting this error now. 

![chrome_FF4VUB68O4](https://user-images.githubusercontent.com/11260048/128854252-c3c0ff89-4061-4c9c-96f9-fb5edb9f5afa.png)

Error in Chrome logs. 
![chrome_qOCJ7EgfJy](https://user-images.githubusercontent.com/11260048/128854698-f70bf0b9-25ae-4718-ac3e-daeaa8f25bf3.png)

**Comment by vvvvvv1vvvvvv** [comment]
can not reproduce in https://opensea.io/assets/0xa7d8d9ef8d8ce8992df33d8b8cf4aebabd5bd270/127000687, can you share me your operations and which step this error appeared?

**Comment by belg1o** [comment]
> can not reproduce in https://opensea.io/assets/0xa7d8d9ef8d8ce8992df33d8b8cf4aebabd5bd270/127000687, can you share me your operations and which step this error appeared?

https://youtu.be/JIsjiR0yxT4 here's a video of me capturing the process. It just appears when the site tries to push the transaction to Rabby. 

1. Go to the item 
2. Press Buy Now
3. Confirm
4. RPC ERROR

**Comment by vvvvvv1vvvvvv** [comment]
Can you try if the package attached fix this issue(built by the latest commit of master)?

### How to install

1. enable the Developer mode on right top of chrome://extensions/
2. disable your previous Rabby
3. unzip the file
4. click Load unpacked
5. choose  the folder which unziped in 2
6. import your address(for security consideration, you can use Watch Mode instead input private key in this package)
7. try sign transaction(you can not really sign this transaction, but if you the popup appeared, it means this issue should be fixed)

![image](https://user-images.githubusercontent.com/86296331/129047309-7a63c9ce-3ebb-4d35-b853-c419f9ad71f9.png)

NOTE: You should only install Rabby from Chrome Store or GitHub Release of Rabby repo or a package attached by **ME**, **NEVER** input your private key or mnemonic words in the package which **ANYONE ELSE** sent you


[Rabby_issue_185.zip](https://github.com/RabbyHub/Rabby/files/6969131/Rabby_issue_185.zip)

**Comment by belg1o** [comment]
> Can you try if the package attached fix this issue(built by the latest commit of master)?
> 
> ### How to install
> 1. enable the Developer mode on right top of chrome://extensions/
> 2. disable your previous Rabby
> 3. unzip the file
> 4. click Load unpacked
> 5. choose  the folder which unziped in 2
> 6. import your address(for security consideration, you can use Watch Mode instead input private key in this package)
> 7. try sign transaction(you can not really sign this transaction, but if you the popup appeared, it means this issue should be fixed)
> 
> ![image](https://user-images.githubusercontent.com/86296331/129047309-7a63c9ce-3ebb-4d35-b853-c419f9ad71f9.png)
> 
> NOTE: You should only install Rabby from Chrome Store or GitHub Release of Rabby repo or a package attached by **ME**, **NEVER** input your private key or mnemonic words in the package which **ANYONE ELSE** sent you
> 
> [Rabby_issue_185.zip](https://github.com/RabbyHub/Rabby/files/6969131/Rabby_issue_185.zip)

Hey @vvvvvv1vvvvvv , that one does seem to prompt Rabby's interface to come up. So it does look like that did the trick. 

That said the interface now feels like there's a lot of latency on it. Compared to when I use Metamask the process is more than 50% slower to bring up the confirmation interface. Also it seems to say that it fails pre-execution now, before this did not be a problem.

**Comment by vvvvvv1vvvvvv** [comment]
possibility got the point, thanks for report, for other 2 questions:

1. Rabby is slower than MetaMask: when you sign a transaction in Rabby, we will do security check and pre-excute to show you what the transaction is, how many tokens you will lose and how many tokens you will get as well as if the contract is safe which MataMask don't have, so that's why Rabby is slower, we need time to get those information.
2. fails pre-execution: many reasons can cause this result, mostly when you retry sign transaction it should be well, don't worry if still not, you still can sign this transaction if you make sure it's a correct transaction

possibility it's better to create another issue for these questions

**Comment by vvvvvv1vvvvvv** [comment]
fixed in v0.10.0
