### ISSUE TITLE
Error 500 - Mumbai network - HTLC provision

### ISSUE THREAD

**Issue by redDwarf03** [RabbyHub/Rabby#1864]
Hello

i use Rabby wallet to sign transactions in a bridge process.
Context: 
EVM chain: Mumbai
Process:
1) create a HTLC on Mumbai with a signed transaction
2) provision the HTLC with token

The 1) works with Rabby but we meet Error 500 with the 2)
For information, 
- the process works with Sepolia 
- the process works with mumbai and metamask

Here a document with an example
[Bridge 2W - scenario en erreur (Rabby).pdf](https://github.com/RabbyHub/Rabby/files/13356978/Bridge.2W.-.scenario.en.erreur.Rabby.pdf)

Raw of the tx to create HTLC
```
{
    "chainId": 80001,
    "from": "0x5ba1d8dc7e0bac18d7dd7664aab59998fc6d3229",
    "to": "0xe55915d112711127339f073e75185e6311dd72c8",
    "value": "0x0",
    "data": "0x2064295e11de948d5f575b7331fc0731eb6b7d082d95ef5d5f465a0e6e25a9a96bfcf1e3000000000000000000000000000000000000000000000000002386f26fc10000",
    "gas": "0x160211",
    "maxFeePerGas": "0xa64c0580",
    "maxPriorityFeePerGas": "0xa64c0580",
    "nonce": "0x89"
}
```

HTLC: https://mumbai.polygonscan.com/address/0xf9b4585c3582444889225d0e51ae7a7cea2262d9

How to get logs from error 500 please ?

Thx

**Comment by vvvvvv1vvvvvv** [comment]
should be fixed now

**Comment by redDwarf03** [comment]
Could you give me some infos about the issue please?
