### ISSUE TITLE
Unable to transfer wrapped tokens

### ISSUE THREAD

**Issue by 0xJem** [RabbyHub/Rabby#1873]
There are a number of ERC20-compatible tokens that are "wrapped" and which can be transferred, but the Rabby desktop interface does not support it (or it is not immediately visible). e.g. gOHM, wstETH

It would be great to add support for this!

**Comment by vvvvvv1vvvvvv** [comment]
We currently think LSD token as portfolio(not token), you need to add it as custom token if you want to transfer it like token
