### ISSUE TITLE
Report a problem with Japanese display (wrong code points)

### ISSUE THREAD

**Issue by kaie3** [RabbyHub/Rabby#1877]
# Summary
Specifically, the font used in the application does not adequately support the Japanese character set, resulting in the display of Chinese characters instead. 
This creates a discrepancy between the expected appearance of Japanese text and the actual display within the app.

# Additional Information
For reference and insight into similar issues, please consider [Your Code Displays Japanese Wrong](https://heistak.github.io/your-code-displays-japanese-wrong/). 
This resource discusses common problems and possible solutions related to displaying Japanese text.

**Comment by vvvvvv1vvvvvv** [comment]
Can you show me an example?
Not Japanese speaker so not sure what I need to fix

**Comment by kaie3** [comment]
Here is an example of approval.
Will this get the point across?
![Examples of Approval](https://github.com/RabbyHub/Rabby/assets/44547717/e417df60-4ad4-4600-8f4f-b55ab5d9c862)

**Comment by Nakochi-crypto** [comment]
This is not caused by code points, but font-family. I'll fix it and send a pull request.

**Comment by kaie3** [comment]
Thank you for responding to the correction!
I look forward to seeing this reflected in the product version!
