### ISSUE TITLE
Please add support for DefiChain

### ISSUE THREAD

**Issue by sandrich** [RabbyHub/Rabby#1884]
Network Name:
DefiChain

New RPC URL:
https://eth.mainnet.ocean.jellyfishsdk.com/

Chain ID:
1130

Currency Symbol:
DFI

Block Explorer:
https://meta.defiscan.live/

Confirmation of launch:
Defichain has been around for a few years https://defichain.com/ but the MetaChain (EVM) is running since a week.

**Comment by vvvvvv1vvvvvv** [comment]
Rabby supports custom networks now, it means you can use Rabby with any EVM network, this issue will be closed
