### ISSUE TITLE
Local development error

### ISSUE THREAD

**Issue by poundbang** [RabbyHub/Rabby#1890]
Hello,

With  building `yarn build:dev` with `node v20.5.1` and loading extension I get the following: 

<img width="647" alt="image" src="https://github.com/RabbyHub/Rabby/assets/23733597/7d3503ee-15a5-4df2-9a1a-dffc3c0f91d8">

Is there a step I am missing? 

Thanks.

**Comment by vvvvvv1vvvvvv** [comment]
<img width="209" alt="image" src="https://github.com/RabbyHub/Rabby/assets/86296331/95236f8e-298c-4db0-a90a-a936ce3dde86">
Try refresh background and check if it works or not.
You can ignore the error if your extension works fine

**Comment by poundbang** [comment]
Thanks.
