### ISSUE TITLE
Default Floor gwei for some chain (e.g. BSC)

### ISSUE THREAD

**Issue by kur0** [RabbyHub/Rabby#190]
I found the auto selected gwei for BSC sometimes is off and used 1 gwei instead of 5gwei (recommended by BSC?)
If I hit confirm then I would have a stuck tx until I check back.
Is there way to adjust the floor gwei for some of the chains?

**Comment by vvvvvv1vvvvvv** [comment]
Rabby will respect the gasPrice set by dapp, if dapp set gasPrice in tx, we just follow it, and if not, we will get the recommended gasPrice of current chain, so looks like the dapp set gasPrice to 1 gwei

**Comment by kur0** [comment]
In that case, I've came across an example that Rabby had  a very low suggested gwei.
Metamask is working fine at the same time.
https://app.beefy.finance/#/
Rabby
![image](https://user-images.githubusercontent.com/1430075/132079144-b8124d36-c79a-44b2-8420-369f0f7834c8.png)


metamask
![image](https://user-images.githubusercontent.com/1430075/132079158-a3dfce70-0c14-4666-988b-d8e8644ab1fb.png)

**Comment by vvvvvv1vvvvvv** [comment]
> In that case, I've came across an example that Rabby had a very low suggested gwei.
> Metamask is working fine at the same time.
> https://app.beefy.finance/#/
> Rabby
> ![image](https://user-images.githubusercontent.com/1430075/132079144-b8124d36-c79a-44b2-8420-369f0f7834c8.png)
> 
> metamask
> ![image](https://user-images.githubusercontent.com/1430075/132079158-a3dfce70-0c14-4666-988b-d8e8644ab1fb.png)

Here is a difference between Rabby and MetaMask, Rabby will always use the gasPrice sent by dapp. In this case, this 1 gwei is set by beefy, but MetaMask probability found its too low, so they use the suggestion gasPrice, Rabby dont have this logic, we only suggestion gasPrice when dapp not set.

Anyway, will discuss with team about this

**Comment by vvvvvv1vvvvvv** [comment]
in v0.17.0 release, if you set gas once time, next time will use the previous selection by default, just try it
