### ISSUE TITLE
CYG token is being marked as scam on Arbitrum

### ISSUE THREAD

**Issue by swan-of-bodom** [RabbyHub/Rabby#1905]
I see that Rabby has added nice support to Cygnus protocol on Polygon, but not on Arbitrum. The token is currently being marked as a scam, anything we can do on our end? 

The protocol is currently deployed on Arbitrum and Polygon and verified on both block explorers with logo and name, etc. 

Polygon: 0xc553a5A789f1BB56a72847b3FDA1DE3E16e6763f

Arbitrum: 0x05eaea39f69b24f8f2da13af2d8ee0853889f2a8

Thanks

**Comment by vvvvvv1vvvvvv** [comment]
fixed
