### ISSUE TITLE
add the option to select the Ledger Live HD path when connecting a Trezor wallet?

### ISSUE THREAD

**Issue by 8001800** [RabbyHub/Rabby#1906]
add the option to select the Ledger Live HD path when connecting a Trezor wallet?

When connecting Trezor, there is no option to select the Ledger Live HD path. 

Consequently, there is no way to access Ledger Live HD path-derived addresses on a Trezor wallet that uses the same passphrases. 

Could you please add the option to select the Ledger Live HD path when connecting a Trezor wallet ?

![Screenshot 2023-12-04 22 06 45](https://github.com/RabbyHub/Rabby/assets/5697645/621d8882-1a3a-4fe3-b355-63c1acdcb8d2)

**Comment by vvvvvv1vvvvvv** [comment]
@heisenberg-2077 Can you check this?

**Comment by vvvvvv1vvvvvv** [comment]
supported in the latest version
