### ISSUE TITLE
Supply chain security: fragility to malware, remove dependency ranges

### ISSUE THREAD

**Issue by paulmillr** [RabbyHub/Rabby#1921]
Rabby is fragile to malware.

When any dependency is updated, you'll receive its update. If the update contains malware, you'll automatically consume it and wouldn't even know.

Two steps for mitigation:

1. Stop using version ranges (`^1.2.0` => `1.2.0`)
2. Do version updates rarely: once per quarter, of rarer, and check every update manually

**Comment by vvvvvv1vvvvvv** [comment]
https://github.com/RabbyHub/Rabby/blob/develop/yarn.lock
We use lock file to lock the version
And sure, we didn't update dependencies if not necessary
Core dependencies we will just follow MetaMask step to update or change (stupid but useful)

**Comment by paulmillr** [comment]
See commit history of the lockfile: https://github.com/RabbyHub/Rabby/commits/develop/yarn.lock

This commit introduced a bunch of new dependencies and dependencies of dependencies. Have you reviewed them? No! https://github.com/RabbyHub/Rabby/commit/0151eccbb8455f8c1aea402ae8a4953c6193613d

This commit changed 525 lines in the lockfile https://github.com/RabbyHub/Rabby/commit/85e7e41cc4a4ddbcdda3ccafbd7095a797d83053.

It's easy to get malware into rabby. Lockfiles help, but not fully.

What would help:

1. Lock down versions
2. Do **rare updates**, try to review every update instead of clicking on "dependabot merge" button
3. Lavamoat

**Comment by vvvvvv1vvvvvv** [comment]
1. Lock down versions has been done in #1940
2. Will only do rare updates in future
3. LavaMoat integration will track in #1891 , will keep focus on development of LavaMoat for webpack
