### ISSUE TITLE
Add Ledger Live / Legacy derivative paths for Trezor HW

### ISSUE THREAD

**Issue by poseidonPLS** [RabbyHub/Rabby#1924]
Add Ledger Live / Legacy derivative paths for Trezor HW. 

For users migrating from Ledger to Trezor HW wallet, additional derivative paths will be helpful. Aurox wallet have that function. Adding it to Rabby wallet will be fantastic.

**Comment by Zarigis** [comment]
Bump please, also duplicated in #1906

**Comment by akaSurreal** [comment]
yes please, ran into the same issue, BIP44 path only shows the first address from Ledger Live

**Comment by vvvvvv1vvvvvv** [comment]
supported in the latest version
