### ISSUE TITLE
Security Question: Update Process for Desktop (.dmg)

### ISSUE THREAD

**Issue by 59023g** [RabbyHub/Rabby#1925]
Hi - The app looks and function great. Thank you.

What's the update process for desktop app? Is it automatic? Is there a way to disable if it is automatic?

I ask after the Ledger incident yesterday, where malicious code was added to a popular library, then distributed. 

Thank you

**Comment by vvvvvv1vvvvvv** [comment]
> What's the update process for desktop app
1. Find the update
2. Download the update
3. Verify the software signature of the downloaded package(.dmg)
4. If the package is signed by our certificate, then you can install the pacakge

> Is it automatic?
No, we only help you to find the update, you need to download and install it by your click, there is no automatic function in Rabby Desktop

For RabbyDesktop discussion, please move to https://github.com/RabbyHub/RabbyDesktop 
Will close this issue
