### ISSUE TITLE
New Network Request: Dexalot

### ISSUE THREAD

**Issue by iJaack** [RabbyHub/Rabby#1927]
Network Name:
Dexalot

New RPC URL:
https://subnets.avax.network/dexalot/mainnet/rpc

Chain ID:
432204

Currency Symbol:
ALOT

Block Explorer:
https://avascan.info OR https://snowtrace.io

Website for reference:
https://dexalot.com

**Comment by veyselozkahraman** [comment]
Chain id is not correct for the dexalot subnet

**Comment by veyselozkahraman** [comment]
Please refer to this link `https://chainlist.org/chain/432204`

**Comment by iJaack** [comment]
@veyselozkahraman thank you, corrected

**Comment by vvvvvv1vvvvvv** [comment]
supported in the latest version

**Comment by vvvvvv1vvvvvv** [comment]
wait sorry, only testnet supported, mainnet is on the way

**Comment by vvvvvv1vvvvvv** [comment]
mainnet support in the latest version
