### ISSUE TITLE
Please add support for LightLink network

### ISSUE THREAD

**Issue by danatpellar** [RabbyHub/Rabby#1931]
Network Name:
LightLink

New RPC URL:
https://replicator.phoenix.lightlink.io/rpc/v1

Chain ID:
1890

Currency Symbol:
ETH

Block Explorer:
https://phoenix.lightlink.io

Website for reference:
https://lightlink.io/

**Comment by vvvvvv1vvvvvv** [comment]
Rabby supports custom networks now, it means you can use Rabby with any EVM network, this issue will be closed
