### ISSUE TITLE
Dexalot Subnet network support

### ISSUE THREAD

**Issue by veyselozkahraman** [RabbyHub/Rabby#1934]
Network Name:
Dexalot Subnet

New RPC URL:
https://subnets.avax.network/dexalot/mainnet/rpc

Chain ID:
432204

Currency Symbol:
ALOT

Block Explorer:
https://432204.snowtrace.io

Website for reference:
https://app.dexalot.com/trade
https://chainlist.org/chain/432204

**Comment by vvvvvv1vvvvvv** [comment]
duplicate with #1927
