### ISSUE TITLE
Tidal Finance dapp unable to connect

### ISSUE THREAD

**Issue by kur0** [RabbyHub/Rabby#195]
Hello,

Wallect unable to connect to dapp for TIdal Finance on Matic. Clicked on switch to Matic but nothing shows up even I manually open Rabby and switch the chain to matic/polygon. Works normally with metamask.

https://app.tidal.finance/index.html

![image](https://user-images.githubusercontent.com/1430075/130540280-0dd65c7e-a4f5-42cb-81af-278b501e2b93.png)

**Comment by vvvvvv1vvvvvv** [comment]
fixed in #197

**Comment by vvvvvv1vvvvvv** [comment]
fixed in 0.12.0
