### ISSUE TITLE
[Chain Request] Shardeum Testnet

### ISSUE THREAD

**Issue by dreamchasing13** [RabbyHub/Rabby#1955]
Please add support for the Shardeum testnet.

Network Name: Shardeum Sphinx
New RPC URL: https://sphinx.shardeum.org/
Chain ID: 8082
Currency symbol (optional): SHM
Block Explorer URL (optional): https://explorer-sphinx.shardeum.org/

**Comment by dreamchasing13** [comment]
Hi @vvvvvv1vvvvvv, Shardeum is launching its incentivized testnet the last week of Feb or the first week of March. We'd love to promote Rabby Wallet as part of the incentivized campaign. Can you please add support for Shardeum's testnet to Rabby? Thank you!

**Comment by vvvvvv1vvvvvv** [comment]
You can add custom testnet in Rabby now, so the issue will be closed
