### ISSUE TITLE
[Testnet Request] Cronos zkEVM Testnet

### ISSUE THREAD

**Issue by zolla0x** [RabbyHub/Rabby#1966]
**Name:** Cronos zkEVM Testnet
**RPC URL:** https://rpc-zkevm-t0.cronos.org
**Chain ID:** 282
**Symbol:** TCRO
**Block explorer URL:** https://zkevm-t0.cronos.org/explorer/

_More official info about Cronos zkEVM Testnet:_
_https://docs.cronos.org/cronos-zkevm-chain/introduction-to-cronos-zkevm-chain-testnet_

**Comment by vvvvvv1vvvvvv** [comment]
You can add custom testnet in Rabby now, so the issue will be closed
