### ISSUE TITLE
Moonbeam and Moonriver Always Type 0 Legacy Txns 

### ISSUE THREAD

**Issue by themacexpert** [RabbyHub/Rabby#1967]
Moonbeam and Moonriver transactions submitted thru Rabby Wallet default to Legacy Type 0 transaction types when they should be Type 2 (EIP-1559). This is curious to me because both Moonbeam and Moonriver are marked as EIP-1559: true in chain-data.js. 

Here is an example of a txn with Rabby that defaults to Legacy Txn type: https://moonbeam.moonscan.io/tx/0x5804fd176dfb4b23c1957b10a48061f1fd8d8585de0eddb0a99c348cf69be392

Let me know if there is anything I can help with regarding this. Thanks! 

<img width="1125" alt="Screenshot 2024-01-08 at 1 55 32 PM" src="https://github.com/RabbyHub/Rabby/assets/5834262/7ec4d69a-6760-4a0b-b219-0450db00a996">

**Comment by vvvvvv1vvvvvv** [comment]
You need to manual set maxPriorityFee to use 1559 transaction currently, we don't support auto-set maxPriorityFee on this 2 chains

**Comment by maggo** [comment]
Having the same issue on Scroll Sepolia (custom network). Even if `maxPriorityFee` and `maxPriorityFeePerGas` are explicitly set it will fall back to legacy
