### ISSUE TITLE
Support Kaspa

### ISSUE THREAD

**Issue by simonjoyner** [RabbyHub/Rabby#1968]
https://kaspa.org/about-kaspa/

**Comment by PierreGuerand** [comment]
+1

**Comment by vvvvvv1vvvvvv** [comment]
Rabby supports custom networks now, it means you can use Rabby with any EVM network, this issue will be closed

**Comment by simonjoyner** [comment]
KASPA isn't an EVM chain. Please reoopen.

**Comment by vvvvvv1vvvvvv** [comment]
We don't have plan to support non-EVM chains
