### ISSUE TITLE
Own Extension connection issue with Dapp

### ISSUE THREAD

**Issue by blockchain-app12** [RabbyHub/Rabby#1972]
We are developing a new extension for our own use cases. We have completed the separate wallet functionalities similar to MetaMask and developed our own DApp application. However, we are encountering issues while trying to connect the wallet with the DApp, akin to the functionality provided by the ethereum.enable() function in the MetaMask extension. We are facing challenges in establishing a connection between the extension and the DApp. 

 As we need the exact functions or procedures required for custom wallet connection with the Dapp. We have a separate custom RPC based on the besu network that's get imported in the wallet. By using that wallet, connect with the Dapp to execute the transactions. we stuck at this process.
 
 If you have suggestions, please let me know to complete it.

**Comment by vvvvvv1vvvvvv** [comment]
Can't understand what's your problem

**Comment by blockchain-app12** [comment]
We developed a own customized extension similar to Metamask and Rabby. The wallet side is working properly.But we need support for Dapp to extension connectivity similar to like connect wallet and other functionalities.

**Comment by vvvvvv1vvvvvv** [comment]
both Rabby and Metamask are open-sourced, you check check the code to find why :)
