### ISSUE TITLE
Add X1 Testnet

### ISSUE THREAD

**Issue by JozefJarosciak** [RabbyHub/Rabby#1978]
Rabby is not allowing me to add a custom RPC for the Testnet of the new X1 blockchain.

Network name: X1 Testnet
New RPC URL: https://x1-testnet.xen.network/
Chain ID: 204005
Currency symbol: XN
Block explorer URL: https://explorer.x1-testnet.xen.network/

How to do this?
And why can't we add custom networks?

**Comment by vvvvvv1vvvvvv** [comment]
You can add custom testnet in Rabby now, so the issue will be closed
