### ISSUE TITLE
Custom Derivation Paths

### ISSUE THREAD

**Issue by 0xbid** [RabbyHub/Rabby#1984]
Right now, you can only select from a range of certain Derivation Paths. For instance, on Ledger, you can only select from the first 1000 Paths.

I would like to use an account from outside of this range. Increasing the range, by 10000, would work, but I think an even better solution would be to just type in the Derivation Path you work manually, without loading in N many accounts.

**Comment by vvvvvv1vvvvvv** [comment]
@QingWei-Li pls check if we can remove the max derivation count for HD wallets

**Comment by codaxiom** [comment]
I need this too.
The 1000 limit is hardcoded in https://github.com/RabbyHub/Rabby/blob/0d33fe6bf68ab98568b87a2beb9ad92062a267b2/src/ui/views/HDManager/AdvancedSettings.tsx
`
const MAX_START_NO = 950 + MIN_START_NO;`

**Comment by 0xbid** [comment]
Thanks so much for the update @heisenberg-2077! Do you happen to know what the release schedule for Rabby is / when users can use this?

**Comment by codaxiom** [comment]
> Thanks so much for the update @heisenberg-2077! Do you happen to know what the release schedule for Rabby is / when users can use this?

It's released now :)
![image](https://github.com/RabbyHub/Rabby/assets/25625522/1da2eebd-85db-42de-a52f-fd128c504549)
