### ISSUE TITLE
New Network Request: OctaSpace

### ISSUE THREAD

**Issue by x9q** [RabbyHub/Rabby#1987]
Hello,

Please add OctaSpace network.

RPC URL: https://rpc.octa.space

Chain ID: 800001

Currency Symbol: OCTA

Block Explorer:
 * https://scan.octa.space
 * https://explorer.octa.space
 
 Website: https://octa.space
 
 ChainList: https://chainlist.org/chain/800001
 
 Thank you

**Comment by x9q** [comment]
Hello @vvvvvv1vvvvvv 

Any chance to add OCTA ?

Thanks

**Comment by vvvvvv1vvvvvv** [comment]
Rabby supports custom networks now, it means you can use Rabby with any EVM network, this issue will be closed
