### ISSUE TITLE
Gas settings

### ISSUE THREAD

**Issue by belg1o** [RabbyHub/Rabby#200]
Hey, I've been having issues with some gas settings

*Gas limit custom set - looks like the custom gas limits I set never get sent through properly. This could be a critical bug, I've ran out of gas today because of it - Rabby showed it set the correct gas, but when the tx was sent to the mempool it did not apply the gas limit specified.

*Can't change gas when network is overloaded - need a way to always be able to customize this, I've had this screen for multiple minutes while the network is clogged up. 
![chrome_NMyx09styS](https://user-images.githubusercontent.com/11260048/131193290-bd4a970f-5c5a-40fa-9960-68743defdbee.png)

*Unable to set custom gas below suggested price, this should not be something that Rabby prevents in the first case - just accept the users input instead of checking it against the system. Would be nice if we could set it in the first screen like suggested in #160

**Comment by vvvvvv1vvvvvv** [comment]
1. Gas limit custom set, sorry for this bug, will fix asap
2. Can't change gas when network is overloaded, it's hard to fix this because after you change the gas, Rabby will re-explain your transaction(use network to send explain request), so even though you can confirm the gas setting, you will stay in explain loading for a long time when the network is clogged up
3. Unable to set custom gas below suggested price, actually because the [EIP-1559](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md), if your gasPrice is lower than the base fee, this transaction should never be completed, so we prevent user input a lower than base fee amount

**Comment by belg1o** [comment]
> 1. Gas limit custom set, sorry for this bug, fixed in [fix: can not customize gasLimit if dapp not set #201](https://github.com/RabbyHub/Rabby/pull/201)
> 2. Can't change gas when network is overloaded, it's hard to fix this because after you change the gas, Rabby will re-explain your transaction(use network to send explain request), so even though you can confirm the gas setting, you will stay in explain loading for a long time when the network is clogged up
> 3. Unable to set custom gas below suggested price, actually because the [EIP-1559](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md), if your gasPrice is lower than the base fee, this transaction should never be completed, so we prevent user input a lower than base fee amount

1. Thanks for the fix.
2. So is there any way we could get #160 added so we can manually override gas settings, would also fix nr. 3. 
3. What if we want to queue lower gas for later. For example, gas is @ 100 in the evening but I want to submit txs with 40 gwei for when I'm asleep that'll complete overnight by the time I wake up.

**Comment by belg1o** [comment]
@vvvvvv1vvvvvv Really need an implementation and fix because today I can't even change them at all, even when they load.
![image](https://user-images.githubusercontent.com/11260048/131734137-2d18b890-5af9-4a85-8de5-dd083a3aa8cd.png)

**Comment by vvvvvv1vvvvvv** [comment]
@belg1o can you expand the Advanced Options? looks like dapp set a invalid gasLimit, and can you tell me the url of this dapp?

**Comment by belg1o** [comment]
> @belg1o can you expand the Advanced Options? looks like dapp set a invalid gasLimit, and can you tell me the url of this dapp?

Sorry, will try remeber for next time. Don't remember what I was doing exacly, just knew it was quite urgent and had to switch to Metamask to get it done.

**Comment by vvvvvv1vvvvvv** [comment]
> > @belg1o can you expand the Advanced Options? looks like dapp set a invalid gasLimit, and can you tell me the url of this dapp?
> 
> Sorry, will try remeber for next time. Don't remember what I was doing exacly, just knew it was quite urgent and had to switch to Metamask to get it done.

sure, we will discuss about it

**Comment by vvvvvv1vvvvvv** [comment]
btw, 0.12 has been released, and Gas limit custom set has been fixed in this version

**Comment by vvvvvv1vvvvvv** [comment]
since bug has been fixed, I will close this issue, for question 2, track in #160 and for can't confirm gas setting, track in #214
