### ISSUE TITLE
WalletConnect ProjectID hardcoded in plain text

### ISSUE THREAD

**Issue by michaelessiet** [RabbyHub/Rabby#2002]
I noticed that your walletconnect projectid is stored in plain text. I recommend removing and possibly changing it so that people can't just copy it and use it within their own applications. This could also be a security risk as people could use it to impersonate Rabby and have users download fake mobile wallet applications and claim that it is the official Rabby app since it shows up in the walletconnect modal
<img width="497" alt="Screenshot 2024-01-21 at 00 11 11" src="https://github.com/RabbyHub/Rabby/assets/23281128/fb85f038-a90a-4303-803c-db6ca269e89f">

**Comment by vvvvvv1vvvvvv** [comment]
It's OK to move it to other sides like env variables but I don't think this will cause some security risk since you can still find it in the network request panel with plain text, we can't prevent bad people find it
