### ISSUE TITLE
Add support for HAQQ Network

### ISSUE THREAD

**Issue by olegshilov** [RabbyHub/Rabby#2004]
Hello Rabby Wallet Team,

I am writing to request the inclusion of a new blockchain network in the Rabby Wallet. The network I am referring to is the Haqq Network, which can be found here: https://haqq.network

The Haqq Network is an innovative and emerging blockchain that has been gaining traction due to its unique features and capabilities. It is listed on [Chainlist](https://chainlist.org/?search=haqq&testnets=true), which showcases its growing relevance in the blockchain community. 

Adding Haqq Network to Rabby Wallet would not only provide existing users with more versatility but also attract new users who are looking for a wallet that supports this network. The integration could potentially open up new avenues for decentralized applications and smart contract interactions for Rabby Wallet users.

Thank you for considering this request. I look forward to the possibility of seeing Haqq Network integrated into Rabby Wallet.

UPD:
explorer can be found here: https://explorer.haqq.network

**Comment by vvvvvv1vvvvvv** [comment]
Rabby supports custom networks now, it means you can use Rabby with any EVM network, this issue will be closed
