### ISSUE TITLE
New Network Request: Mode

### ISSUE THREAD

**Issue by iJaack** [RabbyHub/Rabby#2036]
## Mainnet
Network Name: Mode
RPC URL: https://mainnet.mode.network
ChainID: 34443
Currency: ETH
Block explorer URL: https://modescan.io

## Testnet

Network Name: Mode Sepolia
RPC URL: https://sepolia.mode.network
ChainID: 919
Currency: ETH
Block explorer URL: https://testnet.modescan.io

Reference website: https://mode.network

**Comment by vvvvvv1vvvvvv** [comment]
resolved in #2060
