### ISSUE TITLE
New network request: Immutable zkEVM

### ISSUE THREAD

**Issue by mc-ducky** [RabbyHub/Rabby#2037]
### Mainnet

Network Name: Immutable zkEVM 
RPC URL: https://rpc.immutable.com/
ChainID: `13371`
Currency: IMX
Block explorer URL: https://explorer.immutable.com/

### Testnet

Network Name: Immutable zkEVM Testnet
RPC URL: https://rpc.testnet.immutable.com/
ChainID: `13473`
Currency: IMX
Block explorer URL: https://explorer.testnet.immutable.com/

Reference website: https://immutable.com/

**Comment by vvvvvv1vvvvvv** [comment]
Rabby supports custom networks now, it means you can use Rabby with any EVM network, this issue will be closed
