### ISSUE TITLE
[Testnet Chain Request] Add Support for zkSync Sepolia Testnet

### ISSUE THREAD

**Issue by serejke** [RabbyHub/Rabby#2040]
### Overview
zkSync Quickstart [tutorial](https://docs.zksync.io/build/quick-start/hello-world.html) assumes working with zkSync Sepolia Testnet, which Rabby wallet does not currently support.

Chainlist entry: https://chainlist.org/?search=zksync&testnets=true
RPC: https://sepolia.era.zksync.dev
Chain ID: 300
Symbol: ETH
Explorer: https://sepolia.explorer.zksync.io/

**Comment by vvvvvv1vvvvvv** [comment]
Rabby supports custom networks now, it means you can use Rabby with any EVM network, this issue will be closed
