### ISSUE TITLE
Adding APK to Releases 

### ISSUE THREAD

**Issue by baizon** [RabbyHub/Rabby#2042]
Greeting, 

You provide a [Google Mobile App](https://play.google.com/store/apps/details?id=com.debank.rabbymobile). Could You also provide the APK file within the Github Release. I'm using a custom Android with no Google Services but would like to use the App. 

Thank you in advance.

**Comment by vvvvvv1vvvvvv** [comment]
added

**Comment by grigio** [comment]
I dont see the apk in the latest releases
