### ISSUE TITLE
console error: TypeError: Cannot redefine property: ethereum

### ISSUE THREAD

**Issue by mirumirumi** [RabbyHub/Rabby#2046]
When I open the Developer Tools with the Rubby Wallet installed, an error appears in the console.
It's annoying to me as a developer because it shows up no matter what URL I am at.
I'm not aware of any detailed conditions for reproduction. I have installed and deposited several tokens, including ETH.

version: 0.92.51

```
TypeError: Cannot redefine property: ethereum
    at Function.defineProperty (<anonymous>)
    at <anonymous>:1:63747
    at z (<anonymous>:1:63937)
    at <anonymous>:1:64382
    at <anonymous>:1:68887
    at <anonymous>:1:68891
    at <anonymous>:2:3
```

<img src="https://github.com/RabbyHub/Rabby/assets/88871226/081f16a5-4434-4d91-be16-5b117a59597f"  width="75%"/>

Click content-script.js to open the Rabby Wallet source code.

**Comment by vvvvvv1vvvvvv** [comment]
Since you installed multi ethereum wallets, it's OK in most cases and you can disable other wallets to resolve the issue
