### ISSUE TITLE
Add Support for XDC Network

### ISSUE THREAD

**Issue by MohitXDC** [RabbyHub/Rabby#2069]
Mainnet
Network Name: XDC Network
RPC URL: https://rpc.xdc.org/
ChainID: 50
Currency: XDC
Block explorer URL: https://xdc.blocksscan.io

Testnet
Network Name: Apothem Testnet
RPC URL: https://erpc.apothem.network/
ChainID: 51
Currency: tXDC
Block explorer URL: https://apothem.blocksscan.io/

Reference website: https://xinfin.org, https://xdc.org

**Comment by vvvvvv1vvvvvv** [comment]
Rabby supports custom networks now, it means you can use Rabby with any EVM network, this issue will be closed

**Comment by MohitXDC** [comment]
Hello RabbyHub/Rabby

I understand that one can add any EVM network as a custom Network but
native integrations bring a far better user experience to the community.
Let us know if you can support XDC Network natively and what kind of
support would you require from us to make that possible.

Regards

Mohit Dhiman

Community Moderator  |  XDC Foundation

Note new email: ***@***.***

www.xdc.org
