### ISSUE TITLE
New Network Request: Endurance

### ISSUE THREAD

**Issue by lyfsn** [RabbyHub/Rabby#2073]
Endurance is a decentralized network built by the game company Fusionist for gaming and social interaction, which has recently completed its upgrade to version 2.0.

|Item|Value|
|-|-|
Home Page | https://ace.fusionist.io/
|Network Name | Endurance |
RPC URL | https://rpc-endurance.fusionist.io
Chain ID | 648
Currency Symbol | ACE
Block Explorer URL | https://explorer-endurance.fusionist.io/ 

This is the Endurance token, ACE, information on CoinGecko: https://www.coingecko.com/en/coins/fusionist

**Comment by vvvvvv1vvvvvv** [comment]
Rabby supports custom networks now, it means you can use Rabby with any EVM network, this issue will be closed
