### ISSUE TITLE
Permit2 contract marked as EOA on ZkSync

### ISSUE THREAD

**Issue by Lyagushe4ka** [RabbyHub/Rabby#2074]
Uni Permit2 contract is marked as EOA on ZkSync Era `0x0000000000225e31d15943971f47ad3022f714fa` although it is definitely deployed https://era.zksync.network/address/0x0000000000225e31d15943971f47ad3022f714fa

<img width="366" alt="image" src="https://github.com/RabbyHub/Rabby/assets/79344066/7e8642bd-a32f-4c92-b57a-cf555d5d87e1">
<img width="372" alt="image" src="https://github.com/RabbyHub/Rabby/assets/79344066/a6c165e4-6b7c-40db-8b13-52649f8ef2ec">

**Comment by vvvvvv1vvvvvv** [comment]
should be fixed now

**Comment by MaxInMoon** [comment]
I discovered that Uniswap and Koi.finance both rely on this address (`0x0000000000225e31D15943971F47aD3022F714Fa`) for the tokens approvals. Could you please explain me why ??  Is it normal ?
🙏 👀

**Comment by vvvvvv1vvvvvv** [comment]
Permit2 is a open-source tech standard developed by Uniswap team, every dex can rely it as approval router
