### ISSUE TITLE
Show TX value even if simulation isn't supported

### ISSUE THREAD

**Issue by Lyagushe4ka** [RabbyHub/Rabby#2075]
tx value could be easily shown even if tx simulation isnt supported on the current chain for the basic security reason to not to send all your ether by signing some scam tx

<img width="375" alt="image" src="https://github.com/RabbyHub/Rabby/assets/79344066/2c486297-9230-434f-85ec-e0f41e2b346f">
<img width="351" alt="image" src="https://github.com/RabbyHub/Rabby/assets/79344066/66eb6b50-998f-4fd1-aa05-61f1548fc63e">

**Comment by vvvvvv1vvvvvv** [comment]
<img width="402" alt="image" src="https://github.com/RabbyHub/Rabby/assets/86296331/fb821833-2bbe-4650-a21d-c151a79edee8">
will fix in next release
