### ISSUE TITLE
Instructions for custom dApp integrations

### ISSUE THREAD

**Issue by 0xbid** [RabbyHub/Rabby#2110]
For example on Ambient

![image](https://github.com/RabbyHub/Rabby/assets/145181252/0070b1f6-265f-4532-95ae-0a96d184ed1e)

It tracks your liquidity and rewards. I am assuming Uniswap LPing has something similar. How is this done with Rabby? Is there some specific route for a dApp owner to integrate with Rabby to support this?

Thanks!

**Comment by vvvvvv1vvvvvv** [comment]
check https://cloud.debank.com/
