### ISSUE TITLE
Add Support For ETN Network

### ISSUE THREAD

**Issue by bonifacio123** [RabbyHub/Rabby#2115]
Network Name: Electroneum SmartChain
RPC URL: https://rpc.electroneum.com
Chain ID: 52014
Currency Symbol: ETN
Block Explorer URL: https://blockexplorer.electroneum.com

Thank you

**Comment by vvvvvv1vvvvvv** [comment]
Rabby supports custom networks now, it means you can use Rabby with any EVM network, this issue will be closed
