### ISSUE TITLE
Trezor Bridge Appearing on Chrome When Signing a Message

### ISSUE THREAD

**Issue by emerylopes** [RabbyHub/Rabby#2132]
Here the error printed:

![01](https://github.com/RabbyHub/Rabby/assets/69319870/18a70d64-6514-4591-8465-f0b9d135d0c9)

**Comment by aasseman** [comment]
I have the same issue. Metamask works with Trezor without asking for the bridge.

**Comment by vvvvvv1vvvvvv** [comment]
should be fixed in the latest version(v0.92.59)

**Comment by aasseman** [comment]
Now it's asking for the trezor wallet passphrase at every transaction :(
