### ISSUE TITLE
 Please add a new chain. - zkLink Nova

### ISSUE THREAD

**Issue by kihyun0103** [RabbyHub/Rabby#2133]
As there is currently no such chain, many people involved in the project are experiencing difficulties.

Chain ID:0xc5cc4

**Comment by Keref** [comment]
Bump pls, their early liquidity program unlocks soon and there's $300m of assets bridged, would rather avoid reinstalling metamask to move mine

**Comment by vvvvvv1vvvvvv** [comment]
Rabby supports custom networks now, it means you can use Rabby with any EVM network, this issue will be closed
