### ISSUE TITLE
Rabby "flip" feature doesn't actually do anything

### ISSUE THREAD

**Issue by bradbrown-llc** [RabbyHub/Rabby#2147]
I'm writing a dApp and when logging responses for EIP-6963 provider requests, I noticed two things:

1) Rabby does not respond with the proper EIP-6963 provider object, it instead appears to just be responding with the EIP-1193 injected provider object, which, if another wallet is installed, is mangled.

2) The "flip" feature doesn't change Rabby's EIP-6963 provider response object at all.

3) If Rabby's "flip" feature is set to disable Rabby, why is it responding to EIP-6963 provider requests?

This image is of Rabby's EIP-6963 provider request response object as viewed in Chrome's dev tools console. You can see that the the flags isMetaMask and isRabby are both set to true, as this is really just a mangled EIP-1193 provider (if both MetaMask and Rabby are installed). The response is the exact same with the "flip" feature set to disable Rabby or enable Rabby

![image](https://github.com/RabbyHub/Rabby/assets/108493071/2953c69e-4384-4b1c-8ff7-c82f11b6e0e1)

Compare this to MetaMask's EIP-6963 provider request response object, which is a unique object with only MetaMask flags.

![image](https://github.com/RabbyHub/Rabby/assets/108493071/c6cb1210-5e0d-4b6e-a897-beb7e3249064)

Propositions:

1) If the "flip" feature is set to disable Rabby, Rabby should not respond to EIP-6963 provider requests.

2) Rabby should be responding to EIP-6963 provider requests with a unique EIP-6963 provider response object, and not just using the injected EIP-1193 provider.

3) At the bare minimum, if the "flip" feature is set to disable Rabby, Rabby should put something like a `isRabbyEnabled: false` flag on the provider object that it uses to respond to EIP-6963 provider requests.

If 1) or 3) are implemented, then dApp developers should be able to make the dApp responsive to however the "flip" feature is toggled.

**Comment by vvvvvv1vvvvvv** [comment]
The flip feature is for fix conflict of EIP-1193, it's no use for EIP-6963
EIP-6963 is already a solution for wallets conflicts
When you flip to MetaMask, Rabby relinquishes ownership of window.ethereum for EIP-1193

**Comment by bradbrown-llc** [comment]
> Rabby relinquishes ownership of window.ethereum for EIP-1193

Is there a way to detect this relinquishing of ownership as a dApp developer?

**Comment by vvvvvv1vvvvvv** [comment]
If you find there is Rabby provider in EIP-6963 list but no `window.ethereum.isRabby` defined, then it means Rabby relinquishing the ownership

**Comment by bradbrown-llc** [comment]
Except that doesn't happen, if you "flip" Rabby to be banned then isRabby is still true on window.ethereum even after a refresh.

Please reopen the issue and do not mark it as completed if the issue is not resolved.

![image](https://github.com/RabbyHub/Rabby/assets/108493071/57e31ffa-9b72-49aa-b5b2-7298ab6fbe95)

**Comment by vvvvvv1vvvvvv** [comment]
oops, any other wallets you installed other than Rabby and MetaMask?

**Comment by vvvvvv1vvvvvv** [comment]
<img width="536" alt="image" src="https://github.com/RabbyHub/Rabby/assets/86296331/c3a81552-f248-4124-b959-a076705fa862">
it works fine in my side

**Comment by bradbrown-llc** [comment]
> oops, any other wallets you installed other than Rabby and MetaMask?

Yes, I am testing with Rabby, MetaMask, and Talisman installed.

**Comment by vvvvvv1vvvvvv** [comment]
Please disable Talisman and test again, every wallet you install will try to compete for ownership of `window.ethereum,` ultimately leading to unintended consequences.
We can only handle the condition that install Rabby and MetaMask sametime

**Comment by bradbrown-llc** [comment]
I'll let my users know that your wallet cannot handle working with other wallets besides only MetaMask. 


> We can only handle the condition that install Rabby and MetaMask sametime

This is an absurd way to close this issue, all you would need to do is something as simple as:
"if the user sets Rabby to disabled, don't set isRabby to true on the global ethereum object".
Or any of my other propositions.

**Comment by vvvvvv1vvvvvv** [comment]
The most simple way is use EIP-6963 as instead, Flip is just a workaround for EIP-1193, so for long-time user experience, please use EIP-6963 for connect wallet, there are many connectkit will make it easy like Rainbowkit and Rabbykit
