### ISSUE TITLE
Dapp with incorrect (0) gas limit: BEEFY(fantom)

### ISSUE THREAD

**Issue by kur0** [RabbyHub/Rabby#215]
Hi,

There is number of dapp site that I can't submit the txn because of incorrect gas limit value detected.

for example:
https://fantom.beefy.finance/#/

Will

Rabby
![image](https://user-images.githubusercontent.com/1430075/132020875-fbdab329-cb7e-4111-9876-f8d837b649e1.png)
Metamask
![image](https://user-images.githubusercontent.com/1430075/132020995-522bcfc4-1110-4d78-bbe9-bc83581d099f.png)

**Comment by vvvvvv1vvvvvv** [comment]
reproduce stably? can not reproduce, which action you did in this dapp?

**Comment by kur0** [comment]
I am unable to reproduce it today too. Thansk.
