### ISSUE TITLE
Connect wallet popup disappear instantly when using a small browser window.

### ISSUE THREAD

**Issue by Armxy** [RabbyHub/Rabby#2156]
**Environment:**
- 24" 1920x1080 monitor.
- Windows 10
- Chrome Version 123.0.6312.60
- Rabby Wallet Version 0.92.59

Snap Google Chrome window to one of the corner (1/4) of the screen, and most of the time when trying to connect to DAPP, the Rabby connect popup shown and instantly disappear.
Turn the exact Google Chrome window to full size and can connect just fine, I notice that now the sign transaction popup is match the height of Google Chrome window, this maybe the reason.

**Comment by vvvvvv1vvvvvv** [comment]
duplicate with #2150
