### ISSUE TITLE
Deskop & Plugin Under Windows 11 Unable To Connect To Onekey

### ISSUE THREAD

**Issue by bonifacio123** [RabbyHub/Rabby#2157]
When attempting to connect to a Onekey Classic wallet from within Brave version 1.64.113 with Rabby plugin 0.92.59 it gets stuck at Waiting 99%.  Same thing happens when using Rabby Desktop for Windows 0.37.1 - I even tried rebooting the PC and same issue persists. I've made sure I had entered in the pin and unlocked Onekey. However, if I try using Brave with the Rabby plugin under Ubuntu 22.04 it connects to the Onkey Classic wallet as expected.

**Comment by vvvvvv1vvvvvv** [comment]
https://onekey.so/zh_CN/download?client=bridge try install this on your Windows

**Comment by vvvvvv1vvvvvv** [comment]
will close this issue since no response
