### ISSUE TITLE
Loopring exchange unable to unlock layer2 wallet

### ISSUE THREAD

**Issue by kur0** [RabbyHub/Rabby#216]
![image](https://user-images.githubusercontent.com/1430075/132082978-e29ff70a-09ea-4e3f-ac76-f8e3b2dcce19.png)
![image](https://user-images.githubusercontent.com/1430075/132082982-e71f6008-5790-4f8f-869f-72c274765500.png)
I had been using metamask with same address on loopring, however I am unable to "unlock" the same wallet when using the same address with Rabby

I don't think I need to Reset layer-2 keypair as I can unlock the layer2 wallet fine with other wallet (e.g. imtoken on android) with the same wallet address fine.

https://exchange.loopring.io/

**Comment by vvvvvv1vvvvvv** [comment]
since personal_ecRecover is not support for now, will support asap
