### ISSUE TITLE
Testnets are gone

### ISSUE THREAD

**Issue by hell0men** [RabbyHub/Rabby#2161]
After today update i can't connect to Sepolia testnet and don't see any in my wallet. I see only "Сustom testnet" button.
![image](https://github.com/RabbyHub/Rabby/assets/37250060/77761ea6-4fa6-4aa0-a02d-3c2afbe6d3a6)

**Comment by vvvvvv1vvvvvv** [comment]
You can add it back in Custom Testnet, Rabby support custom testnet now so you can add any testnet but not only Rabby supports
