### ISSUE TITLE
Kept asking trezor for passphrase for every transaction

### ISSUE THREAD

**Issue by oxSaturn** [RabbyHub/Rabby#2164]
Reckon something was broken in the latest rabby. It would ask me to input my passphrase for every transaction even though I've checked the `Don't ask me again`, I only had to input once before:

![CleanShot-1V8D7tnF@2x](https://github.com/RabbyHub/Rabby/assets/126733611/c14ed684-76a1-47cf-92dc-1bc80ed04481)

And It works just fine with MetaMask.

**Comment by vvvvvv1vvvvvv** [comment]
This is a known issue of Trezor new SDK, will forward to Trezor team

**Comment by oxSaturn** [comment]
@vvvvvv1vvvvvv Can you reopen it? From what I can tell, someone else was having the same issue on twitter https://twitter.com/kaiynne/status/1777090598048289057

**Comment by jonolumb** [comment]
This is still not fixed for me. Running latest version. Still prompted
constantly, seems like Trezor session is closed after each confirmation.
Very poor UI. Used to work just fine.

oxSaturn ***@***.***> 于 2024年4月8日周一 20:32写道：

**Comment by Zarigis** [comment]
Having the same issue here.

**Comment by pgendreau** [comment]
Same here, is there a known workaround?

**Comment by heisenberg-2077** [comment]
The "remember device" needs to be checked.

<img width="482" alt="" src="https://github.com/RabbyHub/Rabby/assets/110591045/f3c3a3d8-463d-4dfe-9000-e4c251c6fc17">

**Comment by pgendreau** [comment]
> Seems it's fixed in the latest version 0.92.64.

Thanks for that information. I had that version but still had to remove the connection to the device in the site settings of the trezor connect pop-up to be able to pair again and select remember device as @heisenberg-2077 suggested. It seems to be working now
