### ISSUE TITLE
WalletConnect Integration Unusable

### ISSUE THREAD

**Issue by Deagler** [RabbyHub/Rabby#2165]
Many of our users at https://waymont.co like to use Waymont with Rabby.

A recent update on your side appears to have made the WalletConnect integration with Waymont completely unusable. 

Looking through Rabby's code now to diagnose what could have gone wrong, but would appreciate any pointers on how we can fix this. Have also reached out via DeBank Hi.

**Comment by heisenberg-2077** [comment]
Hi @Deagler 
I need to debug to fix the issue, what do I need to do to download the wallet app?

**Comment by Deagler** [comment]
@heisenberg-2077 Do you have Telegram? I can set you up with an account + send Testflight link.

My TG: @Kasueth

**Comment by vvvvvv1vvvvvv** [comment]
should be fixed in the latest version

**Comment by mcstefan7** [comment]
> should be fixed in the latest version

it doesn't work correctly with wallet connect + Binance web3. It connect and disconnect when you need to sign a transaction. You need to reconnect 3-10 times until the connection to be stable.
