### ISSUE TITLE
Extension is not opening if Chrome Dev Tools is opened

### ISSUE THREAD

**Issue by lotinasa** [RabbyHub/Rabby#2175]
Rabby: 0.92.63
MetaMask: 11.13.1
Chrome: latest Version 123.0.6312.106 (Official Build) (64-bit) - Only MM and Rabby extensions enabled
Windows: 10

If Chrome Dev Tools is opened on any tab, click on Rabby icon doesn't open Rabby window. If I close Dev Tools click on Rabby icon opens Rabby window immediately. It doesn't matter on which tab in Chrome Dev Tools is opened.

When Dev Tools is opened, click on Rabby icon marks icon with grey background just  as window is opened but window is not visible, click again on Rabby icon and it is with normal background.

Before Rabby update in last couple of days this issue wasn't present.

**Comment by vvvvvv1vvvvvv** [comment]
can't reproduce your issue, only what I know is if you open the extension's Service Worker's DevTool may cause some issue but never heard open DevTool on other tab page will cause this issue

**Comment by lotinasa** [comment]
When Rabby window is not opening this error is in service worker:
![image](https://github.com/RabbyHub/Rabby/assets/3956262/02880c45-7b01-4679-a773-3eb17f173d20)

**Comment by lotinasa** [comment]
After clicking on STOP/UNREGISTER issue is solved, now Rabby is opening correctly all the time.
