### ISSUE TITLE
Show Wallet Title (UX Improvement)

### ISSUE THREAD

**Issue by nhmtns** [RabbyHub/Rabby#2178]
In the desktop app, "Current" tab, on the top of the page, only wallet address is shown at present. For someone with multiple wallets, it is difficult to easily understand what the current wallet is? 

So, prominently display the user given Wallet "Title/Name" at the very top, above the line where total balance is shown currently.

**Comment by vvvvvv1vvvvvv** [comment]
close since duplicate with https://github.com/RabbyHub/RabbyDesktop/issues/631
