### ISSUE TITLE
ftmscan (fantom) unable to detect Rabby as Wallet

### ISSUE THREAD

**Issue by kur0** [RabbyHub/Rabby#218]
![image](https://user-images.githubusercontent.com/1430075/132725284-cefcefbf-a310-4b16-a2e3-160fd6cb8959.png)
https://ftmscan.com/address/0xce761d788df608bd21bdd59d6f4b54b2e27f25bb#code
goto any contract on ftmscan (eg rarity)
In Write Contract tab, click Connect to Web3.
Popup will says it is unable to detect any wallet

**Comment by vvvvvv1vvvvvv** [comment]
![image](https://user-images.githubusercontent.com/86296331/132788564-d7ebca74-52c5-4056-aca3-3dcc54f6ddc7.png)

try click "Add Fantom Network" in the bottom first, then select Fantom chain, it should be works

![image](https://user-images.githubusercontent.com/86296331/132788686-f0e2e184-4ae3-44eb-bfb7-97c2fcdcf8d4.png)

will report to ftmcan team for this issue

**Comment by vvvvvv1vvvvvv** [comment]
should be works now
