### ISSUE TITLE
Problem with offscreen

### ISSUE THREAD

**Issue by thirdsaintboy** [RabbyHub/Rabby#2194]
In my browser, in the Zennoposter utility, an offscreen window opens, which interferes with my work; it opens randomly.
Which js file contains the code that opens this page so that I can modify the extension and remove part of the code?
Deleting the offscreen html and offscreen js files themselves does not help and it opens a browser window, which means the launch is in another file.

Chrome 113.  v0.92.63
![image](https://github.com/RabbyHub/Rabby/assets/83788534/0423fff5-15a5-427d-88d3-d7074e0eb3ae)
![image](https://github.com/RabbyHub/Rabby/assets/83788534/ddaf39a0-9b87-48bb-a1c9-2b3fc8dbcd83)

**Comment by vvvvvv1vvvvvv** [comment]
https://github.com/RabbyHub/Rabby/blob/develop/_raw/sw.js#L29

remind that offscreen is for hardware wallet, so if you remove it you can't use hw wallet like Ledger Trezor etc

**Comment by dhruvkelawala** [comment]
Does ledger still use offscreen? Looks like the latest refactor removed the usage of bridge?

**Comment by shitinsider** [comment]
> В моем браузере, в утилите Zennoposter, открывается внеэкранное окно, которое мешает моей работе; оно открывается хаотично. В каком js-файле находится код, который открывает эту страницу, чтобы я мог изменить расширение и удалить часть кода? Удаление самих файлов offscreen html и offscreen js не помогает и открывает окно браузера, а значит запуск находится в другом файле.
> 
> Chrome 113.v0.92.63 ![изображение](https://private-user-images.githubusercontent.com/83788534/321605872-0423fff5-15a5-427d-88d3-d7074e0eb3ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5NTI3NTksIm5iZiI6MTczNjk1MjQ1OSwicGF0aCI6Ii84Mzc4ODUzNC8zMjE2MDU4NzItMDQyM2ZmZjUtMTVhNS00MjdkLTg4ZDMtZDcwNzRlMGViM2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE1VDE0NDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NGM5YzUzNGYwMTc3ZWUyNGI1MWRiZmE3NTA1NDljMTg0NDMyOWJmNmFhNTU1ZDRiMDBlMGEwYWFkNDAwZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UCeoBEuhjWC9ZEN8koNIuxKxKhD6zqsyIY7d1rN4oSc) ![изображение](https://private-user-images.githubusercontent.com/83788534/321605901-ddaf39a0-9b87-48bb-a1c9-2b3fc8dbcd83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5NTI3NTksIm5iZiI6MTczNjk1MjQ1OSwicGF0aCI6Ii84Mzc4ODUzNC8zMjE2MDU5MDEtZGRhZjM5YTAtOWI4Ny00OGJiLWExYzktMmIzZmM4ZGJjZDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE1VDE0NDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MDJmNDEzYmJiZWFhODM4ZTc3ZDc0MzAxNGZlM2NjNWZiMmFjYjMwM2Y4ZDk4YzY2ZTBlN2M5NDdjOTQ3OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.prL_o8iEdeeMRihnZwy7qa7NfqYpYvGlb54JCCLz9WE)

Did you find a solution? I have the same problem, I don't understand how to solve it.
