### ISSUE TITLE
Incorrectly submitting cancelled transaction to be signed when using Keystone Pro 3

### ISSUE THREAD

**Issue by Zarigis** [RabbyHub/Rabby#2203]
Platform: Windows 11
Browser: Edge
Hardware Wallet: Keystone Pro 3
Chain: Multiple EVM chains tested
Rabby: 0.92.64

Problem:
After cancelling a transaction before sending it (either on the hardware wallet or from Rabby), and then attempting to send another transaction afterwards, Rabby sends the original (cancelled) transaction to the wallet for signing instead of the new one.

Steps to Reproduce:

- Add a "Keystone" account
- Open "Send" dialogue and send 0.1 ETH to self on mainnet (A)
- Press "Cancel" at prompt
- Open "Send" dialogue and send 0.2 ETH to self on mainnet (B)
- Press "Begin Signing Process"
- Scan QR code on Keystone

Expected result:
Keystone prompts to send 0.2 ETH to self (sign transaction B)

Actual result:
Keystone prompts to send 0.1 ETH to self (sign transaction A)

Additional notes:
If the second transaction (B) is cancelled and third (C) is re-attempted, the keystone will usually prompt for B but sometimes for A.

**Comment by vvvvvv1vvvvvv** [comment]
it's a known issue, fixed in https://github.com/RabbyHub/Rabby/pull/2202

**Comment by Zarigis** [comment]
I just tested that fix and it does not resolve the issue.
