### ISSUE TITLE
Cannot re-connect to Keystone Pro 3 over USB after locking it

### ISSUE THREAD

**Issue by Zarigis** [RabbyHub/Rabby#2207]
After initial setup for the Keystone Pro 3 over USB, if the device is disconnected from USB or the screen is locked, no further transactions can be submitted. The error prompts to try the initial setup again, but this has no effect. Additionally, no further addresses can be added once it is in the state.

The only workaround is to either restart the browser, or reload the Rabby plugin. At this point the expected approval popup is presented on the Keystone and it works as normal until it is locked or disconnected again.

**Comment by vvvvvv1vvvvvv** [comment]
should be fixed in #2211
