### ISSUE TITLE
Not enough time to sign a transaction with Wallet Connect

### ISSUE THREAD

**Issue by coffee-git** [RabbyHub/Rabby#2249]
When I use Wallet Connect account and need to sign a transaction, after clicking on “Begin signing process” a ten second countdown starts. This is not enough to use my hardware wallet (SafePal), scanning QR codes takes time.

**Comment by coffee-git** [comment]
The transaction is executed even after the timer expires, but at this time the error “Transaction rejected” is displayed.

![image](https://github.com/RabbyHub/Rabby/assets/71521983/f724837c-5ce1-4c6e-9c5a-e780af97285b)

**Comment by vvvvvv1vvvvvv** [comment]
fixed in #2256
