### ISSUE TITLE
Cannot sign transactions using Rabby Wallet on Android

### ISSUE THREAD

**Issue by bragmore** [RabbyHub/Rabby#2277]
Hello,

I use android devices as my primary devices as I'm experimenting on swapping completely over to Android (Samsung Galaxy Tab S9 Ultra as my laptop for example).

On my galaxy tab s9 ultra I cannot seem to get Rabby Wallet to work properly.

When being prompted to sign transactions it just doesn't direct me into the right place. I have tried different chromium based browsers which allow the installation of extensions such as Kiwi, Lemur, Yandex, etc.. none of them work with Rabby Wallet. When I try to sign transactions using the Kiwi browser it just closes the tab completely without anything happening, and I cannot continue with my transaction at all.
When trying in other browsers it just doesn't do anything at all - it completely stops working basically.

It works on mobile which is weird.

Not sure if this is related to Samsung's Dex mode which I activated on my tablet. 

Any solution to this? Please help!

Rabby wallet is my primary wallet of choice and I really want it to work. 

Appreciate the good work on this wallet so far.
Thanks!

Best,

J

**Comment by vvvvvv1vvvvvv** [comment]
The extension doesn't support mobile browsers now, please use the mobile app instead, you can find the install URL on https://rabby.io/
