### ISSUE TITLE
Bug on start-up window

### ISSUE THREAD

**Issue by HhvrshH** [RabbyHub/Rabby#2279]
Sometimes when you push button `Import Private Key` wallet turn back us to startup window (Access All Apps) and you must reopen wallet to continue because in current window   `Import Private Key` button and other is unclickable. 

This bug came with last updates.

**Comment by vvvvvv1vvvvvv** [comment]
<img width="414" alt="image" src="https://github.com/RabbyHub/Rabby/assets/86296331/03e789cc-859c-4c9a-974a-d8dd922f9888">
You mean this button? Is it possible to record a video for how to reproduce the issue?

**Comment by HhvrshH** [comment]
Yes this one. Its not regularly bug. Just try start-up wallet using Import Private Key button several times each time in the new instance and you would may catch it.

Recording a video will be problematically a bit)

**Comment by vvvvvv1vvvvvv** [comment]
When this problem occurs, is it a brand new wallet (no other addresses have been imported) or an already initialized wallet?

**Comment by HhvrshH** [comment]
> When this problem occurs, is it a brand new wallet (no other addresses have been imported) or an already initialized wallet?

In mostly times after the bug, wallet is already with address

**Comment by vvvvvv1vvvvvv** [comment]
looking for a way to stable reproduce this issue

**Comment by HhvrshH** [comment]
Maybe you can add logger in new version and i would catch this bug. Also some times  unlocking fall down even i don't close the browser and don't use auto-lock time.

**Comment by HhvrshH** [comment]
![Screenshot_111](https://github.com/RabbyHub/Rabby/assets/52471002/85b906cb-e951-4072-a60e-9007e94606f9)
Maybe some of this errors products this bug?

**Comment by vvvvvv1vvvvvv** [comment]
No, these errors are not related to this issue

**Comment by vvvvvv1vvvvvv** [comment]
fixed in #2383
