### ISSUE TITLE
Blocked tokens still display within total wallet value

### ISSUE THREAD

**Issue by aboruchovas** [RabbyHub/Rabby#2299]
If a token is blocked, can we hide it from our total wallet holdings? Honeypot tokens often skew the total wallet holdings and blocking them doesn't hide the value of them

<img width="387" alt="image" src="https://github.com/RabbyHub/Rabby/assets/43833194/7f4bb54b-4d87-410e-ae3f-3d02b51ac456">

**Comment by aboruchovas** [comment]
where can I report the token? it's this ca: 0x1cbe689f44c56d28c3d2f3d643923d5c8a5d9dc5

**Comment by vvvvvv1vvvvvv** [comment]
removed

**Comment by crypt0grapher** [comment]
That's still the case, isn't it? 
scam token SPELL 0x2d87f0c8991b82ebbba829b9405646a3ec3cb19a was distributed randomly today on bsc
