### ISSUE TITLE
Rapid 'Sign and Create' Followed by 'Confirm' Causes 4001 Error Despite Successful Signatures

### ISSUE THREAD

**Issue by 0xLightt** [RabbyHub/Rabby#2315]
**Issue Description:**

When clicking on 'Sign and Create' followed by 'Confirm' quickly, Rabby throws a 4001 error.

As you can see in the video, I signed a permit and it resulted in a 4001 error, stating "User rejected the request."

[rabby-sign.webm](https://github.com/RabbyHub/Rabby/assets/109751758/967ce3a6-255b-411a-9fbb-2bcdf0bff4bf)

**Details:**
- This issue only occurs with Rabby.
- It seems different from issue #2146, as the error is thrown before the requested signatures reach the next step.
- This never happens if there is a delay between clicking 'Sign and Create' and 'Confirm'.

Thanks in advance! Please let me know if you are aware of any workaround or if there is any more information I can provide.

**Comment by Admin686** [comment]
Hi @0xLightt sorry for the inconvenience caused! All you've to do is rectification with the Rabby optimal weblink and try it again.

**Comment by vvvvvv1vvvvvv** [comment]
hmm can't reproduce, is it only reproduced on specific website or every websites?

https://github.com/RabbyHub/Rabby/assets/86296331/537ade0b-3eec-4311-89c4-7c7f93347a69

**Comment by 0xLightt** [comment]
Hey, I am very sorry for the delay in answering, wanted to come back with as much info as possible. Really appreciate your answer.

Will close this because the real issue was a race condition in our UI: what happened in the video is that after the first signature was signed, the following two were requested at once instead of 1 at a time.

Even though the main issue was not due to rabby, if you wish I can share the repo here after it's public. This also finally happened with metamask, but only witnessed it less than a handful of times over months compared to it happening very frequently with rabby, took only a few times to reproduce it..
