### ISSUE TITLE
[Security issue] Blind sign on Ledger device (ex. USDT on BEP20)

### ISSUE THREAD

**Issue by AdamB2023** [RabbyHub/Rabby#2321]
While sending using Rabby Desktop, the amount and currency visible on the Ledger are replaced by a contract address.
It is way less secure as you don't know to which address and how much you're sending, which is a critical point of security, as what's seen in the UI is never fully reliable possibly leading to loss of funds.

Results on Ledger:
Rabby - Blind signing, BNB 0, address 0x55 (USDT smart-contract address)
Metamask - BSC-USD 1, target address

**Comment by vvvvvv1vvvvvv** [comment]
#2280 will fix this
