### ISSUE TITLE
Full browser tab view like MM expand

### ISSUE THREAD

**Issue by bitstr3am** [RabbyHub/Rabby#2332]
The expand view in MM brings up a browser tab for the wallet which is nice for some scenariosand repeatedly requested by folks accustomed to it and migrating. 

Consider adding full page because of utility AND to help adoption from MM. The desktop app sort of delivers there but not the same and frankly a different feel.

**Comment by vvvvvv1vvvvvv** [comment]
duplicate with https://github.com/RabbyHub/Rabby/issues/2003
