### ISSUE TITLE
[Idea] a button to speed up gas 10% instantly

### ISSUE THREAD

**Issue by kardelitaitu** [RabbyHub/Rabby#2333]
How about add quick action button to speed up gas 10% on pending transaction window
maybe above or beside the usual speed up icon
no need to customize, no need to sign tx, (no popup)
just instant gas+10%
that would be a great features

**Comment by vvvvvv1vvvvvv** [comment]
![image](https://github.com/RabbyHub/Rabby/assets/86296331/07b28784-95d8-4745-8b45-b03713d1d22a)
We already have this
