### ISSUE TITLE
Signing and confirming transactions through another extension

### ISSUE THREAD

**Issue by brauliobo** [RabbyHub/Rabby#2360]
Hi, I'm writing an extension that will trigger Rebalance transactions with vfat.io. I need this extension to work autonomously, so the signature and confirmation of the transactions in the Rabby wallets needs to happen without user interactions.

Can you please advise if iRabby is receiving events that can control its behaviour? I know this is potentially a security issue.

If not, I'll proceed on writing an event handler to automatically sign and confirm transactions

**Comment by vvvvvv1vvvvvv** [comment]
Rabby Wallet cannot confirm transactions without user interactions

**Comment by brauliobo** [comment]
this is how it can be achieved by adding the following lines to the SubmitActions component:

```ts
  let btnClick = (text) => {
    // @ts-ignore
    let btn = [...document.querySelectorAll('button')].find(b => b.innerText.indexOf(text) != null)?.click()
  }

  chrome.runtime.onMessageExternal.addListener(async (message, sender, sendResponse) => {
    while (!disabledProcess) await new Promise(res => setTimeout(res, 3*1000))
    await new Promise(res => setTimeout(res, 5*1000))
    sendResponse({ done: true })
    if (message.type == 'rabby_sign')    btnClick('Sign')
    if (message.type == 'rabby_confirm') btnClick('Confirm')
    if (message.type == 'rabby_cancel')  btnClick('Cancel')
  })
```

A possible design would be to ask for the user to authorize extensions or other senders that would remotely confirm transactions.
