### ISSUE TITLE
Add ability to name wallet addresses

### ISSUE THREAD

**Issue by hdadr** [RabbyHub/Rabby#238]
When we choose from the **Set Current Address** list there might be many wallet which associated with different protocols. 
As a user i want to rename / add name to them so i can differentiate by name and not the wallet address.

One example, i have 2 wallet address attached to the rabby wallet, 0xA and 0xB.
One is hot, the other is cold storage. I would like to name 0xA to _hot_ and 0xB to _cold_.

Imagine having 5-10 wallets and choose between them by wallet address.

**Comment by thanhlmm** [comment]
Agree with this idea. It's hard to know actually address instead of address alias

**Comment by vvvvvv1vvvvvv** [comment]
Try v0.17.0, there is it
