### ISSUE TITLE
Mobile Rabby dApp URL redirection

### ISSUE THREAD

**Issue by lotinasa** [RabbyHub/Rabby#2418]
When dApp URL is redirected on mobile Rabby, wallet connection to Rabby wallet is not responding. 
When redirect is turned off on the same dApp URL, wallet connection is working.

When redirect from https://speedmarkets.xyz/ to https://www.speedmarkets.xyz/ is enabled it is not working. Without redirect wallet connection is working on both domains.

The same thing is happening on https://overtimemarkets.xyz/ where redirect to www is enabled.

Mobile OS: Android 
Rabby version: 0.2.2

Client dApp is using latest npm packages:
@rainbow-me/rainbowkit@2.1.3
wagmi@2.11.2

**Comment by vvvvvv1vvvvvv** [comment]
for rabby mobile, please move to https://github.com/RabbyHub/rabby-mobile/issues
