### ISSUE TITLE
Android apk on f-droid

### ISSUE THREAD

**Issue by grigio** [RabbyHub/Rabby#2421]
Can the apk also be pushed there?

**Comment by Sami32** [comment]
APK in your GitHub repository and F-Droid will avoid using the centralized and restrictive Play Store use (not available to all of us by default or without trick).

It will also permit App like Obtainium to be used.
Overall, it will be more open sourced philosophy IMHO.

**Comment by vvvvvv1vvvvvv** [comment]
for rabby mobile, please move to https://github.com/RabbyHub/rabby-mobile/issues
