### ISSUE TITLE
EIP1559

### ISSUE THREAD

**Issue by belg1o** [RabbyHub/Rabby#243]
All transactions are still sending using legacy transactions. Please look into adding #160 and EIP1559 support at the same time. Thanks.

**Comment by BowTiedPhoenix** [comment]
ouch, got bit by this. switched from Metamask to Rabby yesterday. love Rabby but now I need to use two wallets

**Comment by gwenvador** [comment]
Any updates on EIP1559? It is long overdue..

**Comment by vvvvvv1vvvvvv** [comment]
EIP-1559 is not supoort in v0.23.0

**Comment by mikeaz** [comment]
I'm seeing my Ethereum mainnet transactions submit as legacy transactions here in 2022. Using Version 0.58.0 on Brave.

**Comment by maggo** [comment]
gm 2024 and it seems like it's still sending legacy tx in some cases (custom network?)

**Comment by 0xKingKoala** [comment]
Can confirm

**Comment by cryptohamm-design** [comment]
Can confirm, still sending type 0 transaction when using Sonic $S

**Comment by keccakdog** [comment]
would be appreciated if this would be fixed, as it is a huge UX/QoL issue

**Comment by acegilz** [comment]
Boosted transactions, even on Mainnet leave with type 0. Ended up paying much more than if it would a type-2...
How's this Issue still not addressed?
