### ISSUE TITLE
Popup disappears when chrome is full screen

### ISSUE THREAD

**Issue by dmihal** [RabbyHub/Rabby#247]
When I'm using Chrome in full screen on OS X, and I go to send a transaction, there is a popup that opens, but immediately closes. I'm unable to send transactions full-screen, and must change Chrome to a window to send transactions.

**Comment by lochuan** [comment]
Check back, the issue still exist

**Comment by vvvvvv1vvvvvv** [comment]
Update: We have fixed this issue in 0.27.0 and will release soon(should in today), UI may looks wired but we will optimize it soon
