### ISSUE TITLE
Add safe support for Metis

### ISSUE THREAD

**Issue by brotherlymite** [RabbyHub/Rabby#2521]
Metis network uses a fork of gnosis safe for multi-sig, [Metis-Safe](https://metissafe.tech/) which does not seem to be supported by rabby and having a support for the Metis-Safe would be quite helpful as there is no other multi-sig on Metis currently.

**Comment by vvvvvv1vvvvvv** [comment]
we currently can not support self-host safe, can only support official supported safe
