### ISSUE TITLE
Explore tab in mobile app not working properly

### ISSUE THREAD

**Issue by theBSH** [RabbyHub/Rabby#2527]
there isnt a place to report the apps bugs so i though i should brig it here
im using the latest version of the rabby app on my ios device

i use ebi.xyz for trading and the explore tab is the only place i can log into it using my wallet so i must use the app
and in the trading page the chart doesn't load while on safari it does.

**Comment by Kiari26** [comment]
Hello @theBSH i will suggest you message support on telegram https://t.me/Rabby_Moderator like i did when i had a similar issue. They will assist you on what to do. Thanks

**Comment by vvvvvv1vvvvvv** [comment]
for rabby mobile, please move to https://github.com/RabbyHub/rabby-mobile/issues
