### ISSUE TITLE
Option to toggle gas fee display between token and USD in Rabby Wallet

### ISSUE THREAD

**Issue by anonployed** [RabbyHub/Rabby#2528]
I have noticed that the current display for gas fees in Rabby Wallet defaults to showing the value in the **gas token**. While the option to see the **USD value** by hovering over the gas fee is available, I find it less intuitive than the previous format where the USD value was shown more directly.

The new system makes it easier to **accidentally accept higher gas fees** if the user isn’t aware of the current price or forgets to hover over the gas fee to check its equivalent in USD. I believe that while the current system has its merits, it would be better to allow users to **choose their preferred display format through settings**. Alternatively, there could be an option to **toggle between gas token and USD value by simply clicking** on the gas price display.

This small enhancement could **improve the user experience** by giving more control and transparency over gas fee information.

**Comment by anonployed** [comment]
luv u ♥️
<img width="276" alt="image" src="https://github.com/user-attachments/assets/fafa4e46-0398-48cf-bacc-e63c508a3161">

**Comment by vvvvvv1vvvvvv** [comment]
resolved in the latest version
