### ISSUE TITLE
Switching wallets in Rabby results in stale wallet connection for connected Dapp in Brave

### ISSUE THREAD

**Issue by 0xnac** [RabbyHub/Rabby#2530]
We are currently investigating an issue where users of our Dapp occasionally run into the problem that if they change their wallet in Rabby, it does not update in the connected Dapp. The connected wallet in the Dapp remains the previous one, not reflecting the currently selected one.

This is problematic because when people sign their transactions, they do so with the new wallet address but could unknowingly send it to the previous wallet address.

We are using [Web3-onboard](https://github.com/blocknative/web3-onboard) as our injected wallet connection provider and initially thought this issue was related to their package. However, we noticed that when trying this with other Dapps, the issue is the same, leading us to believe it is either related to Rabby or Brave.

I do not have exact steps to reproduce this issue as there seems to be no visible pattern so far, but the way I was able to reproduce it a few times is as follows:

1. Connect to the Dapp with the Rabby wallet.
2. Open a new tab and switch to another wallet in Rabby.
3. Return to the Dapp tab and see that it is still connected to the previous wallet address.

When this happens, it gets stuck with that wallet, and no matter how often we try, it won’t change. The reason for this is that the `accountsChanged` event is not triggered on the `EIP1193Provider`.

Rabby wallet: `0.92.90`
Brave: `1.70.117`

This is a big issue, so I’d appreciate any assistance with this.

**Comment by vvvvvv1vvvvvv** [comment]
fixed in https://github.com/RabbyHub/Rabby/pull/2526

**Comment by vvvvvv1vvvvvv** [comment]
close since it has been released
