### ISSUE TITLE
increase max number of ledger wallet

### ISSUE THREAD

**Issue by bb111189** [RabbyHub/Rabby#2544]
Right now, ledger import only supports up to 50 wallets. 
A suggestion is to increase it to a higher value e.g a few hundreds

**Comment by vvvvvv1vvvvvv** [comment]
click "Advanced Settings" then change the number to 50, you can import 50 to 100 now
![image](https://github.com/user-attachments/assets/e6acd008-6a39-4b8f-95b0-2fe146af0b3b)
