### ISSUE TITLE
Submitting a transaction with Ledger results in error roughly ~30% of times for all of our users

### ISSUE THREAD

**Issue by 0xshippor** [RabbyHub/Rabby#2547]
Hey everyone!

We have recently started our public testnet and were recommending users to use Rabby. We have distributed mock tokens to wallets of our users on testnet based on their specific token amounts on mainnet. Now a lot of those wallets, being used on mainnet, were hardware wallets namely Ledger. Our testnet runs on arbitrum sepolia.

Users have been reporting following error `Incompatible EIP155-based V 843518 and chain id 421614. See the Common parameter of the Transaction constructor to set the chain id.` after signing transaction on their Ledger.

![rabby_error](https://github.com/user-attachments/assets/01a9d498-7a59-4b33-a615-5e01666724ad)

Example raw transaction shown in Rabby while signing
```
{
  "chainId": 421614,
  "data": "0x8634d9c800000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000",
  "from": "0x0c366680d1b8d01a194e90be1857f8186ae0e4bb",
  "gas": "0x2ac48",
  "gasPrice": "0x7270e00",
  "nonce": "0x13",
  "to": "0x4Ac6044247C569D7E5b5c7B609aADF3C63D75211",
  "value": "0x0"
}
```
(this is just our custom multicall with empty batch execution array)

This fails around 30% of the tries. Me and our users were not experiencing this issue on Metamask with Ledger connected so I assume the issue is on Rabby's side. If needed I can provide the code but it really is just any write function call on arbitrum sepolia and error is triggered sporadically.

Things I tried
- using custom wallet connector for EIP1193-supported wallets
- using web3-onboard as wallet connector
- adding `chainId` into function call

[Codesandbox code link](https://codesandbox.io/p/sandbox/6mmg2m)
[Codesandbox app link](https://6mmg2m.csb.app/)

To reproduce
- connect Rabby extension with Ledger HW wallet connected to Rabby 
- call any write function on any contract (i.e. `aggregate` on [multicall](https://github.com/mds1/multicall) with empty `calls` array) using ethers or wagmi - in codesandbox just press Execute
- sign the transaction using Ledger
- there's roughly 30% chance of mentioned error happening
- refresh your webapp if error is not triggered and try again

EDIT: Added simple example

Thank you for working on this awesome project, we and our community really love UX of Rabby.

**Comment by vvvvvv1vvvvvv** [comment]
@QingWei-Li can you help to check this?

**Comment by Kiari26** [comment]
Hello @0xshippor i will suggest you message support on telegram https://t.me/Rabby_Moderator like i did when i had a similar issue. They will assist you on what to do. Thanks

**Comment by vvvvvv1vvvvvv** [comment]
going to close this issue since it's issue of Ledger, please report to Ledger team

**Comment by lambertkevin** [comment]
Problem should have been fixed by https://github.com/LedgerHQ/ledger-live/pull/8175 👍
