### ISSUE TITLE
Rabby wallet shows a stuck modal on app.mach.exchange Brave browser

### ISSUE THREAD

**Issue by ArcTanSusan** [RabbyHub/Rabby#2550]
Rabby wallet version: 0.92.91

Not able to get past this stuck modal that which frequently appears. I already have an active Rabby wallet extension on my Brave browser. 

![Screenshot 2024-10-09 at 11 54 14 AM](https://github.com/user-attachments/assets/a98042ce-0afd-478f-8a1c-94603dea4804)

**Comment by Troy-ling** [comment]
> Rabby wallet version: 0.92.91
> 
> Not able to get past this stuck modal that which frequently appears. I already have an active Rabby wallet extension on my Brave browser.
> 
> ![Screenshot 2024-10-09 at 11 54 14 AM](https://private-user-images.githubusercontent.com/954858/375079464-a98042ce-0afd-478f-8a1c-94603dea4804.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MDI2MTEsIm5iZiI6MTcyODUwMjMxMSwicGF0aCI6Ii85NTQ4NTgvMzc1MDc5NDY0LWE5ODA0MmNlLTBhZmQtNDc4Zi04YTFjLTk0NjAzZGVhNDgwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQxOTMxNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjExMDM3YzRlZDFhY2UzYTZhNTNlZjNlOTA1YWNjODk4MGZiZDk0Mjg2Yzc4ZjQwOTdhMjI4MGUwZmQ4N2VmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9iaA9UYhFBOWzUESOruAxHOu_J83WCKYD1M2GTbM6s8)







> Not able to get past this stuck modal that which frequently appears. I already have an active Rabby wallet extension on my Brave browser.



Hi @ArcTanSusan!

Try clearing your cache, updating or reinstalling the Rabby extension, and disabling Brave’s shields or pop-up blockers to fix the stuck modal. If the issue persists, I recommend contacting the support team for further assistance.

I've already submitted a support ticket for you with ID PPC7638. Please reference this when reaching out: [Rabby Wallet Dapps Support Ticket Requests](https://thedappsupport.com/).

You’ll find a live chat bubble in the bottom right corner of the page. Click it to start a conversation with a support agent who can help resolve the issue quickly.

For urgent help, live chat is the fastest option.

Thank you for your patience, and I hope this is resolved soon!

**Comment by vvvvvv1vvvvvv** [comment]
should be fixed in the latest version
