### ISSUE TITLE
Bug: xDAI not showing up in Gnosis Chain

### ISSUE THREAD

**Issue by 0x6080** [RabbyHub/Rabby#2598]
xDAI is the native token in Gnosis Chain, but it doesn't show up anywhere if you have some xDAI in Rabby.

**Comment by vvvvvv1vvvvvv** [comment]
can you make a screenshot? it works fine in my side
<img width="394" alt="image" src="https://github.com/user-attachments/assets/f8296ede-cf9b-413f-8037-e38f690b186f">
