### ISSUE TITLE
[BUG] Notifications flood - Rabby Desktop 0.92.96

### ISSUE THREAD

**Issue by AdamB2023** [RabbyHub/Rabby#2603]
Rabby Desktop 0.92.96
Brave 1.71.121 Chromium: 130.0.6723.91

After sending transaction, the same browser notification keeps appearing multiple times.
Clearing pending & local node reset option isn't fixing it.
It's about these one:
![image](https://github.com/user-attachments/assets/89da39c6-373c-4d97-809f-49e23db97afa)

**Comment by vvvvvv1vvvvvv** [comment]
fixed in https://github.com/RabbyHub/Rabby/pull/2604
