### ISSUE TITLE
Allow adding custom RPC endpoints

### ISSUE THREAD

**Issue by smartins** [RabbyHub/Rabby#261]
Having just tried Rabby, coming from MM, it's a significant upgrade in terms of speed and ease of use. Unfortunately one thing that I use heavily on MM are custom RPC endpoints, since I tend to run infrastructure for some chains and prefer to use my own private nodes.

I would like to request the option of adding our own custom (preferably multiple) chain endpoints to Rabby.

**Comment by Utone** [comment]
Indeed many improvements over MM and faster using DeBank API endpoints.
(while it's likely better than the public RPC)

Use of private node is required/preferred for most of my use cases. Any update or ETA for this feature?

**Comment by miketsui3a** [comment]
Is this feature on the roadmap?

**Comment by DJHellscream** [comment]
Please add this feature. It's very important now that private RPCs are much easier to acquire with a lot of projects allowing people to purchase them.

This would be really big and bring a lot more users over to Rabby.

**Comment by waynehoover** [comment]
Without this feature I can not switch from MetaMask.

**Comment by DJHellscream** [comment]
With new subnets on Avalanche launching, we really need to be able to add our own RPC endpoint. Please at the very least let us know whether this is being worked on or not.

**Comment by armaccloud** [comment]
@vvvvvv1vvvvvv Would you mind providing a quick update on this request?
It seems to be one of the more requested functionalities looking at the linked duplicates. 

A huge adoption could come from the PulseChain community, the fork from Ethereum; maybe testnet could already be tried out as a custom RPC?

**Comment by dragoonzx** [comment]
We need this feature 🙏🏻

**Comment by krogla** [comment]
+1

**Comment by maguroid** [comment]
This is only the reason that I can't delete Metamask and completely switch to Rabby. This feature would be appreciated.

**Comment by AoDev** [comment]
Same, as a DAPP dev, I'd like to get something better than Metamask. We need this feature.

**Comment by burningtree** [comment]
+1

**Comment by drortirosh** [comment]
any progress on this one? highly required

**Comment by yuhua99** [comment]
we need custom RPC!

**Comment by belg1o** [comment]
Bump @vvvvvv1vvvvvv 

Need this with more testnets coming out. Allow users to set their own RPC endpoints please.

**Comment by wenjoy** [comment]
we need custom RPC!

**Comment by 0xRusowsky** [comment]
we need custom RPC!

**Comment by raster21** [comment]
From what I can see, Rabby relies on Alchemy RPC, which tracks IP, cookies, mobile carrier, browser/device info, location and ISP according to their privacy policy.

If you take privacy seriously, you need to allow your users to set a custom RPC.

**Comment by waynehoover** [comment]
It might be time for a community fork.

**Comment by 0xRusowsky** [comment]
> From what I can see, Rabby relies on Alchemy RPC, which tracks IP, cookies, mobile carrier, browser/device info, location and ISP according to their privacy policy.
> 
> If you take privacy seriously, you need to allow your users to set a custom RPC.

Rabby is losing users because of this. Alternatives such as 0xframe which have a worse product are getting traction because of their ability to use custom RPCs endpoints.

Please take our requests seriously...

**Comment by DefiEcoSystem** [comment]
Why is this closed?

**Comment by belg1o** [comment]
@vvvvvv1vvvvvv needs to enable adding custom RPCs fully, not editting RPC urls from current selection. 

Also adding the ability for default testnet RPCs as a toggle would be nice.

**Comment by cylzxje** [comment]
ok I need RPC CONFIGURATION. like VERY SOON. I cant take METAMASK anymore. every day I am checking for RPC CONFIGURATION and it is not there. every day, check GITHUB, no RPC CONFIGURATION. I cant take this anymore, I have been DOXXED by DEBANK, by a lot. it is what it is. but I need the RPC CONFIGURATION in RABBY ALREADY. can devs DO SOMETHING??

**Comment by arminreiter** [comment]
please add this feature - its essential and would boost rabby as a real alternative to metamask.

**Comment by jmartsch** [comment]
This is already integrated. Are you guys aware of the Custom RPC under "settings"?
![image](https://user-images.githubusercontent.com/551551/235887592-44cb1984-127c-44c9-bade-535c3312c36f.png)

**Comment by belg1o** [comment]
> 

This is not a 'good' or proper custom RPC implenentation. Switching out RPC providers is okay, but we need the ability to add new or edit true custom ones. Not just the list Rabby provides.

**Comment by jmartsch** [comment]
> > 
> 
> This is not a 'good' or proper custom RPC implenentation. Switching out RPC providers is okay, but we need the ability to add new or edit true custom ones. Not just the list Rabby provides.

Did you even try the feature? Maybe I don't understand something, but I added a custom RPC endpoint on Avalanche. This is not provided by rabby.

**Comment by belg1o** [comment]
> > > 
> > 
> > 
> > This is not a 'good' or proper custom RPC implenentation. Switching out RPC providers is okay, but we need the ability to add new or edit true custom ones. Not just the list Rabby provides.
> 
> Did you even try the feature? Maybe I don't understand something, but I added a custom RPC endpoint on Avalanche that is not provided by rabby.
> 
> ![image](https://user-images.githubusercontent.com/551551/235888753-1501aee8-9b4f-4e92-b8d4-9da9b341222b.png)

I have, I use personal nodes for the chains supported. What this request is mainly asking for is adding custom chains, for example we cannot add testnets or other new chains we might be exploring.

**Comment by trendespresso** [comment]
The Custom RPC doesn't let me add AVAX Fuji for example. How can I get Avalanche C-Chain Fuji into Rabby??

**Comment by JozefJarosciak** [comment]
This is not allowing me to add a custom RPC for a blockchain we're developing, thus forcing me to switch back to MetaMask which fully supports adding custom new RPCs. 
This is absolutely essential for developers. Why is such a basic functionality and a backbone for communication not supported? Come on!
