### ISSUE TITLE
RPC Authentication Issue with PulseChain Custom RPC

### ISSUE THREAD

**Issue by g4mm4io** [RabbyHub/Rabby#2612]
When attempting to add a custom RPC endpoint for PulseChain (https://rpc-pulsechain.g4mm4.io), Rabby Wallet returns "RPC Authentication Fail" errors. The RPC endpoint itself is functional and accessible.

The RPC endpoint works properly with direct JSON-RPC calls:
curl -X POST -H "Content-Type: application/json" -d '{"method":"eth_chainId","params":[],"id":1,"jsonrpc":"2.0"}' https://rpc-pulsechain.g4mm4.io
Returns correct chainId: {"jsonrpc":"2.0","id":1,"result":"0x171"}

CORS headers are properly configured:
- Access-Control-Allow-Headers: Content-Type
- Access-Control-Allow-Methods: POST
- Access-Control-Allow-Origin: *

Chrome DevTools Network tab shows no requests being made during the failure, suggesting client-side validation is failing before RPC connection attempt.

Technical Details:
Chain ID: 369 (0x171)
Network: PulseChain
RPC URL: https://rpc-pulsechain.g4mm4.io

Expected: Should successfully add the RPC endpoint to Rabby wallet.
Actual: "RPC Authentication Fail" errors with no visible network requests.

The same RPC endpoint works consistently with other web3 wallets, suggesting this is specific to Rabby's validation process.

**Comment by vvvvvv1vvvvvv** [comment]
this rpc works fine in myside, maybe you can ask help from rpc provider

**Comment by g4mm4io** [comment]
I am the rpc provider, there's nothing wrong with the rpc endpoints. it works. I'll have to try deleting the rabby extension and reinstalling, see if that fixes this issue. I thought maybe it's a verification issue from within the app.. Since there are no failed calls to the RPC in the dev tools when trying to add https://rpc-pulsechain.g4mm4.io it just says RPC Authentication Fail but doesn't actually try to connect to the rpc as far as I can tell.

**Comment by g4mm4io** [comment]
> this rpc works fine in myside, maybe you can ask help from rpc provider

![Screenshot 2024-11-11 at 8 37 33 PM](https://github.com/user-attachments/assets/9364928d-2677-4278-862d-0a3705b5a34b)
![Screenshot 2024-11-11 at 8 38 01 PM](https://github.com/user-attachments/assets/96da322b-f5ef-4393-bbd9-a9f293d1e09c)
I'd like for you to explain why I can enter https://rpc-pulsechain.g4mm4.io. << see the period >> and it works fine, but if I put https://rpc-pulsechain.g4mm4.io << without the period >> it says RPC Authentication Fail. this is clearly a problem with your app just not liking my url, so it's not a RPC problem.. and this is my RPC by the way. I know it works perfectly fine....
