### ISSUE TITLE
Unable to sign transactions, showing 0 balance on sepolia

### ISSUE THREAD

**Issue by kritik-sah** [RabbyHub/Rabby#2641]
# !URGENT
hi, We are building a defi product and during test some of our user use rabby wallet and they are facing this error.
even though they had sepolia eth in their wallet but they are an able to sign/execute any transactions.

sharing an wallet image with you guys
Address 1: 0x8e2dc1D01C90EC7067f06E9Db25A1B6f9fF56497
![Screenshot 2024-11-25 at 5 29 44 PM](https://github.com/user-attachments/assets/656cb4c7-8ef1-4dda-8349-f7a6ee47b797)

user 2:  0x8624F05b786874F71f80fbBf949FB63339a41334
![image_2024-11-25_17-19-31 (1)](https://github.com/user-attachments/assets/a7fce225-1827-4d88-9025-eae45df181d3)

while with same private key user can do this transactions using metamask

**Comment by kalrashivam** [comment]
faced the same issue

**Comment by vvvvvv1vvvvvv** [comment]
the rpc on chainlist not working anymore, can't test
![image](https://github.com/user-attachments/assets/db95997a-3f44-4696-ba0d-3c3100a447eb)

**Comment by kritik-sah** [comment]
So how to resolve it?

**Comment by vvvvvv1vvvvvv** [comment]
i don't know, the rpc server not working, you need to ask chain team for a working rpc

**Comment by kritik-sah** [comment]
> i don't know, the rpc server not working, you need to ask chain team for a working rpc

Bro how can you close this issue, people are using your product, so fix it.

**Comment by Athensmo** [comment]
> > i don't know, the rpc server not working, you need to ask chain team for a working rpc
> 
> Bro how can you close this issue, people are using your product, so fix it.

Kindly reopen this issue, you can resolve this by using the Decentralize Dapps Protocol
