### ISSUE TITLE
Imported Seed Phrase on Rabby Wallet Mobile App Shows New Addresses

### ISSUE THREAD

**Issue by Zoowee26** [RabbyHub/Rabby#2642]
Hello Rabby Wallet Team,

I recently installed the Rabby Wallet mobile app from the official Google Play Store and imported my seed phrase, which I have been using with the Rabby Wallet browser extension on my desktop. However, upon completing the import, the app generated new wallet addresses that do not match the ones I was using previously.

Here are the details:

I verified that I installed the official Rabby Wallet mobile app.
The seed phrase used is correct and has been working without issues on the desktop extension.
The mobile app seems to generate addresses with a different derivation path or configuration.
Could you please confirm if the Rabby Wallet mobile app uses the same derivation path as the browser extension? If not, how can I retrieve the original addresses linked to my seed phrase?

Thank you for your assistance. I look forward to your guidance on resolving this issue.

Best regards,
Gilles

**Comment by Andesxtzgerald** [comment]
> Hello Rabby Wallet Team,
> 
> I recently installed the Rabby Wallet mobile app from the official Google Play Store and imported my seed phrase, which I have been using with the Rabby Wallet browser extension on my desktop. However, upon completing the import, the app generated new wallet addresses that do not match the ones I was using previously.
> 
> Here are the details:
> 
> I verified that I installed the official Rabby Wallet mobile app. The seed phrase used is correct and has been working without issues on the desktop extension. The mobile app seems to generate addresses with a different derivation path or configuration. Could you please confirm if the Rabby Wallet mobile app uses the same derivation path as the browser extension? If not, how can I retrieve the original addresses linked to my seed phrase?
> 
> Thank you for your assistance. I look forward to your guidance on resolving this issue.
> 
> Best regards, Gilles


Hello @Zoowee26 
You’re experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID RAB12638
Please see the link below to our dedicated support line:
[Rabby Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by vvvvvv1vvvvvv** [comment]
both using bip44 hd path, please double check your seed phrase and hd path
![image](https://github.com/user-attachments/assets/30b3b5e8-8bb5-43c6-ace0-a767e5a37be2)
