### ISSUE TITLE
Request for Support of Trezor via USB for Rabby Mobile

### ISSUE THREAD

**Issue by 0xGitGuy** [RabbyHub/Rabby#2649]
Trezor One is very accessible from a price standpoint compared to Ledger Nano X (perhaps due to it's bluetooth feature). It is also battle tested. Opening up to USB hardware devices would enable more users access to Rabby mobile.

**Comment by keo** [comment]
👍

**Comment by vvvvvv1vvvvvv** [comment]
for rabby mobile, please move to https://github.com/RabbyHub/rabby-mobile/issues
