### ISSUE TITLE
Repeated (3) failed transactions on Beefy Finance on Fantom

### ISSUE THREAD

**Issue by roleerob** [RabbyHub/Rabby#265]
This morning, I have run into an insurmountable (for me anyway ...) problem executing a transaction on Beefy Finance on Fantom:

[Screenshot of Rabby](https://cdn.discordapp.com/attachments/859693145251119156/901195097692057710/unknown.png)

Even if I click the "I'm sure I want to proceed anyway" checkbox, it still fails - costing me FTM in the process, each time ... The problem (at least 1 of them) is the gas limit is 0. Rabby is not autopopulating that value.  With no value, the transaction automatically fails.  The 3 failures are due to my own attempt to populate this "Advanced" field.  Obviously with no success ...

I am a new user and have been very impressed with Rabby, hoping it will fully replace my use of Metamask.  In this instance (after successfully using it for over a day on a number of transactions), I had to deactivate Rabby and reactivate Metamask, which successfully completed the transaction.

Edit, 23 Oct 2021:  Here is the Beefy Finance Contract which generated the above issue - [USDC Contract on Fantom](https://ftmscan.com/address/0x2438009ba14a93e82ab43c66838e57be27a55aa1).

**Comment by roleerob** [comment]
Had another issue this morning @vvvvvv1vvvvvv:

[Screenshot of Rabby](https://user-images.githubusercontent.com/31572169/139541027-9c0cbc94-111c-46c3-839a-87519a45ae90.png)

Rabby was not accurately assessing the balances I had in my wallet.  In this case BNB.  It was "stuck" on a previous balance, prior to my making an exchange.  As a result, I got this unsettling message, when attempting to transfer it to a different wallet.

From what you said above, I did go ahead and it did work okay.  It is just unsettling for users to see these "... want to proceed anyway?" boxes to check, as how would we know? 🤷‍♂️

I'm sure you are working steadily on making it better.  And, again, I'll say overall how much I like what you (and your team?) are doing with it.  It looks like it is well on the way to being a big improvement over MetaMask!

---

P.S. It did not seem appropriate to create a new issue for what I am reporting here, although somewhat different than my original message.  Hope that is okay.

**Comment by vvvvvv1vvvvvv** [comment]
> Had another issue this morning @vvvvvv1vvvvvv:
> 
> [Screenshot of Rabby](https://user-images.githubusercontent.com/31572169/139541027-9c0cbc94-111c-46c3-839a-87519a45ae90.png)
> 
> Rabby was not accurately assessing the balances I had in my wallet. In this case BNB. It was "stuck" on a previous balance, prior to my making an exchange. As a result, I got this unsettling message, when attempting to transfer it to a different wallet.
> 
> From what you said above, I did go ahead and it did work okay. It is just unsettling for users to see these "... want to proceed anyway?" boxes to check, as how would we know? 🤷‍♂️
> 
> I'm sure you are working steadily on making it better. And, again, I'll say overall how much I like what you (and your team?) are doing with it. It looks like it is well on the way to being a big improvement over MetaMask!
> 
> P.S. It did not seem appropriate to create a new issue for what I am reporting here, although somewhat different than my original message. Hope that is okay.

it's a known issue since our BSC node meet delay issue recently
