### ISSUE TITLE
Rabby is tracking all websites we visit without permission !!

### ISSUE THREAD

**Issue by BABA3344** [RabbyHub/Rabby#2650]
It appears that in the latest update
Rabby is tracking all websites we visit without permission? 
There aren't even settings to disable such annoying privacy violation?

https://api.rabby.io/v1/wallet/eth_rpc?origin=https%3A%2F%2Fgoogle.com&method=net_version

This is concerning and needs to be addressed immediately.

![1](https://github.com/user-attachments/assets/1a88503e-ef60-4ef8-9f31-49576c69f25f)

**Comment by vvvvvv1vvvvvv** [comment]
it's a bug, will fix in next release

**Comment by BABA3344** [comment]
What is happening with this wallet is absolutely unacceptable! We are not talking about guesses or assumptions here; this is a confirmed fact: the wallet is tracking every website users visit!

I used to consider the Rabby wallet one of the best digital wallets, despite its moderately centralized nature. However, when it reaches this level of tracking and violation of user privacy, such behavior amounts to a great betrayal that only the corrupt would dare to commit.

You claim in your privacy policy that you don’t log IP addresses, yet you are tracking every move users make online????! Does that make any sense? This is deceitful, unethical, and completely unprofessional behavio

What makes the situation even worse is that you introduced this tracking without any clear announcement or notice to the users! Sneaking in such a dangerous change secretly is a blatant betrayal of users' trust

No wallet with good intentions or respect for its users would ever engage in such disgraceful actions. How can anyone possibly justify such behavior? This is utterly unacceptable and cannot be tolerated!

**Comment by vvvvvv1vvvvvv** [comment]
To clarify: Rabby does not collect your private information. This is a bug that causes unnecessary requests to be made. Because the net_version of each network may be different, Rabby needs to get it through rpc requests, but due to unexpected error logic, we sent requests to each website.
This bug will be fixed soon: we will not request net_version on unconnected websites, and will not use the website's domain name when requesting net_version
Sorry again for the inconvenience caused to you, I promise that this problem will be fixed ASAP

**Comment by vvvvvv1vvvvvv** [comment]
fixed in https://github.com/RabbyHub/Rabby/pull/2651

**Comment by BABA3344** [comment]
Rabby urgently needs to implement more comprehensive privacy control options
For example, MetaMask provides users with extensive options to manage their privacy settings. Isn’t this a more transparent approach? They explicitly state that they retain the user’s IP address when their proprietary RPC node is used, but they also provide alternative options, allowing users to opt out of such tracking. This level of transparency and user control is essential.

For a wallet that aims to compete with MetaMask, providing at least the same level of privacy should be a top priority.

Moreover, Rabby should only operate when explicitly called upon. There's absolutely no justification for sending network requests or performing background operations when the wallet isn't even open.

https://api.rabby.io/v1/wallet/eth_rpc?origin=rabby&method=eth_getTransactionReceipt

These requests are happening even when the wallet is completely inactive
and why is there no option to disable this behavior?

A wallet should respect user privacy by default and allow users to fully control its activity. Without such features, this lack of transparency and control raises serious concerns about trustworthiness.

I hope you take this feedback seriously and work towards ensuring that Rabby respects user privacy and provides more robust privacy controls.
