### ISSUE TITLE
More comprehensive privacy control options

### ISSUE THREAD

**Issue by BABA3344** [RabbyHub/Rabby#2660]
Rabby urgently needs to implement more comprehensive privacy control options
For example, MetaMask provides users with extensive options to manage their privacy settings. Isn’t this a more transparent approach? They explicitly state that they retain the user’s IP address when their proprietary RPC node is used, but they also provide alternative options, allowing users to opt out of such tracking. This level of transparency and user control is essential.

For a wallet that aims to compete with MetaMask, providing at least the same level of privacy should be a top priority.

Moreover, Rabby should only operate when explicitly called upon. There's absolutely no justification for sending network requests or performing background operations when the wallet isn't even open.

https://api.rabby.io/v1/wallet/eth_rpc?origin=rabby&method=eth_getTransactionReceipt

These requests are happening even when the wallet is completely inactive
and why is there no option to disable this behavior?

A wallet should respect user privacy by default and allow users to fully control its activity. Without such features, this lack of transparency and control raises serious concerns about trustworthiness.

I hope you take this feedback seriously and work towards ensuring that Rabby respects user privacy and provides more robust privacy controls.

**Comment by vvvvvv1vvvvvv** [comment]
`eth_getTransactionReceipt` is rpc call for check your pending transaction is completed or now, if you do not have any pending transaction, this rpc will not be called :)
