### ISSUE TITLE
Trezor Integration been broken for a month or more. No one else?

### ISSUE THREAD

**Issue by gruvin** [RabbyHub/Rabby#2668]
When trying to add new Trezor addresses, we get "TrezorConnect has stopped. Please refresh the page to connect again." This is not true. Trezord is just fine and Metamask has no issues what-so-ever. Evidently, something is has changed int he Rabby / Trezor integration protocols.

This is happening on both my Intel iMac and my MacBook Pro M3, each running the latest version of Chrome and with all other extensions disabled for testing. 

I am unable to give further details (wouldn't know where to look) bu am 82% (±80%) confident that anyone else who tries this will be presented with the same failure -- at least, here's hoping.

Thanks.

P.S: There's also been this annoying thing where the first attempt to do anything with the Trezor, even for existing accounts just stalls out with the Trezor spinner ring thing. I cancel, click the same action again and it always works the second time. That's been going on for months as well. Again, **there have been no issues with Metamask what-so-ever** over this entire time. I'm hopeful I don't have some obscure unique nonsense going on, even on two separate machines!

**Comment by vvvvvv1vvvvvv** [comment]
Please check:
1. Is your Rabby the latest version (v0.93.4)?
2. Is your Trezor firmware updated to the latest version?
3. If the first two checks are OK, please provide a screenshot and I will help you contact the Trezor team for help

**Comment by vvvvvv1vvvvvv** [comment]
can you try inspect the "TrezorConnect is stopped..." page(right click on page, then click "inspect"), open "Console", then make a screenshot?
I checked the code and found the error should be logged
![image](https://github.com/user-attachments/assets/4d46c491-fe27-4437-8a10-b174be5e5be6)
