### ISSUE TITLE
BitBox missing from initialization 

### ISSUE THREAD

**Issue by jadzeidan** [RabbyHub/Rabby#2670]
Since a recent release, the BitBox02 is missing from the initial setup UI (picture below).

It would be great if BitBox can be added again. BitBox customers have been reaching out to us being confused.

<img src="https://github.com/user-attachments/assets/0893e6f0-58bf-4179-ab80-49aa54b30f0e" width="500">

**Comment by vvvvvv1vvvvvv** [comment]
It is just not displayed in the new user guidance process. Due to limited manpower, we only integrated some hardware wallets into the new user guidance process (sorted by transaction count). 
Users can still add it after the guidance process is completed. Bitbox has not been removed.

**Comment by sutterseba** [comment]
> Users can still add it after the guidance process is completed

Currently, there seems to be no intuitive way to skip this guidance workflow without either creating or importing a new hot keystore. This could prompt users to import their hardware wallet keystore manually, which would be dangerous, or cause confusion after creating a new keystore.

If not all compatible hardware wallets are added to this menu, there should at least be an option to skip the workflow to get back to the normal workflow to add an address.
