### ISSUE TITLE
Network Etherlink is not working

### ISSUE THREAD

**Issue by vch9** [RabbyHub/Rabby#2684]
Hey, I have been trying to use Etherlink on Rabby to do simple transfers but it is not working. I don't know whether this comes from the Etherlink public endpoint or somewhere in Rabby.

When I get to the signature page, I'm getting an error both on Chromium and Firefox.

On Chromium I'm getting a JSON decoding error:
![image](https://github.com/user-attachments/assets/9a978d6f-ad3b-4c96-a224-d5e281909b9e)

On Firefox it is just saying "Gas balance is not enough" (which I believe is not root issue, but perhaps a consequence of a bug)
![image](https://github.com/user-attachments/assets/f8d254a3-d082-41c7-9446-1934fb05590d)

I have been trying to look at the logs to see where the issue was located, but I think it happens in the backend API:
![image](https://github.com/user-attachments/assets/defa11f7-d468-4470-b4db-dfaf4ae982fc)
![image](https://github.com/user-attachments/assets/8287bfab-f3b0-44d0-8436-707f58df6fa8)

The transactions on this network are really cheap so if you cannot reproduce I can probably spare you some tokens so you can test

**Comment by vvvvvv1vvvvvv** [comment]
fixed now
