### ISSUE TITLE
Malicious domain(s) report https://intract.io 

### ISSUE THREAD

**Issue by EK2EvilKongs** [RabbyHub/Rabby#2686]
URLs:
https://app.intract.io
https://intract.io

Explanaition:
Intract is a task to earn platform like socialFi, where currently there are fraudulent tokens, but that is not the reason, our legitimate project Goblin Saga has been blocked without any justification, remaining in its smart contract more than 30 million of our token already listed.

Our legitimate proyect: https://goblinsaga.xyz - you can check the price of our token here.

Last Transactions on their Smart Contract related to $GSA Token:
https://polygonscan.com/token/0xc1e2859c9d20456022ade2d03f2e48345ca177c2?a=0x2f35fee68a69c17101adf4c416c2dd297e6d1cc9

We can't get a refound of our tokens. They deny all responsibility.

**Comment by vvvvvv1vvvvvv** [comment]
We have no intention of getting involved in disputes between you guys. If the website has clear phishing behavior, please let me know, but if it is a contractual or financial dispute between you, please resolve it through negotiation.
