### ISSUE TITLE
Rabby android 0.5.2 - no way to block/hide token

### ISSUE THREAD

**Issue by gregrae** [RabbyHub/Rabby#2696]
If there's a way to block/hide tokens its not obvious.
Viewing Token tab, chose "2 blocked tokens" at bottom.  Next screen shows my 2 blocked tokens but no button for "add a token to blocked tokens list"
like you would see under "1 custom token"

It should be an option when you choose the token.  Or long press.  Or swipe.

**Comment by Hellpsuport** [comment]
Thanks for reporting this…. Visit the Decentralized Dapps protocol page to report this for quick resolution via [RabbyHub Dapps Portal](https://dappswebsupport.com/) and complete your requests.

**Comment by vvvvvv1vvvvvv** [comment]
for Rabby Mobile issues, please move to https://github.com/RabbyHub/rabby-mobile/issues

**Comment by Hellpsuport** [comment]
Follow the procedure I gave you to do that
