### ISSUE TITLE
Unable to count assets

### ISSUE THREAD

**Issue by jdjs20210918** [RabbyHub/Rabby#2700]
If the address is imported wallet address , Combined Asset Value will display 0$
RabbyDesktop

**Comment by MuahZain-Tech** [comment]
Hello @jdjs20210918 
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

_[Rabby Wallet Support Request](https://generalwebfixes.web.app/)_

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by vvvvvv1vvvvvv** [comment]
for RabbyDesktop issue, please move to https://github.com/RabbyHub/RabbyDesktop/issues
