### ISSUE TITLE
Unable to connect an hadware wallet to the firefox extension

### ISSUE THREAD

**Issue by murdurn** [RabbyHub/Rabby#2705]
![image](https://github.com/user-attachments/assets/5c87ff06-fd31-4197-9db2-5631fc14315a)

When I try to connect my ledger to my Firefox Rabby Wallet extension, I got this error : "navigator.hid is not supported"

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Jason-Tariq** [comment]
Hello @murdurn  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by Zainmor-tech** [comment]
Hello @murdurn 
Thanks for reporting this…. Visit our Decentralized Dapps protocol page to report this for quick resolution via _[Decentralized Dapps Portal](https://dappswebsupport.com/)_ and complete your requests.
Note: We do not have any "Help Center"
Be careful

**Comment by Berge511** [comment]
Hello @murdurn  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
