### ISSUE TITLE
Default gaslimit for "Send" token feature on Rabby wallet.

### ISSUE THREAD

**Issue by kur0** [RabbyHub/Rabby#323]
It seems currently when doing token transfer on Rabby, there is no gas limit preset on it (as there is no dapp to set one )
Is it possible to put a preset on it ( at least for the popular chains) 
(I have not check but should the EVM chains share simiar gaslimit for simple operation like token transfer?)

**Comment by vvvvvv1vvvvvv** [comment]
for native token: gasLimit will be fixed 21000
for non-native token: Rabby will estimate the gasLimit in-time(may difference for each token)
not sure why you prefer to "preset" the gasLimit?

**Comment by riordant** [comment]
this is still a problem - some exchanges require higher gas limits to be set when sending the native token to their deposit contract (eg. Deribit requires 100k gas over the usual 21k), so accomplishing this with the native token send in Rabby is not possible
