### ISSUE TITLE
Support for signTypedData_v4 (1inch limited order)

### ISSUE THREAD

**Issue by skygunner** [RabbyHub/Rabby#340]
The signing of a limit order in your wallet failed. Please, use another wallet that supports the method signTypedData_v4

**Comment by vvvvvv1vvvvvv** [comment]
![image](https://user-images.githubusercontent.com/86296331/141935871-d1adac68-3843-4af4-bd80-050c1983f6f1.png)
Just tried limit order in 1inch, it works fine in my side, how can I reproduce your issue?

**Comment by vvvvvv1vvvvvv** [comment]
Will close since can't reproduce
