### ISSUE TITLE
The language is chinese

### ISSUE THREAD

**Issue by Pheromon** [RabbyHub/Rabby#349]
I installed the extension on chrome (not yet available on other browsers, right?) but I can't understand anything because the welcome screen, the buttons and everything else is in chinese.

Is there a way to switch the language to english?

**Comment by vvvvvv1vvvvvv** [comment]
You can switch it in Setting page
![image](https://user-images.githubusercontent.com/86296331/142806401-ab8c1a3b-ade1-4dea-b57f-00bdbf08294e.png)

![image](https://user-images.githubusercontent.com/86296331/142794872-53cb8929-c93f-407f-a37b-758a8fc80598.png)

**Comment by Pheromon** [comment]
The problem is arriving there: I'm stuck at a page where it asks me some information that I don't understand what are they about
![image](https://user-images.githubusercontent.com/29581654/142820931-03fc795c-e5cf-4c42-92c7-8130bcfd9819.png)
