### ISSUE TITLE
Transactions stuck in pending on Polygon

### ISSUE THREAD

**Issue by mightyguava** [RabbyHub/Rabby#361]
I've encountered several times where transactions got stuck in pending on Rabby with Polygon. The transactions themselves were confirmed in Polygon. Only Rabby thought they were pending. The only way to clear them was to uninstall the extension. An example below

![image](https://user-images.githubusercontent.com/2769275/144144182-0a8db2b5-18f3-43d3-b982-2db121c57ec7.png)

I think of the times were when gas prices were fluctuating quite a bit on Polygon.

**Comment by vvvvvv1vvvvvv** [comment]
should be fixed now, please try again

**Comment by mightyguava** [comment]
Yeah, seems to be working now, thanks!
