### ISSUE TITLE
EIP-2612 Causes Rabby to get stuck on message signing

### ISSUE THREAD

**Issue by 0xRektora** [RabbyHub/Rabby#377]
Bug discovered on Abracadabra borrowing. On Metamask it should open a signing popup if not already, then the actual transaction. On Rabby it get stuck on the message signing indefinitely, which causes the next transaction to never be shown.

**Comment by vvvvvv1vvvvvv** [comment]
Please show me the reproduce step like:
1. which chain
2. which token deposit for borrow

tried Abracadabra but didn't find a EIP-2612 approve signing
