### ISSUE TITLE
Data doesn't populate on GMX / Arbitrum

### ISSUE THREAD

**Issue by vying1** [RabbyHub/Rabby#387]
At https://gmx.io/earn on Arbitrum, when using Rabby + a Trezor, none of the data loads - fields show ($...).  I have tried disconnecting / reconnecting GMX, switching networks to something else, then switching back to Arbitrum, and removing / reinstalling Rabby.  Did not resolve the issue.

However, using Metamask instead immediately resolves the issue.

**Comment by vying1** [comment]
GMX has started working again.  Nevertheless, I have had sustained periods of time where Rabby has been unable to make a connection where Metamask has.  

Another example is Alpha Homora v2 on Avalanche.  I have had times where Rabby repeatedly cannot prepare the transaction - "data fetch failed".  Using Metamask instead works every time.  Is there some kind of network endpoint Rabby uses that could be unreliable?

**Comment by vvvvvv1vvvvvv** [comment]
> I have had sustained periods of time where Rabby has been unable to make a connection where MetaMask has

Would you like to list them then we can check one by one?

> data fetch failed

Can you make a screenshot next time? Not sure where this error message shown, if in "Balance Change" section, it's expected and you can just ignore it and submit the transaction

**Comment by vying1** [comment]
I haven't had the issue reoccur for the past few days.  I'll reopen if needed, thanks.
