### ISSUE TITLE
BitBox02: Address selection bug

### ISSUE THREAD

**Issue by jadzeidan** [RabbyHub/Rabby#388]
When selecting an address from the BitBox02, there is a bug where if you select an address in the list, it will select the one above. For example if you select the second address, it will select the first address. In addition, the numbering of the addresses starts with the second address, not with the first. Please see the image below:

![image](https://user-images.githubusercontent.com/42831937/144895221-ed65fc90-e20d-4580-8c5d-da90991bb06d.png)

**Comment by rabbyOnTheMars** [comment]
fixed in https://github.com/RabbyHub/Rabby/pull/389
