### ISSUE TITLE
BitBox02: Change icon to official logo

### ISSUE THREAD

**Issue by jadzeidan** [RabbyHub/Rabby#391]
I notice the icon used for the BitBox02 hardware wallet is the twitter logo. This is not actually the official logo, it's just used for social media :D 

![image](https://user-images.githubusercontent.com/42831937/145017053-fc7a35fe-df16-49b1-b498-a5632e96256d.png)

Here are different sizes of the official logo you can use:

![bitbox02-160](https://user-images.githubusercontent.com/42831937/145016766-cc141d89-7e24-4088-ba02-1366165a1e88.png)
![bitbox02-48](https://user-images.githubusercontent.com/42831937/145016854-efe04f00-332d-4c4b-999e-a45cd337aeb7.png)
![bitbox02-24](https://user-images.githubusercontent.com/42831937/145016862-7149704d-831e-4f68-8926-8cc424cd077b.png)

Thanks

**Comment by vvvvvv1vvvvvv** [comment]
Will update in next release
