### ISSUE TITLE
Rabby override suggested gas settings

### ISSUE THREAD

**Issue by Utone** [RabbyHub/Rabby#392]
I'm getting a remove funds tx stuck on BSC ApeSwap pool that was assigned to use 1 gwei.

[as seen in a beefy issue somewhere earlier]

I sent a new tx with 5.2 gwei and cancelled the previous one  you can see the time difference 38 minutes...  

The new tx was instant when the previous was cancelled. 
Also curious how Rabby processes pending tx MM could have one stuck holding up many waiting "pending" tx that should /could be ran parallel instead of serial so we can assign priority for 
-dynamic or user per type set gas for some tx types. 
(a user on ETH  chain preferring low for overnight tx, (* TIP: limit orders do not pay gas on ETH)

![Screen Shot 2021-12-08 at 02 08 45AM](https://user-images.githubusercontent.com/5865016/145131627-3ea64107-8674-4dd5-840a-0c8cd403f701.png)
![Screen Shot 2021-12-08 at 02 22 11AM](https://user-images.githubusercontent.com/5865016/145131629-caf39eb3-16c2-4250-bfa7-4ee8aa763e5b.png)

Same on deposit tokens:
manually adjusting this takes too much of my time.[=money]
![Screen Shot 2021-12-08 at 02 39 39AM](https://user-images.githubusercontent.com/5865016/145133660-4e626ee1-90f2-492c-9835-f1f8802af09f.png)
![Screen Shot 2021-12-08 at 02 42 19AM](https://user-images.githubusercontent.com/5865016/145133661-b2086b71-97b3-4bff-aa6d-450645c3c0c8.png)

**Comment by Utone** [comment]
Will play around with a few tx to see if we can already prioritize in parallel (if one pending holds the que or not)
curious how Rabby gets 1gwei as I've not seen such low settings in MM

**Comment by Utone** [comment]
Early but stating the obvious anything below 5 Gwei will clog the pipes.
![Screen Shot 2021-12-08 at 03 04 38AM](https://user-images.githubusercontent.com/5865016/145135571-eb58b43c-a511-4c46-9c51-f25adb1fa3f3.png)
..

**Comment by vvvvvv1vvvvvv** [comment]
This 1 Gwei is set by dapp and obviously not make sense, so we have a new feature in v0.17.0:
1. Rabby will ignore the gasPrice set by dapp
2. Rabby will cache the last time gasPrice/gasPrice level you selected
3. So next time when you submit a transaction Rabby will use the last time value as default(i.e. if you set gas to 5 Gwei in custom field, then the default gas is 5 Gwei, if you set gas to the fast level, then the default gas is fast level and use the real-time fas gasPrice)

This version is released and waiting for audit of Chrome Store, should be release soon
