### ISSUE TITLE
From dissonance to synergy_ultimate dApp helper wallet interface? A workflow challenge, perhaps better off in stages before merging two different challenges: Portfolio user customization / Wallet has potential for innovation + improvements. 

### ISSUE THREAD

**Issue by Utone** [RabbyHub/Rabby#393]
## Example:

On deBank a token like $GNANA will not be included due to no (official LP (the little one on pcs is a very odd fluke and its existence makes zero sense..)

All my GNANA and yield in various token emissions are not listed so would need a custom add token, is this saved on debank servers or locally? (will tedious repetitive tasks like MM custom token contracts be erased on clearing browser cache??)

OK I'll try to emphasize the huge "pandoras hellbox of an unattainable universal all protocol perfect" 
Portfolio vs the lesser evil id say benign challenge of a Wallet:

 -# THIS GNANA shit can be skipped to next comment but is a valid issue in itself  #--
 
 Golden Banana $GNANA does not have an official LP pairing.   It is a much used part of the ecosystem  
A 'Banana 'purified' with a 28% burn fee and a 2% reflect fee which is distributed as free GNANA airdropped to all (un-staked) GNANA in wallet holders, used for:
-governance
-stake to earn exclusive tokens in higher APR 'syrup' pools.
-participate and pay in IAO's

It's value differs across boards [using the PCS LP is most definitely going to show erroneous values] 
There is an official calculation based on BANANA price.. somewhere...in ape swap docs..

If my GNANA is ~ 50% of holdings it better show up on my dash ..;)
##found it after comparing between several asset tracking products NONE of them do all of the few things im in but reference more than 4 portfolios, ape-boards and what not.. to get a few parts together. ##
 
from ape swap docs:

The GNANA does not have a price nor will we open up a trading pair or farm for it. Its core utility will be the functions outlined above. 

GNANA's makeshift "price" is referenced in two places: 
1 - Initial Ape Offerings, where GNANA would be valued at 1.389x the current BANANA price.
2 - GNANA Staking pools, where the $ value staked of GNANA is based on the amount x 1.389 the BANANA price. 
Please note this factors into the APRs!

Not really 'the point' here at all but to illustrate. the following down below____________

**Comment by Utone** [comment]
Not sure about calculation recall something different than banana* 1.39024....but... both 
Ape Swap and YieldWatch show same stats: 
BANANA @ $1.23 
GNANA @ $1.71

Not really 'the point' here but a part of a broader workflow issue in general.  
Where you either make the landing page fully customizable (like walletnow) or at least 
Present a choice to use the extension as a wallet 
-instead of a signing app for DeBank 
=Great if you want a portfolio tracking service 
NOT if you just want a snappy wallet experience..

Which as far all Portfolio Ape/dashboards isn't going to be perfect.
It will require lots of updates to facilitate every protocol or User customization in MUCH greater detail vs a Wallet. 

Instead of adding token contracts (for portfolio level vaults etc but it won't be a panacea) 

Custom token support is still lacking even in MM still super annoying 
Here you could add a user token list  (grab the token code from state logs) in -export to json [basically plain text]

Backup, migrate or restore all tokens would make tons of users happy. TrustWallet has a huge token repo here too easy to fork.

**Comment by vvvvvv1vvvvvv** [comment]
check the latest v0.19.0
