### ISSUE TITLE
Ledger disconnected, no user message

### ISSUE THREAD

**Issue by antonio-fr** [RabbyHub/Rabby#395]
When the app is running and using with a Ledger, it doesn't catch when the Ledger is disconnected. And more importantly for the UX, when the user makes a transaction, there is not a single message anywhere explaining the need for a Ledger.
The Rabby panel appears, displaying the tx info, and once the user confirms the transaction, nothings popup, nothing proceeds. Rabby, at best is silently waiting for a Ledger. At worst it's silently throw an exception because of the missing Ledger.
The user has to lock its Rabby and connect again with a Ledger.
 
At least add a dedicated clear message asking the user to reconnect hes Ledger. also it can lock itself when it detect there is no more a Ledger connected.

**Comment by vvvvvv1vvvvvv** [comment]
Try the latest release(v0.26.0), now you can get the feedback when sign with Ledger
