### ISSUE TITLE
Polygonscan not connecting

### ISSUE THREAD

**Issue by gasperbr** [RabbyHub/Rabby#397]
Cannot connect to polygonscan.com with my Rabby wallet. Can something be done? I realize this is something that probably should be resolved by the Etherscan team since other websites work as expected.
![image](https://user-images.githubusercontent.com/42702599/145561167-a4a73fce-dadd-4adc-ac4a-b5f1e5846bd4.png)
(no popup happens after the alert shows up)

**Comment by vvvvvv1vvvvvv** [comment]
![image](https://user-images.githubusercontent.com/86296331/145774466-a0f66626-a982-4314-99e1-d98579056d49.png)
Click "Add Polygon Network" at the bottom of the page then will works, it's known issue with etherscan
