### ISSUE TITLE
Send feature not available in version 0.17

### ISSUE THREAD

**Issue by marciuz** [RabbyHub/Rabby#400]
In the version 0.17 the Send functionality seems not more available. 
I presume it's an issue, not a feature.

**Comment by vvvvvv1vvvvvv** [comment]
Send functionality just offline temporary and will back in future, you can use Send function in https://app.zerion.io/ or https://zapper.fi/ for instead.
If you use Send to see your token balance, no worry because token balance in home page is coming soon

**Comment by celo-no** [comment]
ok, a tried to use zapper but i did a swap from avax to BNB, on avax network. Now my wallet does not recognize the BNBs (although on zapper the BNBs appear). How can i reverse this operation and have the avax tokens back?

**Comment by marciuz** [comment]
The issue affect also the new version 0.18

**Comment by vvvvvv1vvvvvv** [comment]
We are re-designing the Send feature, will back soon

**Comment by vvvvvv1vvvvvv** [comment]
check v0.20.0, Send is back
