### ISSUE TITLE
Withdrawl from Rabby - AVAX and BNB

### ISSUE THREAD

**Issue by celo-no** [RabbyHub/Rabby#407]
I am trying to find a way to withdrawl my tokens from rabby and it is being a hard work. Zerion does not support Avalanche network and Zapper does not have a send function. How can we withdrawl our funds from Rabby?

**Comment by integer-underflow** [comment]
Zapper has send function. First, you need to add the recipient address in `Address Book`, then click it and you should see the button for sending token to that address

<img width="852" alt="image" src="https://user-images.githubusercontent.com/2921893/147022123-203c7a6e-96d9-446a-8d3b-e245ddd002e8.png">

**Comment by vvvvvv1vvvvvv** [comment]
duplicated with #400
