### ISSUE TITLE
Critical Bug! SEND button gone ...

### ISSUE THREAD

**Issue by roleerob** [RabbyHub/Rabby#412]
Version: 0.18.0

Waking up this morning to complete a transaction with Rabby and the SEND button is gone!?  Hard to imagine a more basic function to your wallet, to ensure does NOT disappear than this one!?

Please investigate and restore this functionality ASAP!  Until then, I have no choice but to disable and return to my use of MetaMask ... 👎

**Comment by vvvvvv1vvvvvv** [comment]
duplicated with #400
