### ISSUE TITLE
Ability to change wallet password

### ISSUE THREAD

**Issue by PandaWhisperer** [RabbyHub/Rabby#420]
Currently, it appears to be impossible to change the wallet password once it's been set up. I looked in the settings screen and found no option for it there. There isn't even an option to reset the extension.

It appears the only way to change the password reinstalling the extension and adding all your accounts from scratch.

**Comment by vvvvvv1vvvvvv** [comment]
This will cause security issue.

1. Rabby didn't know your password actually
2. when you set your password, Rabby use your password to encrypt your sensitive account information(private key, mnemonic word, etc.) 
3. every time you unlock the wallet Rabby just use the password to try decode the data

So Rabby don't know your password and can't let you change it

**Comment by PandaWhisperer** [comment]
That's fine, and actually what I expected, but isn't it possible, given the existing password and a new password, to decrypt the wallet and then re-encrypt it with the new password? 

Also, if you're not going to fix it, it would be helpful to at least point this out in the setup screen that it can't be changed later.

**Comment by vvvvvv1vvvvvv** [comment]
> That's fine, and actually what I expected, but isn't it possible, given the existing password and a new password, to decrypt the wallet and then re-encrypt it with the new password?

Yes it's possible, but it's danger in both technically and user interaction, if there is any bug means user will lost privatekey or mnemonic

> Also, if you're not going to fix it, it would be helpful to at least point this out in the setup screen that it can't be changed later.

Will think about it, thanks

**Comment by Zaczero** [comment]
> Yes it's possible, but it's danger in both technically and user interaction, if there is any bug means user will lost privatekey or mnemonic

It shouldn't be difficult to make a properly working password change feature.

> Rabby didn't know your password actually

I am quite surprised from what I'm reading here, this is just false ([look](https://github.com/RabbyHub/Rabby/blob/81c85654f1d2ff589a1b96f12c02044cfbd98ecd/src/background/service/keyring/index.ts#LL119C30-L119C30)).

> if there is any bug means user will lost privatekey or mnemonic

But a seed phrase can easily recover that.

---

Pseudo code:

```py
# currently implemented in some form:
data = decrypt(read_storage(), user_pass)

# new code:
write_storage_temp(encrypt(data, new_user_pass))

# extra validation for safety:
data2 = decrypt(read_storage_temp(), new_user_pass))

if data == data2:
  accept_storage_temp()
else
  raise 'Integrity validation failed'
```
