### ISSUE TITLE
Loopring: Unable to deposit and activate layer 2

### ISSUE THREAD

**Issue by haykkh** [RabbyHub/Rabby#468]
Hi there, I've successfully connected my wallet to loopring, but am having difficulties depositing and activating layer 2. I've tried a few times and keep on getting the error seen below. All the data in the raw tx seems correct (to my untrained eye), except for nonce which is `0x0`

<img width="397" alt="Screen Shot 2022-01-08 at 18 59 18" src="https://user-images.githubusercontent.com/5832225/148649045-5ddfb742-bf68-451e-b1d0-141dd6f2499a.png">

**Comment by vvvvvv1vvvvvv** [comment]
How can I reproduce this issue? works fine in my side
