### ISSUE TITLE
Cannot read properties of undefined (reading 'find') on preference.getHiddenAddresses

### ISSUE THREAD

**Issue by kiwibrowser** [RabbyHub/Rabby#470]
Issue originally reported by: autodefier@gmail.com

After the basic setup: neither dialogs nor the main extension UI finishes loading, hangs on white screen in first case, infinite loop for the main UI/dashboard of the extension.
When investigating the background page of the extension, an error is reported at the following line:
https://github.com/RabbyHub/Rabby/blob/481b75bf25ebd861b6b383b6c8a731aa00e50c48/src/background/service/keyring/index.ts#L902

- Platform: Kiwi Browser ( https://github.com/kiwibrowser/src.next/releases ) or https://play.google.com/store/apps/details?id=com.kiwibrowser.browser&hl=en&gl=US

Reproduction:
Install Kiwi Browser
Just create any password and add any address for a Watching wallet.
<img width="1406" alt="Screenshot 2022-01-09 at 01 26 12" src="https://user-images.githubusercontent.com/40272275/148679264-87e43b11-35f1-4bd1-8936-78d0fe0163dd.png">

The cause is because preference.getHiddenAddresses is returning an undefined value.

**Comment by vvvvvv1vvvvvv** [comment]
fixed in https://github.com/RabbyHub/Rabby/releases/tag/v0.20.1 under auditing of Chrome Web Store team

**Comment by kiwibrowser** [comment]
Thank you very much, you are awesome!

I will forward the result to the user.
