### ISSUE TITLE
Add 2nd Wallet with mnemonic words

### ISSUE THREAD

**Issue by f0o** [RabbyHub/Rabby#482]
Right now you can only add your first wallet with mnemonic words - any subsequent wallet must be added via private key..

Please allow adding additional wallets through mnemonic.

**Comment by vvvvvv1vvvvvv** [comment]
![image](https://user-images.githubusercontent.com/86296331/149699033-31fdf837-bdae-41e5-a131-63b63543d516.png)
Just click "Create New Address"

**Comment by f0o** [comment]
That creates a new Address. I want to Add/Import an additional Wallet with words. I'm forced to use Import by Private Key after adding the 1st wallet.

Reopen please

**Comment by f0o** [comment]
@vvvvvv1vvvvvv - Your answer didnt even relate to the Issue/Feature Request. Please reopen or show how I can add 2 or more mnemonic Wallets.

**Comment by vvvvvv1vvvvvv** [comment]
If you mean create a new address via the same mnemonic, just follow my prev answer
If you mean import another mnemonic, Rabby currently not support, then I will reopen the issue

**Comment by f0o** [comment]
The latter. Thanks

**Comment by hjklcc** [comment]
+1

**Comment by Divaltor** [comment]
+1

**Comment by antonio-fr** [comment]
What I'm doing for this case :
Use [Uniblow](https://uniblow.org/get) SeedWatcher, input mnemonic, scan, open an address in wallet.
Then connect Uniblow wallet with WalletConnect to Rabby, for example importing Fireblocks (to have the walletconnect system).

This way, one can use Rabby as a Web3 wallet, and use a temporary mnemonic easily. Rabby is used like a dapp to the wallet.

**Comment by vvvvvv1vvvvvv** [comment]
multi mnemonic words is supported now
