### ISSUE TITLE
[Feature Request] Custom chains / Testnet

### ISSUE THREAD

**Issue by Amcolex** [RabbyHub/Rabby#483]
I'd first like to thank you for this awesome plugging. I've been using metamask and find Rabby to be a net improvement!

One key missing feature that I often use though is testnets. So the feature request is pretty simple:

Allow the user to add a custom chain, similar to how it's done in metamask.

I get that rabby is trying to be super user friendly, and testnets are an advanced feature rarely used by the general public, so maybe it can just be hidden in the advanced settings pannel, etc?

**Comment by vvvvvv1vvvvvv** [comment]
duplicate with https://github.com/RabbyHub/Rabby/issues/261
