### ISSUE TITLE
Cannot setup ledger device

### ISSUE THREAD

**Issue by Tavo22** [RabbyHub/Rabby#522]
It is not possible to add a ledger device.
I tried chrome and brave.
Device mac.

Working fine in metamask

![image](https://user-images.githubusercontent.com/2164675/151429228-b9a6a973-9211-4f60-83a2-507678b6f154.png)

**Comment by vvvvvv1vvvvvv** [comment]
Please make sure your Ledger Live App not open same time, this two use same USB channel will cause conflict

**Comment by Tavo22** [comment]
Thanks for your reply.
I tried both methods. Through the ledger live app and direct connection (with the live app closed). Both got me stuck at the same place.

I am able to get the addresses but after selecting one it is not moving forward.

**Comment by mrgrauel** [comment]
I have the same issue.

**Comment by vvvvvv1vvvvvv** [comment]
going to use WebHID instead of WebUSB for Ledger

**Comment by 0xthrowaway** [comment]
I have the same problem, but if I try enough times it works.

@vvvvvv1vvvvvv 
Thanks for your reply.

Are you sure this is a WebUSB issue? Rabby is able to get the addresses successfully from Ledger. The wizard gets stuck only after I choose an address. Also, after an address is added successfully, Rabby works flawlessly.

**Comment by vvvvvv1vvvvvv** [comment]
We optimized Ledger import and sign process in the latest release (v0.26.0), you can try it and kindly reply if still have issue like this
