### ISSUE TITLE
Sushiswap in polygon network

### ISSUE THREAD

**Issue by Tavo22** [RabbyHub/Rabby#524]
Tokens list is not loading in sushiswap for polygon network.
I tried sushiswap in avalanche or other networks and seems to be working fine. I also tried with metamask and working without any issue.

![image](https://user-images.githubusercontent.com/2164675/151686446-75d4ea10-5317-40ee-8f6c-dbbb76e0d69f.png)

**Comment by vvvvvv1vvvvvv** [comment]
fixed now, just retry
