### ISSUE TITLE
Not working in Vivaldi

### ISSUE THREAD

**Issue by hypefiasco** [RabbyHub/Rabby#525]
Fresh install of Vivaldi and Rabby and all that happens is a black screen pops up for half a sec and the connection fails.

Fresh install of Chrome and Rabby and everything works fine.

**Comment by vvvvvv1vvvvvv** [comment]
Works fine on Vivaldi in my side, how can I reproduce your issue?

**Comment by vvvvvv1vvvvvv** [comment]
Close since can not reproduce
