### ISSUE TITLE
Cancel Polygon transactions

### ISSUE THREAD

**Issue by a1termoon** [RabbyHub/Rabby#527]
I can't cancel transactions. Now I'm paralyzed. 
![1](https://user-images.githubusercontent.com/58614810/153200903-9a879ca1-c9e2-4cb9-a5f1-b67356e9d585.jpg)

**Comment by vvvvvv1vvvvvv** [comment]
Please check your nonce(last transaction on pylogon scan)
<img width="742" alt="image" src="https://user-images.githubusercontent.com/86296331/153543538-f61170c9-46d6-44e5-be41-f54164fd2c45.png">
If your nonce is 1, then submit a new transaction from dapp and set nonce to 2

**Comment by vvvvvv1vvvvvv** [comment]
There is a "Reset Account" in 0.21.3 release, you can use it to clear stuck pending transactions
