### ISSUE TITLE
Non Chrome Based Browser Support

### ISSUE THREAD

**Issue by carterlasalle** [RabbyHub/Rabby#528]
Add support for Firefox and other non-chrome based browsers

**Comment by Olyno** [comment]
Hi 👋🏻 I tried to use Rabby with Firefox (v102.0b3), and it looks like a charm so far. I will make more tests with the extension using different dapps, and report any issue i found here.

If there is no specific issue with it, i guess it could be a good idea to publish it on the Firefox add-ons store.

**Comment by Philippe734** [comment]
Could you make a release for Firefox? What we can do to help to create it?

**Comment by rootedetc** [comment]
Is there a plan for releasing a Firefox version?

**Comment by Philippe734** [comment]
What can we do to help to create this release?

**Comment by Philippe734** [comment]
Nope... 2 years ago...
[https://twitter.com/Rabby_io/status/1419985324885700610](url)
![2023-03-13_16-27](https://user-images.githubusercontent.com/24923693/224748392-bf91f820-6960-4b15-aaeb-b7f8dff1f5ac.png)

**Comment by rootedetc** [comment]
It seems like they gave up completely.
Would be cool of them to at least acknowledge this issue though.

**Comment by dylankilkenny** [comment]
bump

**Comment by dylankilkenny** [comment]
also interested in this

**Comment by Clean42** [comment]
wen pls

**Comment by Philippe734** [comment]
As Metamask is no longer works with Firefox on Linux, Rabby don't works and as the last wallet works on this combo is Frame, then please, don’t abandon us

**Comment by marek22k** [comment]
Is there any news regarding this feature?

**Comment by Leechael** [comment]
Can we revisit this issue?

**Comment by Polve** [comment]
This is the only extension I miss to use firefox for everything.

Please support it: what is the problem? Technical issues?

**Comment by jummy123** [comment]
:+1:  would appreciate a firefox wallet

**Comment by paulperegud** [comment]
Gents, Firefox is a great browser. Please add support :-)

**Comment by blksw4n** [comment]
Please add support for Firefox. MM supports it. You should support it if you want to be most competitive! Thanks.

**Comment by alexx-ftw** [comment]
I would love Firefox support. Would be a pretty good differentiation factor

**Comment by gionn** [comment]
Please just add a reaction to the first post to +1 - no need to spam every issue subscriber with a meaningless comment.

**Comment by janbsw** [comment]
Also vouching for Firefox support in the future.

**Comment by peixotons** [comment]
I hope for a Firefox support in couple years .-.

**Comment by Pheromon** [comment]
what is the problem exactly in porting the app to firefox?
I though the extension structure and code would be mostly the same, nowadays.
I'd like to know a few technical problems in detail

**Comment by antofa** [comment]
any updates?

**Comment by dylankilkenny** [comment]
This issue has been open for 2 years without response. At this stage I suggest anyone looking to ditch metamask but wants to continue using firefox to use [frame.sh](https://frame.sh).

**Comment by flajann2** [comment]
Maybe someone can fork the project and do a Firefox version. MetaMask totally sucks, so I am going to do crypto on the Brave browser. and Firefox for everything else. At least for now. Eventually I will start using Brave exclusively.

**Comment by Philippe734** [comment]
After almost 15 years of loyalty to Firefox only, I gave it up for this reason. I now use Brave with Rabby to preserve my funds safe. Wait and see or divorce Firefox, my choice was quickly made. I repeat, 15 years on Firefox...

**Comment by alexx-ftw** [comment]
There are many wallets other than Rabby. I refuse to use Brave or any other
crappy Browser

**Comment by Pheromon** [comment]
I want to try rabby but I'm not giving up firefox, sorry

**Comment by devsbestfriend** [comment]
+1 for the cause

**Comment by rhmaxdotorg** [comment]
Yes please add Firefox support, lots of people would like to use the wallet for their browser.

**Comment by wslyvh** [comment]
Ok, let's see if we can get attention this way. Putting up a bounty to support Firefox. This is long overdue!

I'll start with 500 USDC, and welcome others to pitch in!

https://www.bountycaster.xyz/bounty/0xf3486ff0d6ebf14235ab9dbcbe33593cdd861079

**Comment by badreddineelouarigli** [comment]
we need the extension,we need the extension , we need the extension pls ♥♥♥

**Comment by Mr-SciFi** [comment]
Any reason we can't get a firefox version?

**Comment by DPrimasso** [comment]
Need extension firefox please!

**Comment by nixorokish** [comment]
> Ok, let's see if we can get attention this way. Putting up a bounty to support Firefox. This is long overdue!
> 
> 
> 
> I'll start with 500 USDC, and welcome others to pitch in!
> 
> 
> 
> https://www.bountycaster.xyz/bounty/0xf3486ff0d6ebf14235ab9dbcbe33593cdd861079

added a couple bucks. this is absolutely necessary.

**Comment by Eleleth77** [comment]
commenting for vis. No one who cares about their privacy and data is using Chrome in the year of our Chain 2024.. cmon, please bless FireFox with this supposedly "great" wallet

**Comment by wrocketdev** [comment]
+1

**Comment by Philippe734** [comment]
It's time to shine spotlight on this file.
OK friends, let's go, together, create a bet on Polymarket: In what year will Rabby be available in Firefox?
If we can't use it with Firefox, then maybe we can earn money with this?

**Comment by bakeiro** [comment]
when firefox wallet 😭

**Comment by puzzle-rusher** [comment]
FIREFOX!!!

**Comment by iowoof** [comment]
bump this topic

**Comment by theBSH** [comment]
i need this!!!

**Comment by hack3r-0m** [comment]
dis before gta 6? rabby team seriously needs to re-consider this to gain more market share from metamask.

**Comment by dandepeched** [comment]
The only thing preventing me of switching from Metamask to Rabby is lack of support for Firefox. No way I will be using Chrome for any sensitive information.

**Comment by trader-payne** [comment]
Bump. Fuck chrome and google.

**Comment by Pheromon** [comment]
@trader-payne hell ya!

I can understand support only firefox and not chrome, but the converse makes no sense.

Can someone explain if there are some technical showstoppers in doing an extension that works on both browsers?
From what (little) I know the APIs are quite standard now and it should be straightforward to develop an extension for both.

**Comment by puzzle-rusher** [comment]
Guys, stop using chrome, it's a slow piece of shit

**Comment by Pheromon** [comment]
The problem it's not that it is slow, the problem is that it's just a honeypot for harvesting your private data.

**Comment by Philippe734** [comment]
To use Rabby, move from Firefox to Brave, as privacy concern is high as Firefox. Stop to ask Rabby for Firefox, we'll never got it. Use hardware wallet + rabby asap to protect your assets.

**Comment by ipha** [comment]
Firefox support is being worked on right now: https://github.com/RabbyHub/Rabby/pull/2568
Last commit was 2 hours ago.

**Comment by vvvvvv1vvvvvv** [comment]
resolved in https://github.com/RabbyHub/Rabby/pull/2568

**Comment by carterlasalle** [comment]
Thanks to everyone who upvoted! It's been a grind getting this done, but because of you, we have it now :)
🥇

**Comment by dandepeched** [comment]
Now you can installed from here - https://rabby.io/

**Comment by zotabee** [comment]
Looks like the firefox addon is gone from Mozilla store. Also no sign of it on rabby.io. 🤔

**Comment by zotabee** [comment]
Seems gone for good : https://x.com/Rabby_io/status/1925519050471288956

**Comment by dandepeched** [comment]
What a short-vision decision... Back to Phantom :(

**Comment by grayegret** [comment]
for reference the firefox build does work with minimal changes
https://github.com/RabbyHub/Rabby/compare/develop...grayegret:Rabby:develop you can build and test the install with firefox debug mode
the applets within the extension work, also you can sign into sites such as opensea etc

**Comment by Polve** [comment]
@grayegret thanks!
Would you be so kind to give a list of steps to manually build/update rabby for firefox for the few of us still stuck with the old version?

**Comment by grayegret** [comment]
@Polve Firefox has a security policy so extensions from outside the store don't persist by default, they are cleared after restarting the browser, so this is mostly for testing. But you could try testing with 
```sh
git clone https://github.com/grayegret/Rabby.git
cd Rabby
yarn
yarn build:pro:mv2
```
it will take several minutes to build

Then in Firefox: `about:debugging` you can open "This Firefox" then "Load Temporary Add-on" and select `manifest.json` from the `dist-mv2` folder. The extension will be loaded in the browser where you can set it up and use it.

Alternatively, if you are using Firefox Developer or Nightly, you can build the `.xpi` file with `npx web-ext build --source-dir ./dist-mv2` (after those earlier `yarn` commands). It will generate a file in `web-ext-artifacts/` with a name like `rabby_wallet-0.93.88.zip`; you can change the extension to `.xpi`. Set `xpinstall.signatures.required` to `false` in `about:config` and then [install addon from file](https://extensionworkshop.com/documentation/publish/install-self-distributed/), this would allow it to persist across sessions
