### ISSUE TITLE
Unable to connect wallet via Wallet Connect

### ISSUE THREAD

**Issue by 1mm0rt41PC** [RabbyHub/Rabby#536]
Step to reproduce:
1) `+ Add addresses`
2) Select `Trust Wallet` or any wallet type with wallet connect 
3) The qRcode use by default the bridge url `https://wcbridge.rabby.io`
4) Scan the qRcode with https://play.google.com/store/apps/details?id=com.frontierwallet or with any wallet with wallet connect.
=> You will get an error.

To avoid the error, it's actually possible to change the bridge server to the official server `bridge.walletconnect.org` (see https://docs.walletconnect.com/bridge-server)

Is there a raison to use the bridge of rabby ? Is it possible to set the default server to the official one?

The code to change is on this line
https://github.com/RabbyHub/Rabby/blob/e2bb32d800990bebf79dcf1fff0593b1d1d7ff8e/src/ui/views/ImportWatchAddress.tsx#L98

**Comment by vvvvvv1vvvvvv** [comment]
Will change to official server in next release
