### ISSUE TITLE
Gridplus Lattice1 wallet has no way to change derivative path

### ISSUE THREAD

**Issue by Proteus7** [RabbyHub/Rabby#576]
There is no way to add a legacy ledger/MEW path (m/44'/60'/0'/x)  address to a Gridplus Lattice1 wallet.

**Comment by Proteus7** [comment]
Any update on this? Not really useable on Lattice without it :(

**Comment by rube-de** [comment]
I also can't use my lattice1 without it :(
why is it only implemented for ledger?

**Comment by vvvvvv1vvvvvv** [comment]
supported in v0.92.3
