### ISSUE TITLE
Gridplus Lattice1 shows error on Avalanche chain with TraderJoe, Pangolin,etc

### ISSUE THREAD

**Issue by Proteus7** [RabbyHub/Rabby#577]
Received the following error consistently when attempting swap on TraderJoe and Pangolin on Avalanche with Gridplus lattice1. Switching to ledger wallet, was not able to replicate problem. Lattice1 worked fine with metamask and same transaction.

"Swap failed: Error: The chain ID does not match the chain ID of Common (tx type=2 hash=error nonce=493 value=0 signed=true hf=error maxFeePerGas=undefined maxPriorityFeePerGas=undefined)"

**Comment by vvvvvv1vvvvvv** [comment]
fixed in #596
