### ISSUE TITLE
Adding an account/addresses within an existing seed

### ISSUE THREAD

**Issue by armaccloud** [RabbyHub/Rabby#593]
This request is to make it possible to add an address within an existing seed, instead of generating a new seed.
Within MM, this is called creating an (additional) account. It is then created within the same seed/mnemonic.

**Comment by vvvvvv1vvvvvv** [comment]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/86296331/157855136-1d027a45-b39d-4f93-bc80-75e4dd52edb3.png">
This will generate a new address within the existing seed

**Comment by twodam** [comment]
I still see this issue, everytime I create an address, it shows a new seed phrase.
<img width="339" alt="image" src="https://user-images.githubusercontent.com/103885077/220856001-143b77c3-2ab5-4ed2-9580-2cd305510afa.png">
