### ISSUE TITLE
Latest Update broke the ability to connect to some sites (BSC & Fantom Sites)

### ISSUE THREAD

**Issue by Verdugo** [RabbyHub/Rabby#610]
Before the most recent update (0.25.0) Rabby would ask what mainnet I wanted to connect to and remember them for the following sites. Now, every time I got to these sites and refresh, I get the error saying I need to connect to the sites. Some give me the error after I select Metamask as the wallet and some give me the error when I select the "connect to wallet" option.

I use Rabby through the Brave browser. 

https://app.samurai.financial/ (Fantom Network)
https://ozark.network/#wallet (BSC Network)

Again, I was able to connect to both sites without an issue and can still do using MetaMask using a different browser from the one that has Rabby installed on it.

**Comment by vvvvvv1vvvvvv** [comment]
Will contact with dev of these 2 teams to fix it
