### ISSUE TITLE
Option to hide a token

### ISSUE THREAD

**Issue by armaccloud** [RabbyHub/Rabby#621]
This request is for an option to hide a token.

**Use cases** 
A scam token suddenly appeared with a balance in my overview. I want to hide this token.
A token I sold the funds for, but only a few cents of value remains on it. The token stays visible, but I'd like to hide it.

**Comment by xuyong2022** [comment]
Which token do you think is scam, please give the chain and token contract address

**Comment by armaccloud** [comment]
This token appeared in my wallet. When I open their website, it automatically tries to contact to my wallet.

![image](https://user-images.githubusercontent.com/9272078/160281024-e2fb53de-5f52-439f-b483-e951623dc545.png)
**Contract**
0x69b14e8d3cebfdd8196bfe530954a0c226e5008e

**Comment by Miyabi999** [comment]
😘~~~~

**Comment by dcout** [comment]
+1 for this issue. Plenty of dust in my wallet, as well as this same scam airdrop.

An option to hide tokens with total value below a certain threshold would work nicely for dust.

**Comment by vvvvvv1vvvvvv** [comment]
You can block token now

**Comment by gregrae** [comment]
Rabby android - how to block/hide token?
