### ISSUE TITLE
Zero Balance

### ISSUE THREAD

**Issue by EVLRBT-01** [RabbyHub/Rabby#622]
It seems that Rabby maybe isn't returning the correct value of "0x0" for a zero balance, when calling eth_getBalance (as per https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1474.md#quantity)

![image](https://user-images.githubusercontent.com/60948618/160281953-ee0f5d97-fcfe-401d-84de-acdbe31a097f.png)

Testing the same code using Metamask returns the correct expected value:
 
![image](https://user-images.githubusercontent.com/60948618/160282083-976a9720-b170-4c30-97e8-35f3abe3ba7c.png)

PS - JsValue is a Rust wasm wrapper around a JavaScript value.

**Comment by vvvvvv1vvvvvv** [comment]
fixed now
