### ISSUE TITLE
Support for limited order feature on 1inch Polygon

### ISSUE THREAD

**Issue by skygunner** [RabbyHub/Rabby#691]
At the moment, it doesn't seem to understand the transaction

**Comment by vvvvvv1vvvvvv** [comment]
Can not understand what you mean, you mean can not create a limit order on 1inch?

**Comment by pax85** [comment]
Hi @vvvvvv1vvvvvv ,

if you want to reopen this case I can add some additional information.
Using Limit Orders on 1inch does work with Rabby.

What does not seem work is pulling the actual transaction information for limit orders.

This Screenshot is using MetaMask:
![Screenshot 2022-07-24 at 11 51 36](https://user-images.githubusercontent.com/7982498/180641797-e85514a4-5a28-49aa-87a1-a337e7fe9b36.png)

The Status column is filled with a progress bar.


This Screenshot is with Rabby. The Progress bar is not displayed
![Screenshot 2022-07-24 at 11 31 41](https://user-images.githubusercontent.com/7982498/180641826-75196dcc-5510-4632-a2f2-6753d7c1e531.png)
The actual executions do happen though. 

kind regards
