### ISSUE TITLE
Upgrade to Manifest V3

### ISSUE THREAD

**Issue by lmcmz** [RabbyHub/Rabby#703]
Hi, 

I have been trying upgrade the project to manifest v3. 
It seem like the ui and background got disconnected sometime, a lot of breaking changes. 

Is there any plan to upgrade it to v3 ?

**Comment by vvvvvv1vvvvvv** [comment]
Planing and no timeline for now

**Comment by studioTeaTwo** [comment]
Wen upgrade? :)

**Comment by vvvvvv1vvvvvv** [comment]
> Wen upgrade? :)

Est. early Oct

**Comment by Jo-Chris** [comment]
Is there a timeline for that issue? Deprecation 2023 as it stands

**Comment by vvvvvv1vvvvvv** [comment]
close since mv3 is on production now
