### ISSUE TITLE
Urgent: Conflicting Issue with MetaMask

### ISSUE THREAD

**Issue by faxotherapy** [RabbyHub/Rabby#759]
Hi, since installing the add-on Rabby, MetaMask can no longer connect to any dApp. MetaMask no longer responds when clicking on the “Connect Wallet” button from any dApp website. MetaMask somewhat becomes a “dead” extension. This is because of the Rabby extension. It tooked me 2 hours to find the culprit. After uninstalling Rabby, MetaMask now works. I have reinstalled Rabby, and again MetaMask no longer connect to any dApp!

**Comment by AlbertChanX** [comment]
It seems that Rabby is the competitor to Metamask.
