### ISSUE TITLE
Better display for EIP-2612 signature request

### ISSUE THREAD

**Issue by wrap-that-potassium** [RabbyHub/Rabby#770]
Instead of the default `signTypedData` display, it would be best to switch to something more similar than what's done for `approve` transactions, so that the user can edit at least the amount and the deadline.

**Comment by vvvvvv1vvvvvv** [comment]
https://twitter.com/Rabby_io/status/1595023587316228096
https://twitter.com/Rabby_io/status/1587416889159983107
We currently support permit and list order on some NFT marketplace, you can try it again
