### ISSUE TITLE
Wrong gasLimit for Ethereum transaction using Metamask test dapp

### ISSUE THREAD

**Issue by Toporin** [RabbyHub/Rabby#782]
I am trying Rabby with a test dapp (https://metamask.github.io/test-dapp/) and I get some strange behaviors while doing a simple "send legacy transaction":

* Unrecognized transaction: the transaction shown by Rabby is flagged as "unknown protocol" with "unknown action"
* Wrong gas limit: the transaction shown by Rabby has a "gas" (gas limit?) of "0x2faf080" which is non-standard for a basic Eth transaction (should be 0x5208).

The raw data provided by Rabby is the following:
`{
    "chainId": 1,
    "data": "0x",
    "from": "0xdb8109a158ef6db939c9cfe16fff01779121e187",
    "gas": "0x2faf080",
    "gasPrice": "0xab5d04c00",
    "nonce": "0x0",
    "to": "0x0c54FcCd2e384b4BB6f2E405Bf5Cbc15a017AaFb",
    "value": "0x"
}`

Moreover, I get the same transaction data and confusing warning when doing a "send EIP 1559 transaction". It looks like Rabby converted the EIP-1559 transaction from the Dapp back to a legacy transaction.

Maybe the issue is caused by the tx value being 0x0 (along with data being 0x)?
Metamask displays and processes these transactions correctly.

Attached are 2 screenshots of Rabby
![Screenshot from 2022-05-31 14-38-01](https://user-images.githubusercontent.com/10826856/171190596-908f83f0-5612-4018-9764-6d7de3b17ac5.png)
![Screenshot from 2022-05-31 14-38-48](https://user-images.githubusercontent.com/10826856/171190588-d4cca5fc-1025-460b-853f-720257ebd92b.png)

**Comment by vvvvvv1vvvvvv** [comment]
Since the value is 0, will not happen on a real transfer transaction
