### ISSUE TITLE
AutoLock Wallet Extension

### ISSUE THREAD

**Issue by pax85** [RabbyHub/Rabby#831]
Hi,

is there a way to AutoLock the extension after a period of time?
I only found the "Lock Wallet" Button under Settings.

If not I would appreciate a setting for auto locking the wallet extension after x minutes.

kind regards

**Comment by pax85** [comment]
Is it possible, that this has been implemented? Can't pinpoint it yet, but I regularly have to unlock my rabby wallet recently.

**Comment by vvvvvv1vvvvvv** [comment]
supported now
