### ISSUE TITLE
1inch on Polygon - Limit Order Status Column empty [Bug]

### ISSUE THREAD

**Issue by pax85** [RabbyHub/Rabby#904]
Hi, I've added a comment to #691, but didn't seem to get a reply, so I have copied it here.

When placing Limit Orders on 1inch on the Polygon network, the "Status" Column for "Active Orders" remains empty and is not displayed.

![1](https://user-images.githubusercontent.com/7982498/182592519-bc114f7b-accf-473f-85af-cde9378fb519.png)

This is a screenshot of the same orders, but with MetaMask, where the Status column is correctly displayed.
![2](https://user-images.githubusercontent.com/7982498/182592623-b058cf43-1c73-4095-8826-4eb7931d314d.png)

The limit orders do fill properly on the background, so it seems to be a display related issue.

kind regards

**Comment by vvvvvv1vvvvvv** [comment]
fixed now
