### ISSUE TITLE
Connection popup appears for less than a second then closes

### ISSUE THREAD

**Issue by cybertelx** [RabbyHub/Rabby#908]
I'm having a little issue with Rabby on Brave, but the issue can be reproduced on Ungoogled Chromium too.

When connecting to a site, a Rabby popup shows up and then disappears instantly. A little notification bubble like (1) shows up on the Rabby icon for a second then disappears.

I have tried:
- Setting Brave Wallet to "none" (I already toggled that)
- Disabling all other extensions
- Restarting browser
- Reinstalling Rabby

Chromium version: 104.0.5112.81 (64-bit)

Thank you in advance!

**Comment by ankkax** [comment]
Same issue, it seems to happen only in linux tough, tried in windows and it works. I opened rabby in developer mode and it there is this error
`Form submission canceled because the form is not connected`
`popup.html#/dashboard:0 (anonymous function)`

**Comment by vvvvvv1vvvvvv** [comment]
Can you make a screen recording video so we can reproduce this issue?

**Comment by cybertelx** [comment]
[recording.zip](https://github.com/RabbyHub/Rabby/files/9279926/recording.zip)
It doesn't show the popup as that lasts only for a frame or two, but it does show a notification blink for a bit on the Rabby extension icon.

**Comment by vvvvvv1vvvvvv** [comment]
We found that this might be a issue caused by Brave browser update, could you try install the latest Brave browser in this link https://github.com/brave/brave-browser/releases/tag/v1.44.30 and check issue has been fixed?

download [Brave-Browser-Nightly-x64.dmg](https://github.com/brave/brave-browser/releases/download/v1.44.30/Brave-Browser-Nightly-x64.dmg) if you are MacOS user, and [BraveBrowserNightlySetup.exe](https://github.com/brave/brave-browser/releases/download/v1.44.30/BraveBrowserNightlySetup.exe) for Windows user

Let me know if your issue has been fixed or not, thanks

**Comment by Vyachean** [comment]
I'm seeing the issue in **Chrome 104.0.5112.79**, **Brave 1.42.88**, **1.43.88** and **1.44.30** **Chromium 104.0.5112.81** for Linux, Rabby v0.41.2.

**Comment by vvvvvv1vvvvvv** [comment]
Update: we found that something wrong with Linux users, will fix it asap

**Comment by Philippe734** [comment]
Same issue on my system
OS: Ubuntu Mate 20.04 (Linux)
Brave 1.42.88 in snap release, in private mode, only one extenasion: Rabby
Rabby 0.41.2

As you can on my screen record, the Rabby's icon briefly show the "1", but it fail to connect to web3 sites.

https://user-images.githubusercontent.com/24923693/183605072-a385811e-5098-4fab-89ac-8e02be9088b1.mp4

**Comment by vvvvvv1vvvvvv** [comment]
@Philippe734 @Vyachean @cybertelx @ankkax 
We are trying to fix this issue, here is a test pacakge below, can anyone help to validate if this issue has been fixed?

NOTE: DO NOT import your mnemonic or private key into this package, only import them into the one you installed from Chrome Web Store

[Rabby_linux.zip](https://github.com/RabbyHub/Rabby/files/9289158/Rabby_linux.zip)

**Comment by vvvvvv1vvvvvv** [comment]
https://debankglobal.larksuite.com/docs/docusr6ZvSc0rCRabHGA19I6bLb here is a guide for install the test package

**Comment by Philippe734** [comment]
Tested and successfully connected. Good job.

**Comment by vvvvvv1vvvvvv** [comment]
> Tested and successfully connected. Good job.

Well, will release soon

**Comment by vvvvvv1vvvvvv** [comment]
v0.41.3 has been released, update to the latest version then this issue will be fixed
