### ISSUE TITLE
Support for REBUS network or RPC support

### ISSUE THREAD

**Issue by armaccloud** [RabbyHub/Rabby#974]
This request is for the adding of REBUS network or RPC support.

Chain Name: Rebus Network
Chain ID: 1111
RPC: https://jsonrpc.rebus.nodestake.top/
Symbol: REBUS

**Comment by vvvvvv1vvvvvv** [comment]
Rabby supports custom networks now, it means you can use Rabby with any EVM network, this issue will be closed
